package com.carddemo.card.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity for the {@code CARD} table &mdash; the live-tracer read target of the
 * CardDemo walking skeleton ({@code card-svc}, Spring Boot 3.5 / Java 21).
 *
 * <p>This is the foundational persistence class of the one fully-wired vertical
 * tracer slice: {@code GET /cards/{cardNumber}} performs a REAL Oracle 23ai read
 * ({@code SELECT ... FROM CARD WHERE CARD_NUM = ?}) of a single Flyway-seeded row
 * in PDB {@code FREEPDB1}. The sibling {@code repo.CardRepository}
 * ({@code JpaRepository<Card, String>}), {@code service.CardService}
 * (entity&rarr;DTO mapping), and {@code web.CardController} (implements the generated
 * {@code GET /cards/{cardNumber}} interface) all build on top of this entity.</p>
 *
 * <p><strong>Natural-key mapping.</strong> The entity is keyed on the natural
 * 16-character card number ({@code CARD_NUM}); the surrogate identity primary key
 * {@code CARD_SK} is deliberately kept off the read path and is intentionally NOT
 * mapped here. No JPA identifier-generation strategy is applied anywhere in this
 * class &mdash; key values are supplied by the seed data, never generated by JPA.
 * This mirrors the legacy {@code COCRDSLC} VSAM read keyed on the 16-character
 * card number.</p>
 *
 * <p><strong>Column fidelity.</strong> Column names and lengths mirror
 * {@code db/migration/V1__baseline.sql} exactly, including the load-bearing legacy
 * misspelling {@code EXPIRAION} on {@code CARD_EXPIRAION_DATE} &mdash; the field
 * name {@code cardExpiraionDate} preserves it verbatim so the JPA mapping resolves
 * against the real Oracle schema. The {@code CARD_CVV_CD} column is intentionally
 * not mapped (excluded from the read DTO).</p>
 *
 * <p><strong>Codegen boundary.</strong> This persistence entity is DISTINCT from
 * the generated API DTO {@code com.carddemo.card.model.Card} produced by
 * {@code openapi-generator-maven-plugin} from {@code contracts/card-svc.openapi.yaml}.
 * Entity-to-DTO conversion is the responsibility of
 * {@code com.carddemo.card.service.CardService}, not this class; this file
 * references no generated ({@code .api} / {@code .model}) types and stays free of
 * project-specific dependencies so it compiles as the safe foundation for the
 * repo/service/web layers.</p>
 *
 * <p>Provenance: [SRC: COCRDSLC | CARDDAT] &mdash; app/csd/CARDDEMO.CSD
 * ({@code DEFINE TRANSACTION(CCDL) PROGRAM(COCRDSLC)} over
 * {@code DEFINE FILE(CARDDAT)}); record shape from app/cpy/CVACT02Y.cpy
 * ({@code CARD-RECORD}).</p>
 */
@Entity
@Table(name = "CARD")
public class Card {

    /**
     * Natural key / read key: the 16-character card number ({@code CARD_NUM},
     * {@code VARCHAR2(16) NOT NULL UNIQUE}). Annotated {@code @Id} with no
     * identifier-generation strategy &mdash; the value is supplied by the
     * seed/data, not generated by JPA. Fixes the repository ID type to
     * {@code String} ({@code JpaRepository<Card, String>}).
     */
    @Id
    @Column(name = "CARD_NUM", length = 16, nullable = false)
    private String cardNumber;

    /**
     * Owning account id ({@code CARD_ACCT_ID}, Oracle {@code NUMBER(11)}). Mapped
     * to {@code Long} to hold the full 11-digit range (an {@code int} would
     * overflow).
     */
    @Column(name = "CARD_ACCT_ID")
    private Long accountId;

    /** Embossed cardholder name ({@code CARD_EMBOSSED_NAME}, {@code VARCHAR2(50)}). */
    @Column(name = "CARD_EMBOSSED_NAME", length = 50)
    private String embossedName;

    /**
     * Card expiry date ({@code CARD_EXPIRAION_DATE}, {@code VARCHAR2(10)}). The
     * legacy misspelling {@code EXPIRAION} is preserved VERBATIM in both the
     * column name and this field name; the service layer maps it to the DTO's
     * {@code expiryDate}.
     */
    @Column(name = "CARD_EXPIRAION_DATE", length = 10)
    private String cardExpiraionDate;

    /**
     * Card active status flag ({@code CARD_ACTIVE_STATUS}, Oracle {@code CHAR(1)},
     * {@code Y}/{@code N}). Modeled as {@code String} to carry the single-character
     * flag.
     */
    @Column(name = "CARD_ACTIVE_STATUS", length = 1)
    private String activeStatus;

    /**
     * Public no-argument constructor required by JPA/Hibernate to instantiate the
     * entity via reflection.
     */
    public Card() {
    }

    /**
     * Returns the natural 16-character card number ({@code CARD_NUM}).
     *
     * @return the card number (entity identifier)
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the natural 16-character card number ({@code CARD_NUM}).
     *
     * @param cardNumber the card number to set (entity identifier)
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * Returns the owning account id ({@code CARD_ACCT_ID}).
     *
     * @return the account id, or {@code null} if unset
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * Sets the owning account id ({@code CARD_ACCT_ID}).
     *
     * @param accountId the account id to set
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * Returns the embossed cardholder name ({@code CARD_EMBOSSED_NAME}).
     *
     * @return the embossed name, or {@code null} if unset
     */
    public String getEmbossedName() {
        return embossedName;
    }

    /**
     * Sets the embossed cardholder name ({@code CARD_EMBOSSED_NAME}).
     *
     * @param embossedName the embossed name to set
     */
    public void setEmbossedName(String embossedName) {
        this.embossedName = embossedName;
    }

    /**
     * Returns the card expiry date ({@code CARD_EXPIRAION_DATE}). The accessor name
     * preserves the legacy {@code EXPIRAION} misspelling by JavaBean convention.
     *
     * @return the expiry date string, or {@code null} if unset
     */
    public String getCardExpiraionDate() {
        return cardExpiraionDate;
    }

    /**
     * Sets the card expiry date ({@code CARD_EXPIRAION_DATE}). The accessor name
     * preserves the legacy {@code EXPIRAION} misspelling by JavaBean convention.
     *
     * @param cardExpiraionDate the expiry date string to set
     */
    public void setCardExpiraionDate(String cardExpiraionDate) {
        this.cardExpiraionDate = cardExpiraionDate;
    }

    /**
     * Returns the card active status flag ({@code CARD_ACTIVE_STATUS}, {@code Y}/{@code N}).
     *
     * @return the active status flag, or {@code null} if unset
     */
    public String getActiveStatus() {
        return activeStatus;
    }

    /**
     * Sets the card active status flag ({@code CARD_ACTIVE_STATUS}, {@code Y}/{@code N}).
     *
     * @param activeStatus the active status flag to set
     */
    public void setActiveStatus(String activeStatus) {
        this.activeStatus = activeStatus;
    }
}
