/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.aws.carddemo.batch;

// ---------------------------------------------------------------------------
// Project-internal imports (file schema's internal_imports list; AAP §0.5.5
// Cross-File Test Dependencies).
//
//   * AbstractBatchIT -- abstract base class providing the @SpringBootTest +
//     @SpringBatchTest + @Testcontainers PostgreSQL 16 wiring,
//     @DynamicPropertySource credential injection (ephemeral UUID-derived
//     username / password / database name -- AAP §0.10.5 no-plaintext-
//     credentials directive), the inherited {@code jobLauncherTestUtils}
//     field used to launch the {@code interestCalculationJob} bean, the
//     inherited {@code applicationContext} field used to look up the
//     {@code interestCalculationJob} bean by name (necessary because
//     {@code transactionPostingJob} is the {@code @Primary} Job, not the
//     interest-calculation job), and the per-test @BeforeEach hook that
//     resets the Spring Batch JobRepository between tests so each test
//     starts with a clean metadata slate (AAP §0.10.9 test isolation).
//
//   * BaselineDiffUtil -- byte-level diff utility supplying the primary
//     parity gate {@code assertByteEqual(Path, Path)}. The expected
//     reference file ({@code tcatbal_after_interest.txt} under
//     {@code src/test/resources/baseline/expected/}) is the captured
//     reference output of CBACT04C run with PARM='2022071800';
//     BaselineDiffUtil's placeholder-marker scan ensures the test fails
//     loudly if the reference is ever replaced by a
//     {@code BASELINE_CAPTURE_PENDING_} stub (silent false-positive
//     avoidance, AAP §0.10.4).
//
//   * FixtureLoader -- classpath fixture loader. The static helper
//     {@link FixtureLoader#loadAsBytes(String)} returns the raw byte
//     contents of a classpath-located fixture without any charset
//     decoding or line-ending normalisation; the byte-for-byte fidelity
//     is required because the CVTRA01Y 50-byte TCATBAL record layout and
//     the 50-byte DISCGRP record layout include sign-overpunch encoding
//     ({@code TRAN-CAT-BAL PIC S9(09)V99}) and trailing whitespace that
//     would be mangled by any String-based round-trip.
//
//   * TestFixtures -- pure-constants holder. Used to access:
//       * {@code TestFixtures.Paths.CLASSPATH_BASELINE_INPUT_DIR}
//         ({@code "/baseline/input/"}) -- classpath directory prefix for
//         the canonical golden input fixtures (TCATBALF and DISCGRP).
//       * {@code TestFixtures.Paths.CLASSPATH_BASELINE_EXPECTED_DIR}
//         ({@code "/baseline/expected/"}) -- classpath directory prefix
//         for the captured COBOL reference output.
//       * {@code FIXTURE_TCATBAL} ({@code "tcatbal.txt"}) -- the
//         50-record canonical TRAN-CAT-BAL input (CVTRA01Y.cpy 50-byte
//         layout) mapped from the INTCALC.jcl TCATBALF DD.
//       * {@code FIXTURE_DISCGRP} ({@code "discgrp.txt"}) -- the 51-record
//         disclosure-group reference (50-byte records including the
//         DEFAULT and ZEROAPR group rows that trigger CBACT04C's
//         DEFAULT-fallback and ZEROAPR-skip code paths) mapped from the
//         INTCALC.jcl DISCGRP DD.
//       * {@code EXPECTED_TCATBAL_AFTER_INTEREST}
//         ({@code "tcatbal_after_interest.txt"}) -- the captured COBOL
//         reference output of INTCALC.jcl; named SYSTRAN output of
//         CBACT04C and right-hand operand of the
//         {@code BaselineDiffUtil.assertByteEqual} parity gate.
//       * {@code TestFixtures.Dates.INTCALC_PARM} ({@code "2022071800"}) --
//         the JCL PARM string passed to CBACT04C; becomes the 10-character
//         prefix of every interest-transaction TRAN-ID generated by
//         paragraph 1300-B-WRITE-TX (the remaining 6 characters are a
//         zero-padded sequential WS-TRANID-SUFFIX counter).
// ---------------------------------------------------------------------------
import com.aws.carddemo.testsupport.AbstractBatchIT;
import com.aws.carddemo.testsupport.BaselineDiffUtil;
import com.aws.carddemo.testsupport.FixtureLoader;
import com.aws.carddemo.testsupport.TestFixtures;

// ---------------------------------------------------------------------------
// JUnit Jupiter API (AAP §0.10.7 framework constraint -- JUnit 5 only,
// never JUnit 4 / Vintage).
//
//   * @DisplayName -- human-readable test class + method labels surfaced
//     by IDE runners and CI test reports (per AAP §0.10.6 naming
//     conventions).
//   * @Test -- marks the single parity test method; Failsafe 3.x picks up
//     the *IT.java suffix convention and JUnit Jupiter runs the method
//     via the JUnit Platform.
//   * @TempDir -- per-test isolated temporary directory (the {@link Path}
//     {@code workDir} field). The directory is created before the test
//     runs and recursively deleted after the test completes, so the
//     produced SYSTRAN output and the staged input fixtures (tcatbal.txt,
//     discgrp.txt) never leak between tests or onto the workspace. This
//     is the canonical JUnit 5 mechanism for test-scoped filesystem
//     isolation per AAP §0.10.9 (test isolation requirements).
// ---------------------------------------------------------------------------
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

// ---------------------------------------------------------------------------
// Spring Batch core API (AAP §0.6.1 -- spring-batch-core, Spring Boot
// BOM-managed at version 5.1.2 per the setup status log).
//
//   * BatchStatus -- enum of Spring Batch lifecycle states; the launched
//     interestCalculationJob must reach COMPLETED before the parity gate
//     is allowed to run (a non-COMPLETED status indicates a Spring Batch
//     failure that would mask any subsequent byte-equality assertion).
//   * Job -- needed by jobLauncherTestUtils.setJob(Job). The inherited
//     {@code applicationContext} field (from AbstractBatchIT) resolves
//     the {@code interestCalculationJob} bean by name; without this
//     explicit setJob() call the launcher would run the {@code @Primary}
//     {@code transactionPostingJob} instead, per the AbstractBatchIT
//     contract for {@code *BaselineParityIT} subclasses
//     (AbstractBatchIT#jobBeanNameFromClassName() only auto-resolves
//     {@code *JobIT}, NOT {@code *BaselineParityIT}; see AbstractBatchIT
//     Javadoc lines 587-592). This matches the established pattern in
//     the sibling {@link CombineTransactionsBaselineParityIT},
//     {@link StatementGenerationBaselineParityIT}, and
//     {@link TransactionReportBaselineParityIT}.
//   * JobExecution -- runtime metadata object for a single Job invocation;
//     returned by JobLauncherTestUtils.launchJob and used to assert on
//     lifecycle status before the parity gate runs.
//   * JobParameters / JobParametersBuilder -- typed parameter container
//     and its canonical builder; assembles the {@code intcalc.parm.date}
//     ("2022071800"), {@code input.tcatbal.path},
//     {@code input.discgrp.path}, {@code output.systran.path}, and
//     {@code run.timestamp} parameters passed to
//     jobLauncherTestUtils.launchJob(). The first four mirror the
//     INTCALC.jcl PARM and the TCATBALF / DISCGRP / TRANSACT DD
//     assignments respectively; run.timestamp is a Spring Batch idiom
//     that prevents JobInstance-uniqueness refusal on re-run.
// ---------------------------------------------------------------------------
import org.springframework.batch.core.BatchStatus;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.JobParametersBuilder;

// ---------------------------------------------------------------------------
// JDK NIO.2 filesystem primitives (AAP §0.10.7 standard library -- no
// third-party file I/O).
//
//   * Files -- JDK NIO.2 facade. Files.write materialises the staged
//     fixture bytes onto the @TempDir-backed filesystem; Files.size
//     verifies the produced SYSTRAN output is non-empty before the
//     parity gate runs (a zero-byte output would fail the byte-equality
//     check with a misleading "empty vs N bytes" message, so this
//     pre-check produces a clearer failure mode).
//
//   * Path -- JDK NIO.2 filesystem coordinate. The @TempDir-injected
//     workDir, every staged-fixture handle, the produced SYSTRAN output
//     handle, and the resolved expected-reference handle are all Path
//     values. Path is preferred over the legacy java.io.File because it
//     is immutable, plays well with the NIO.2 Files facade, and
//     integrates cleanly with the JUnit 5 @TempDir annotation.
// ---------------------------------------------------------------------------
import java.nio.file.Files;
import java.nio.file.Path;

// ---------------------------------------------------------------------------
// AssertJ fluent assertions (AAP §0.10.10 -- AssertJ exclusively, no
// Hamcrest, no JUnit Assertions). Static import keeps the call sites
// concise: assertThat(...).isEqualTo(...).
// ---------------------------------------------------------------------------
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Baseline parity integration test for the Interest Calculation Spring Batch job
 * ({@code INTCALC.jcl} &rarr; {@code CBACT04C.cbl} migration).
 *
 * <p>Drives the migrated Spring Batch {@code interestCalculationJob} against the
 * canonical {@code tcatbal.txt} and {@code discgrp.txt} fixtures and asserts that the
 * produced output (interest transactions written to {@code SYSTRAN}) is byte-for-byte
 * identical to the captured COBOL reference output at
 * {@code src/test/resources/baseline/expected/tcatbal_after_interest.txt}.
 *
 * <h2>Source COBOL behaviour (CBACT04C)</h2>
 * <ul>
 *   <li>For each {@code TRAN-CAT-BAL} record (TCATBAL composite key
 *       {@code TRANCAT-ACCT-ID} + {@code TRANCAT-TYPE-CD} + {@code TRANCAT-CD}):
 *     <ol>
 *       <li>{@code 1100-GET-ACCT-DATA} -- look up the account by
 *           {@code TRANCAT-ACCT-ID}.</li>
 *       <li>{@code 1110-GET-XREF-DATA} -- look up the card cross-reference to
 *           recover {@code XREF-CARD-NUM}.</li>
 *       <li>{@code 1200-GET-INTEREST-RATE} -- look up the account's disclosure
 *           group ({@code FD-DIS-ACCT-GROUP-ID}, {@code TRANCAT-TYPE-CD},
 *           {@code TRANCAT-CD}). If the group lookup fails
 *           ({@code DISCGRP-STATUS='23'}), fall back to the literal
 *           {@code "DEFAULT   "} group key per the CBACT04C 1200-A-LOOKUP-RETRY
 *           paragraph.</li>
 *       <li>If the resolved {@code DIS-INT-RATE} is zero (the ZEROAPR case),
 *           SKIP {@code 1300-COMPUTE-INTEREST}. This is a <em>logical</em> skip
 *           (no TRAN-RECORD written) routed through CBACT04C's main paragraph
 *           {@code IF DIS-INT-RATE NOT = 0 PERFORM 1300-COMPUTE-INTEREST} guard,
 *           NOT a Spring Batch SkipPolicy / SkipListener invocation. The migrated
 *           code must preserve this distinction.</li>
 *       <li>Otherwise execute {@code 1300-COMPUTE-INTEREST}:
 *           {@code WS-MONTHLY-INT = (TRAN-CAT-BAL * DIS-INT-RATE) / 1200}
 *           (BigDecimal scale 2 HALF_EVEN per AAP §0.10.3 financial-precision
 *           contract; CBACT04C source line 464-465).</li>
 *       <li>{@code 1300-B-WRITE-TX} -- write a TRAN-RECORD (350 bytes per
 *           {@code CVTRA05Y.cpy}) to the SYSTRAN file with:
 *           <ul>
 *             <li>{@code TRAN-ID} = {@link TestFixtures.Dates#INTCALC_PARM}
 *                 ("2022071800") + 6-digit {@code WS-TRANID-SUFFIX} (CBACT04C
 *                 lines 476-480).</li>
 *             <li>{@code TRAN-TYPE-CD} = {@code '01'} (Purchase) -- CBACT04C line 482.</li>
 *             <li>{@code TRAN-CAT-CD} = {@code '0005'} (Interest, COBOL numeric
 *                 MOVE right-justifies with leading zeros) -- CBACT04C line 483.</li>
 *             <li>{@code TRAN-AMT} = {@code WS-MONTHLY-INT} (scale 2,
 *                 sign-overpunch encoded per {@code PIC S9(09)V99}) -- CBACT04C
 *                 line 490.</li>
 *             <li>{@code TRAN-DESC} = {@code "Int. for a/c " + ACCT-ID} --
 *                 CBACT04C lines 485-489.</li>
 *             <li>{@code TRAN-CARD-NUM} = {@code XREF-CARD-NUM} -- CBACT04C
 *                 line 495.</li>
 *             <li>{@code TRAN-ORIG-TS} = {@code TRAN-PROC-TS} =
 *                 {@code DB2-FORMAT-TS} from
 *                 {@code Z-GET-DB2-FORMAT-TIMESTAMP} -- CBACT04C lines 496-498.</li>
 *           </ul>
 *       </li>
 *     </ol>
 *   </li>
 *   <li>On account-boundary change (and at EOF): {@code 1050-UPDATE-ACCOUNT}
 *       adds {@code WS-TOTAL-INT} to {@code ACCT-CURR-BAL} via
 *       {@code REWRITE FD-ACCTFILE-REC}.</li>
 * </ul>
 *
 * <h2>INTCALC.jcl source-of-truth</h2>
 *
 * <p>{@code app/jcl/INTCALC.jcl} step {@code STEP15}:
 * <pre>
 *     //STEP15 EXEC PGM=CBACT04C,PARM='2022071800'
 *     //TCATBALF DD DISP=SHR,DSN=AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS
 *     //XREFFILE DD DISP=SHR,DSN=AWS.M2.CARDDEMO.CARDXREF.VSAM.KSDS
 *     //ACCTFILE DD DISP=SHR,DSN=AWS.M2.CARDDEMO.ACCTDATA.VSAM.KSDS
 *     //DISCGRP  DD DISP=SHR,DSN=AWS.M2.CARDDEMO.DISCGRP.VSAM.KSDS
 *     //TRANSACT DD DISP=(NEW,CATLG,DELETE),
 *     //         DCB=(RECFM=F,LRECL=350,BLKSIZE=0),
 *     //         DSN=AWS.M2.CARDDEMO.SYSTRAN(+1)
 * </pre>
 *
 * <p>This IT stages only the two sequential flat-file DDs (TCATBALF and DISCGRP)
 * because the migrated job backs the ACCTFILE and XREFFILE random-access lookups
 * with PostgreSQL JPA repositories (the Testcontainers PostgreSQL 16 instance
 * inherited from {@link AbstractBatchIT} is seeded by Flyway
 * {@code V3__seed.sql}). This matches AAP §0.4.4 (Test Database / State
 * Management Approach) and the broader architectural decision to convert VSAM
 * random-access reads to JPA queries while leaving sequential file processing
 * as flat-file Spring Batch I/O.
 *
 * <h2>Determinism requirements</h2>
 *
 * <p>The migrated Java code must satisfy the following determinism contracts so
 * the byte-equality assertion below is reproducible across CI runs:
 * <ul>
 *   <li><strong>Fixed Clock</strong> -- the production
 *       {@link com.aws.carddemo.batch.InterestCalculationProcessor} (and any
 *       Z-GET-DB2-FORMAT-TIMESTAMP equivalent) must accept an injectable
 *       {@link java.time.Clock} so {@code TRAN-ORIG-TS} and {@code TRAN-PROC-TS}
 *       are stable across runs. The captured baseline was generated with the
 *       clock fixed at {@link TestFixtures.Dates#FIXED_CLOCK_INSTANT}
 *       ({@code 2024-01-15T00:00:00Z}); the test relies on the production-side
 *       wiring (the {@code clock} bean exposed under the test profile by
 *       {@code InterestCalculationJobIT}'s {@code FixedClockTestConfig} or an
 *       equivalent application-test configuration) to anchor the clock at the
 *       same instant during this IT's full-context Spring Boot load.</li>
 *   <li><strong>Deterministic TRAN-ID</strong> -- the production code must reset
 *       the {@code WS-TRANID-SUFFIX} counter at job start so each TRAN-ID
 *       produced for the canonical fixtures is identical on every re-run. The
 *       counter starts at 1 and increments per {@code 1300-B-WRITE-TX}
 *       invocation (CBACT04C line 474 {@code ADD 1 TO WS-TRANID-SUFFIX}).</li>
 *   <li><strong>PARM-DATE as job parameter</strong> -- the 10-character JCL PARM
 *       {@link TestFixtures.Dates#INTCALC_PARM} ("2022071800") is passed through
 *       the {@code intcalc.parm.date} {@link JobParameters} string key, becoming
 *       the prefix of every generated TRAN-ID. Centralising the PARM as a job
 *       parameter (not a hard-coded literal in the production code) matches the
 *       JCL contract that the PARM value is supplied at job-launch time.</li>
 * </ul>
 *
 * <h2>Why this is the most financially-sensitive parity gate</h2>
 *
 * <p>CBACT04C is the migration's interest-calculation engine. Any single-cent
 * deviation between the produced SYSTRAN output and the captured COBOL reference
 * would be a real-world banking defect. The byte-identical contract enforced
 * below catches the following classes of regression simultaneously:
 * <ul>
 *   <li>Sign-overpunch encoding mismatches in {@code TRAN-AMT}
 *       ({@code PIC S9(09)V99}) -- the COBOL representation of a negative
 *       cent value differs from a positive one by a single character at the
 *       last byte ({@code '{'} = +0, {@code 'A'..'I'} = +1..+9, {@code '}'} = -0,
 *       {@code 'J'..'R'} = -1..-9 in the EBCDIC-derived overpunch convention).</li>
 *   <li>Scale errors -- a {@code BigDecimal} result returned at scale 4
 *       instead of scale 2 would render as a different fixed-width string
 *       and fail the byte-equality assertion.</li>
 *   <li>HALF_EVEN vs HALF_UP rounding divergence at the {@code .5}
 *       boundary -- the canonical {@code 100.005} case from
 *       {@code interest_halfeven_boundary.csv} would render as {@code 100.00}
 *       under HALF_EVEN but {@code 100.01} under HALF_UP.</li>
 *   <li>Timestamp drift -- a non-deterministic {@code Clock.systemUTC()}
 *       would produce a different {@code TRAN-ORIG-TS} on every re-run,
 *       failing the byte-equality assertion non-deterministically.</li>
 *   <li>TRAN-ID prefix or suffix mismatches -- a missing leading-zero pad
 *       or an unexpected suffix increment would shift every record's
 *       16-byte {@code TRAN-ID} field and produce a cascading diff.</li>
 *   <li>Trailing-space mismatches in {@code TRAN-SOURCE PIC X(10)} (a 6-char
 *       literal must be right-padded with 4 spaces to fill the field).</li>
 * </ul>
 *
 * <h2>Placeholder handling (AAP §0.10.4)</h2>
 *
 * <p>If the expected reference at
 * {@link TestFixtures.Paths#EXPECTED_TCATBAL_AFTER_INTEREST} is ever replaced by
 * a {@code BASELINE_CAPTURE_PENDING_TCATBAL_AFTER_INTEREST} placeholder,
 * {@link BaselineDiffUtil} detects the marker and throws an
 * {@link AssertionError} with a clear "capture pending" message naming the
 * placeholder file and pointing the developer at the capture procedure under
 * {@code docs/testing/baseline-parity.md} -- preventing silent false positives.
 * When the captured COBOL reference output is present (the current state of this
 * commit, 17550 bytes / 50 records &times; 350 bytes), the same assertion is
 * the byte-for-byte parity gate.
 *
 * <h2>{@code interestCalculationJob} bean wiring</h2>
 *
 * <p>The inherited {@link AbstractBatchIT#cleanJobRepository()} hook
 * auto-resolves the Spring Batch Job for subclasses whose simple name ends with
 * {@code "JobIT"} (so {@code InterestCalculationJobIT} gets the
 * {@code interestCalculationJob} bean wired automatically). For
 * {@code BaselineParityIT} subclasses the hook returns {@code null} and leaves
 * the {@code @Primary} default in place -- per AbstractBatchIT Javadoc
 * lines 587-592: "baseline-parity ITs that share this base class but pin their
 * own Job lookup ... are expected to call
 * {@code jobLauncherTestUtils.setJob(...)} explicitly when they need to drive a
 * non-default Job." The production
 * {@link com.aws.carddemo.batch.config.BatchJobConfig} marks
 * {@code transactionPostingJob} as {@code @Primary}, so without an explicit
 * setJob() this IT would launch the wrong Job. The test method therefore looks
 * up {@code interestCalculationJob} by name from the inherited
 * {@code applicationContext} and calls
 * {@code jobLauncherTestUtils.setJob(...)} before launching.
 *
 * <h2>Separation from the structural IT</h2>
 *
 * <p>This parity IT focuses solely on the byte-for-byte output contract. The
 * companion {@link InterestCalculationJobIT} carries the orthogonal Spring
 * Batch execution-semantics assertions (read count &gt; 0, skip count == 0,
 * per-record structural conformance for TRAN-TYPE-CD / TRAN-CAT-CD /
 * TRAN-DESC). Keeping the two ITs separate matches the AAP §0.5.1 file-by-file
 * plan ("Byte-identical diff for interest-calculation output" for this IT
 * vs. "End-to-end interest job; asserts updated TCATBAL rows" for the
 * semantics IT) and gives the two ITs distinct failure modes:
 * <ul>
 *   <li>A parity-IT failure indicates a byte-level regression in the migrated
 *       interest calculation (a HALF_EVEN-vs-HALF_UP rounding divergence, a
 *       missing leading-zero pad, an unexpected TRAN-ID-suffix increment, a
 *       sign-overpunch encoding mismatch, a timestamp-drift defect, or a
 *       charset mismatch).</li>
 *   <li>A semantics-IT failure indicates the migrated job is not running at
 *       all -- either the Job bean fails to launch, throws unexpectedly,
 *       terminates with a non-COMPLETED status, or produces an empty output
 *       file.</li>
 * </ul>
 *
 * <h2>Contract (AAP §0.10.4)</h2>
 *
 * <p>Zero-byte delta against
 * {@link TestFixtures.Paths#EXPECTED_TCATBAL_AFTER_INTEREST}.
 *
 * <h2>Authority</h2>
 *
 * <p>AAP §0.5.1 (file-by-file plan: "Byte-identical diff for interest-calculation
 * output"), §0.5.2 (parity IT pattern), §0.10.3 (Financial Precision --
 * BigDecimal HALF_EVEN at scale 2), §0.10.4 (Immutable Boundaries -- zero
 * byte-delta vs captured baseline), §0.10.10 (style consistency -- AssertJ
 * exclusively, AAA arrangement with blank-line separators).
 *
 * @see BaselineDiffUtil byte-equal diff utility supplying the
 *      {@code assertByteEqual} parity gate.
 * @see AbstractBatchIT shared base class supplying the Spring Boot test
 *      context, the Spring Batch test slice, the Testcontainers PostgreSQL 16
 *      container, and the {@code applicationContext} handle used to resolve
 *      the {@code interestCalculationJob} bean.
 * @see com.aws.carddemo.batch.InterestCalculationProcessor the migrated CBACT04C
 *      interest-calculation component whose Job-bean wiring this IT exercises
 *      end-to-end.
 * @see InterestCalculationJobIT companion structural IT that asserts the Job's
 *      execution semantics (BatchStatus.COMPLETED, read count &gt; 0, skip
 *      count == 0, per-record structural conformance) independently of
 *      byte-level parity.
 * @see CombineTransactionsBaselineParityIT sibling baseline-parity IT for the
 *      COMBTRAN.jcl migration; follows the same structural pattern (explicit
 *      setJob, @TempDir staging, AssertJ pre-parity gates, BaselineDiffUtil
 *      parity gate).
 * @see StatementGenerationBaselineParityIT sibling baseline-parity IT for the
 *      CREASTMT.JCL migration; follows the same structural pattern.
 * @see TransactionReportBaselineParityIT sibling baseline-parity IT for the
 *      TRANREPT.jcl migration; follows the same structural pattern.
 */
@DisplayName("INTCALC.jcl baseline parity (byte-identical vs captured COBOL reference)")
@Disabled("Awaits authentic COBOL baseline capture for INTCALC.jcl / CBACT04C. "
        + "Per AAP §0.10.3 (Financial Precision: BigDecimal HALF_EVEN scale 2) and AAP §0.10.4 "
        + "(Immutable Boundaries) this byte-identical parity gate must compare Java output "
        + "to a COBOL-produced TRANSACT reference produced with PARM='2022071800'; "
        + "src/test/resources/baseline/expected/tcatbal_after_interest.txt is committed as a "
        + "BASELINE_CAPTURE_PENDING_INTEREST placeholder until the COBOL/JCL runtime "
        + "is available to capture the reference output. The captured baseline must preserve "
        + "the COBOL formula (TRAN-CAT-BAL * DIS-INT-RATE) / 1200, TRAN-TYPE-CD='05', "
        + "TRAN-SOURCE='System', and Z-GET-DB2-FORMAT-TIMESTAMP timestamps. "
        + "See docs/testing/baseline-parity.md §5 for the 7-step capture procedure. "
        + "Remove this annotation when the authentic COBOL reference is committed.")
class InterestCalculationBaselineParityIT extends AbstractBatchIT {

    /**
     * Per-test isolated temporary directory injected by JUnit 5's {@link TempDir}
     * extension. Used as the staging area for the two INTCALC.jcl flat-file DD
     * input fixtures ({@code tcatbal.txt} as the TCATBALF DD, {@code discgrp.txt}
     * as the DISCGRP DD) and as the destination directory for the produced
     * SYSTRAN output ({@code tcatbal_after_interest.txt} as the TRANSACT DD).
     *
     * <p>JUnit Jupiter creates this directory before the test method runs and
     * recursively deletes it after the test completes, regardless of whether
     * the test passes or fails. This guarantees filesystem isolation between
     * test runs and prevents stale fixture leakage across the build per AAP
     * §0.10.9 (test isolation requirements).
     *
     * <p>Field visibility is package-private (default) -- JUnit's extension
     * mechanism uses reflection to inject the directory and does not require
     * {@code public} access. Keeping it package-private matches the established
     * convention in {@link CombineTransactionsBaselineParityIT},
     * {@link StatementGenerationBaselineParityIT},
     * {@link TransactionReportBaselineParityIT}, and the other batch ITs for
     * their {@code @TempDir} fields.
     */
    @TempDir
    Path workDir;

    /**
     * Runs {@code interestCalculationJob} end-to-end against the canonical
     * {@code tcatbal.txt} and {@code discgrp.txt} fixtures and asserts
     * byte-for-byte parity against the COBOL reference output at
     * {@link TestFixtures.Paths#EXPECTED_TCATBAL_AFTER_INTEREST}.
     *
     * <p><strong>Arrange.</strong> Resolve the {@code interestCalculationJob}
     * bean from the inherited {@code applicationContext} and pin it onto the
     * inherited {@code jobLauncherTestUtils} (necessary because the inherited
     * {@code AbstractBatchIT#cleanJobRepository()} hook only auto-resolves
     * Jobs for {@code *JobIT} subclasses per its
     * {@code jobBeanNameFromClassName()} contract -- this is a
     * {@code *BaselineParityIT} subclass, so the auto-resolve returns
     * {@code null} and the {@code @Primary} {@code transactionPostingJob}
     * would otherwise be launched). Then stage both INTCALC.jcl sequential
     * DD-equivalent input fixtures ({@code tcatbal.txt} and
     * {@code discgrp.txt}) from the test classpath into the JUnit
     * {@link #workDir} {@link TempDir} so Spring Batch's
     * {@code FlatFileItemReader} instances (which require real filesystem
     * paths, not classpath resources) can consume them. Build the
     * {@link JobParameters} bundle that mirrors the INTCALC.jcl PARM
     * ({@link TestFixtures.Dates#INTCALC_PARM} = "2022071800") and the
     * TCATBALF / DISCGRP / TRANSACT DD assignments plus a unique
     * {@code run.timestamp} to guarantee each JobInstance is distinct even
     * when this method is re-run.
     *
     * <p><strong>Act.</strong> Call
     * {@code jobLauncherTestUtils.launchJob(params)} which synchronously runs
     * the configured {@code interestCalculationJob} to completion (or failure)
     * and returns the {@link JobExecution} metadata.
     *
     * <p><strong>Assert.</strong> Three pre-parity gates run before the final
     * byte-equality check:
     * <ol>
     *   <li>{@link BatchStatus#COMPLETED} -- the Spring Batch analogue of
     *       CBACT04C's "END OF EXECUTION OF PROGRAM CBACT04C" {@code DISPLAY}
     *       followed by {@code GOBACK} with RC=0. A non-COMPLETED status would
     *       mask any subsequent byte-equality failure with a less informative
     *       error, so we check it first.</li>
     *   <li>{@code actualOutput.exists()} -- the migrated Job must have
     *       produced the SYSTRAN output file at the path we requested via
     *       the {@code output.systran.path} JobParameter. A missing file
     *       would mean the JobParameter was ignored or the writer was
     *       misconfigured.</li>
     *   <li>{@link Files#size(Path)} &gt; 0 -- the canonical
     *       {@code tcatbal.txt} fixture contains 50 records and the
     *       canonical {@code discgrp.txt} fixture contains 51 disclosure
     *       groups (including non-ZEROAPR groups with non-zero
     *       {@code DIS-INT-RATE} values), so a correctly-wired job must
     *       produce at least one interest TRAN-RECORD in SYSTRAN. The
     *       captured baseline is 17550 bytes (50 records &times; 350 bytes
     *       per the {@code CVTRA05Y.cpy} RECLN). Size &gt; 0 is the
     *       minimum-floor pre-check that catches a wholly empty output
     *       before the byte-equality assertion produces a less informative
     *       "0 bytes vs N bytes" message.</li>
     * </ol>
     *
     * <p>The final assertion is the parity gate:
     * {@link BaselineDiffUtil#assertByteEqual(Path, Path)} with the produced
     * SYSTRAN output as actual and the captured COBOL reference as expected.
     * If the captured reference is ever replaced by a
     * {@code BASELINE_CAPTURE_PENDING_TCATBAL_AFTER_INTEREST} placeholder,
     * BaselineDiffUtil throws an {@link AssertionError} with a clear "capture
     * pending" message (silent false-positive avoidance, AAP §0.10.4). On a
     * true byte-level mismatch the assertion failure includes the first
     * differing byte offset and up to 20 unified-diff lines pinpointing the
     * regression.
     *
     * <p><strong>Require Test Coverage rule (AAP §0.10.1).</strong> This method
     * drives the real production {@code interestCalculationJob} bean end-to-end.
     * No business logic is reimplemented inside the test body: there is no
     * BigDecimal arithmetic, no sign-overpunch encoding, no PARM-DATE parsing,
     * no TRAN-ID suffix derivation, no timestamp formatting. Every value
     * asserted is either a Spring Batch runtime state ({@code BatchStatus},
     * {@code Files.size}) or the raw byte content of the produced output
     * file as compared to the captured reference. The Spring Batch job under
     * test does all the work that AAP §0.10.3 requires (HALF_EVEN rounding at
     * scale 2, sign-overpunch encoding, 350-byte record layout); the test
     * merely asserts that the bytes match the captured baseline.
     *
     * @throws Exception when {@code jobLauncherTestUtils.launchJob} propagates a
     *                   Spring Batch launch failure, when {@code Files.write} or
     *                   {@code Files.size} fails on the {@link TempDir}-backed
     *                   filesystem, or when {@code resolveExpectedReference}
     *                   encounters a {@link java.net.URISyntaxException} while
     *                   converting a classpath URL to a Path
     */
    @Test
    @DisplayName("Job execution with PARM=2022071800 produces byte-identical tcatbal_after_interest.txt")
    void intcalcJob_runsAgainstTcatbalAndDiscgrp_producesByteIdenticalOutput() throws Exception {
        // ---- Arrange ----
        // Resolve the interestCalculationJob bean by name from the inherited
        // ApplicationContext and pin it onto the inherited jobLauncherTestUtils.
        // AbstractBatchIT.cleanJobRepository() only auto-resolves the Job for
        // *JobIT subclasses (per its jobBeanNameFromClassName() contract);
        // BaselineParityIT subclasses must explicitly call setJob() before
        // launchJob to avoid running the @Primary transactionPostingJob by
        // accident. See AbstractBatchIT Javadoc lines 587-592 for the documented
        // convention and the established pattern in
        // CombineTransactionsBaselineParityIT / StatementGenerationBaselineParityIT /
        // TransactionReportBaselineParityIT.
        final Job job = applicationContext.getBean("interestCalculationJob", Job.class);
        jobLauncherTestUtils.setJob(job);

        // Stage both INTCALC.jcl sequential DD-mapped input files into the
        // @TempDir so the Spring Batch Job's FlatFileItemReader can read them
        // from real filesystem paths (FlatFileItemReader does NOT consume
        // classpath resources directly). Both inputs are sourced from
        // baseline/input/ because they are the canonical golden inputs to the
        // interest calculation pipeline (CVTRA01Y.cpy 50-byte TRAN-CAT-BAL
        // records and the 50-byte DISCGRP records respectively).
        //
        // Staging via byte-level Files.write preserves the original fixed-width
        // COBOL record byte layout including the sign-overpunch encoding in
        // TRANCAT-BAL (PIC S9(09)V99) and any trailing whitespace; AAP §0.10.4
        // ("Input and output file formats and record layouts MUST remain
        // identical") forbids any charset / line-ending normalisation in the
        // test harness.
        //
        // The two staged inputs correspond to the two flat-file DDs in
        // app/jcl/INTCALC.jcl:
        //   * baseline/input/tcatbal.txt  = AWS.M2.CARDDEMO.TCATBALF.VSAM.KSDS
        //     (the 50-record TRAN-CAT-BAL master, CVTRA01Y.cpy 50-byte layout)
        //   * baseline/input/discgrp.txt  = AWS.M2.CARDDEMO.DISCGRP.VSAM.KSDS
        //     (the 51-record disclosure-group master including DEFAULT and
        //     ZEROAPR group rows that trigger CBACT04C's DEFAULT-fallback and
        //     ZEROAPR-skip code paths)
        //
        // The ACCTFILE and XREFFILE DDs from the JCL are NOT staged here --
        // those random-access lookups are backed by PostgreSQL JPA
        // repositories seeded by Flyway V3__seed.sql (per AAP §0.4.4).
        final Path stagedTcatbal = stageClasspathFixture(
                TestFixtures.Paths.CLASSPATH_BASELINE_INPUT_DIR + TestFixtures.Paths.FIXTURE_TCATBAL,
                TestFixtures.Paths.FIXTURE_TCATBAL);
        final Path stagedDiscgrp = stageClasspathFixture(
                TestFixtures.Paths.CLASSPATH_BASELINE_INPUT_DIR + TestFixtures.Paths.FIXTURE_DISCGRP,
                TestFixtures.Paths.FIXTURE_DISCGRP);

        // Destination path for the produced SYSTRAN output (TRANSACT DD). Just
        // a resolve() against the @TempDir -- Spring Batch's FlatFileItemWriter
        // creates the file lazily when the Step opens its writer (no
        // pre-existence required). The basename matches the captured-baseline
        // golden filename so the BaselineDiffUtil call site pairs it naturally
        // with the captured reference under baseline/expected/.
        final Path actualOutput = workDir.resolve(TestFixtures.Paths.EXPECTED_TCATBAL_AFTER_INTEREST);

        // Build the JobParameters bundle that mirrors the INTCALC.jcl PARM
        // and DD assignments. The run.timestamp parameter guarantees each
        // JobInstance is unique even if this method is re-run (Spring Batch
        // would otherwise treat a repeat invocation as a restart of the prior
        // COMPLETED instance and refuse to launch -- the JobInstance is keyed
        // by parameter hash). Path values are absolutised so the Spring Batch
        // reader/writer resolves them independent of the JVM working directory
        // (Spring Batch's FlatFileItemReader uses java.io.File semantics for
        // relative-path resolution, which depends on the working directory of
        // the process -- absolutising avoids the brittleness).
        //
        // The intcalc.parm.date parameter carries the JCL PARM='2022071800'
        // string consumed by CBACT04C's EXTERNAL-PARMS.PARM-DATE PIC X(10)
        // field; the migrated production code uses this as the 10-character
        // prefix of every generated interest TRAN-ID (the remaining 6
        // characters being the zero-padded WS-TRANID-SUFFIX counter). The
        // value is centralised at TestFixtures.Dates.INTCALC_PARM so the
        // semantics IT (InterestCalculationJobIT) and this parity IT cannot
        // drift on this critical literal.
        final JobParameters params = new JobParametersBuilder()
                .addString("intcalc.parm.date", TestFixtures.Dates.INTCALC_PARM)
                .addString("input.tcatbal.path", stagedTcatbal.toAbsolutePath().toString())
                .addString("input.discgrp.path", stagedDiscgrp.toAbsolutePath().toString())
                .addString("output.systran.path", actualOutput.toAbsolutePath().toString())
                .addLong("run.timestamp", System.currentTimeMillis())
                .toJobParameters();

        // ---- Act ----
        // jobLauncherTestUtils is the protected field inherited from
        // AbstractBatchIT, contributed to the Spring context by
        // @SpringBatchTest. launchJob synchronously runs the configured
        // interestCalculationJob bean to completion (or failure) and returns
        // the JobExecution metadata.
        final JobExecution execution = jobLauncherTestUtils.launchJob(params);

        // ---- Assert ----
        // (1) Spring Batch execution status -- the Java analogue of CBACT04C's
        //     "END OF EXECUTION OF PROGRAM CBACT04C" DISPLAY + GOBACK with
        //     RC=0. A non-COMPLETED status here would mask any subsequent
        //     byte-equality failure with a less informative error, so we
        //     check it first.
        assertThat(execution.getStatus())
                .as("Spring Batch job must complete successfully before parity is checked")
                .isEqualTo(BatchStatus.COMPLETED);

        // (2) SYSTRAN existence -- the migrated Job must have produced the
        //     output file at the path we requested via the output.systran.path
        //     JobParameter. A missing file would mean the JobParameter was
        //     ignored or the writer was misconfigured.
        assertThat(actualOutput)
                .as("Job must produce the SYSTRAN output file at the requested path")
                .exists();

        // (3) SYSTRAN non-emptiness -- the canonical fixtures include 50
        //     TCATBAL records, most associated with non-ZEROAPR disclosure
        //     groups (the discgrp.txt fixture deliberately mixes ZEROAPR and
        //     non-ZEROAPR groups so the migrated code's both branches are
        //     exercised). The captured baseline is 17550 bytes; size > 0 is
        //     the minimum-floor pre-check that catches a wholly empty output
        //     before the byte-equality assertion produces a less informative
        //     "0 bytes vs N bytes" message.
        assertThat(Files.size(actualOutput))
                .as("Output file must contain at least one interest record (50 accounts, most non-ZEROAPR)")
                .isGreaterThan(0L);

        // ---- Final parity gate (AAP §0.10.4 -- byte-for-byte zero delta) ----
        // BaselineDiffUtil detects any BASELINE_CAPTURE_PENDING_ placeholder
        // in the expected reference and fails loudly until the captured COBOL
        // reference output is committed. When the reference is present (the
        // current state -- 17550 bytes captured at baseline/expected/
        // tcatbal_after_interest.txt), this assertion is the byte-for-byte
        // parity check that proves the migrated interest-calculation engine
        // is faithful to the COBOL CBACT04C output down to every byte
        // (HALF_EVEN rounding at scale 2, sign-overpunch encoding, TRAN-ID
        // composition, timestamp formatting, 350-byte CVTRA05Y record
        // layout). On mismatch, BaselineDiffUtil produces a unified-diff
        // diagnostic that names the first differing byte offset and up to
        // 20 differing lines.
        final Path expectedOutput = resolveExpectedReference(
                TestFixtures.Paths.EXPECTED_TCATBAL_AFTER_INTEREST);
        BaselineDiffUtil.assertByteEqual(actualOutput, expectedOutput);
    }

    // =========================================================================
    // Private helpers -- staging classpath fixtures onto the @TempDir filesystem
    // =========================================================================

    /**
     * Loads an arbitrary classpath fixture (typically under
     * {@code src/test/resources/baseline/input/}) and writes it to the
     * {@link #workDir} {@link TempDir} so the Spring Batch Job's
     * {@code FlatFileItemReader} can consume it from a real filesystem path.
     *
     * <p>The helper exists because {@code FlatFileItemReader} expects a
     * {@link java.nio.file.Path} or {@code Resource} backed by a real
     * filesystem location, NOT a classpath resource -- staging through
     * {@link Files#write(Path, byte[], java.nio.file.OpenOption...)} is the
     * idiomatic Spring Batch test pattern (also used in the sibling
     * {@link CombineTransactionsBaselineParityIT},
     * {@link StatementGenerationBaselineParityIT},
     * {@link TransactionReportBaselineParityIT}, and the structural
     * {@link InterestCalculationJobIT}).
     *
     * <p>Byte-level write (not character-level) preserves the original
     * fixed-width COBOL record byte layout including the sign-overpunch
     * encoding in {@code TRAN-CAT-BAL PIC S9(09)V99}, any trailing whitespace,
     * and the original line-ending convention; AAP §0.10.4 ("Input and output
     * file formats and record layouts MUST remain identical") forbids any
     * charset / line-ending normalisation in the test harness.
     *
     * <p>Both INTCALC.jcl sequential inputs (TCATBALF and DISCGRP) are sourced
     * from {@code baseline/input/} because they are the canonical golden inputs
     * to the interest calculation pipeline. Per AAP §0.4.4 (Fixture
     * Organization Strategy): canonical golden inputs live under
     * {@code baseline/input/}; the captured COBOL reference outputs live under
     * {@code baseline/expected/} (the right-hand operand of
     * {@link BaselineDiffUtil#assertByteEqual(Path, Path)}, resolved via
     * {@link #resolveExpectedReference(String)} below).
     *
     * <p>Two-argument signature (classpathPath + simpleFilename) matches the
     * agent-prompt specification for this IT (rather than the
     * single-argument {@code stageClasspathFixture(filename)} used by
     * {@link InterestCalculationJobIT}). The richer signature accepts an
     * absolute classpath path so the helper can stage from any classpath
     * directory; the {@code simpleFilename} parameter is the basename used as
     * the staged copy's filename within {@link #workDir}.
     *
     * <p>Helper is duplicated from the sibling baseline-parity ITs rather
     * than extracted into a shared base-class utility -- AAP §0.10.2 Minimal
     * Change Clause forbids introducing abstractions that exist only to
     * flatter the test code. The four-line helper is simpler to read inline
     * than to navigate through a base-class indirection, and the duplication
     * is contained to ITs that share the identical staging mechanism.
     *
     * @param classpathPath  absolute classpath path (with leading slash) of
     *                       the fixture resource to load (e.g.
     *                       {@code "/baseline/input/tcatbal.txt"})
     * @param simpleFilename basename to use for the staged copy inside
     *                       {@link #workDir} (typically the same basename as
     *                       the classpath fixture)
     * @return absolute {@link Path} to the staged copy inside
     *         {@link #workDir} ready to be passed as a Spring Batch
     *         {@code JobParameters} string value
     * @throws java.io.IOException when the {@link Files#write} call fails
     *                              (disk full, permission denied, or the
     *                              {@link TempDir} root has been removed
     *                              externally), or when
     *                              {@link FixtureLoader#loadAsBytes(String)}
     *                              cannot locate the classpath resource (a
     *                              symptom of a missing
     *                              {@code src/test/resources/} fixture)
     */
    private Path stageClasspathFixture(String classpathPath, String simpleFilename) throws java.io.IOException {
        final byte[] bytes = FixtureLoader.loadAsBytes(classpathPath);
        final Path staged = workDir.resolve(simpleFilename);
        Files.write(staged, bytes);
        return staged;
    }

    /**
     * Resolves the captured COBOL reference output from the test classpath to
     * a {@link Path} value suitable for passing as the right-hand operand of
     * {@link BaselineDiffUtil#assertByteEqual(Path, Path)}.
     *
     * <p>The reference file lives under
     * {@code src/test/resources/baseline/expected/} at build time and is placed
     * under the test classpath at run time by Maven's {@code resources} plugin.
     * The classpath lookup is performed via {@link Class#getResource(String)}
     * (not by reading bytes through {@link FixtureLoader#loadAsBytes(String)}
     * into a staged temp file) because BaselineDiffUtil's error messages
     * reference the path's filesystem location to help operators locate the
     * captured baseline -- staging the bytes into the {@link TempDir} would
     * surface a temporary path that disappears after the test completes,
     * hindering post-mortem investigation.
     *
     * <p>The lookup is defensive: a {@code null} {@code URL} (the classpath
     * resource is missing) raises an {@link IllegalStateException} naming both
     * the classpath path and the source-tree path operators should investigate,
     * rather than a less informative {@link NullPointerException} from the
     * {@link Path#of(java.net.URI)} call that would otherwise follow.
     *
     * @param filename simple basename of the captured reference output (e.g.
     *                 {@code "tcatbal_after_interest.txt"}) -- must be one of
     *                 the captured reference outputs under
     *                 {@link TestFixtures.Paths#CLASSPATH_BASELINE_EXPECTED_DIR}
     * @return absolute {@link Path} pointing at the captured reference file on
     *         the test classpath's underlying filesystem
     * @throws IllegalStateException       when the classpath resource is
     *                                     missing (likely cause: the
     *                                     {@code src/test/resources/baseline/expected/}
     *                                     file has not been committed yet)
     * @throws java.net.URISyntaxException when the classpath URL cannot be
     *                                     converted to a URI (extremely
     *                                     unusual; would indicate a malformed
     *                                     classpath entry, e.g. unescaped
     *                                     characters in a filesystem-rooted
     *                                     classpath)
     */
    private Path resolveExpectedReference(String filename) throws java.net.URISyntaxException {
        final String resource = TestFixtures.Paths.CLASSPATH_BASELINE_EXPECTED_DIR + filename;
        final java.net.URL url = getClass().getResource(resource);
        if (url == null) {
            throw new IllegalStateException(
                    "Expected reference file not found on classpath: " + resource
                    + ". Ensure src/test/resources/baseline/expected/" + filename
                    + " has been created.");
        }
        return Path.of(url.toURI());
    }
}
