package com.cardemo.batch.jobs;

import com.cardemo.batch.processors.TransactionCombineProcessor;
import com.cardemo.config.AwsConfig;
import com.cardemo.model.entity.Transaction;
import com.cardemo.repository.TransactionRepository;
import io.awspring.cloud.s3.S3Resource;
import io.awspring.cloud.s3.S3Template;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.item.ItemWriter;
import org.springframework.batch.item.support.IteratorItemReader;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.transaction.PlatformTransactionManager;

/**
 * Spring Batch {@code @Configuration} that assembles <strong>Stage&nbsp;3</strong> of the greenfield
 * Java&nbsp;25 LTS + Spring&nbsp;Boot&nbsp;3.5.x CardDemo batch pipeline &mdash; the
 * <strong>Combine Transactions</strong> job. It is the faithful translation of the legacy JES job
 * {@code app/jcl/COMBTRAN.jcl}.
 *
 * <h2>Provenance &amp; authority &mdash; a JCL utility job, NOT a COBOL program</h2>
 * <p>Translated from the frozen AWS CardDemo COBOL/JCL baseline at commit SHA {@code 27d6c6f}. Unlike
 * most stages in the estate, {@code COMBTRAN} has <strong>no COBOL program</strong>: it is a pure
 * <em>DFSORT&nbsp;+&nbsp;IDCAMS&nbsp;REPRO</em> utility job. The JCL source is <strong>read-only</strong>
 * reference material and is <strong>never copied</strong> into this repository; traceability is by commit
 * SHA only (AAP &sect;0.7.2). Per the <strong>Minimal Change Clause</strong> (AAP &sect;0.7.1) this
 * migration reproduces the sort-and-reload behaviour <em>exactly</em> &mdash; it invents no transformation
 * logic &mdash; and documents every technology substitution at its point of change. The application base
 * package is {@code com.cardemo} (decision <strong>D-006</strong> &mdash; deliberately <em>not</em>
 * {@code com.carddemo}).
 *
 * <h2>Source contract &mdash; {@code COMBTRAN.jcl} (two steps, preserved exactly)</h2>
 * <ol>
 *   <li><strong>{@code //STEP05R EXEC PGM=SORT} (DFSORT).</strong> {@code SORTIN} is the
 *       <em>concatenation</em> of two generation-data-group inputs &mdash;
 *       {@code AWS.M2.CARDDEMO.TRANSACT.BKUP(0)} (the prior transaction-master backup) followed by
 *       {@code AWS.M2.CARDDEMO.SYSTRAN(0)} (the interest transactions generated by Stage&nbsp;2). The
 *       {@code SYMNAMES} statement defines {@code TRAN-ID,1,16,CH} (the 16&nbsp;bytes at positions
 *       1&ndash;16, character data) and {@code SYSIN} requests {@code SORT FIELDS=(TRAN-ID,A)} &mdash; an
 *       <strong>ascending</strong> sort on that 16-character transaction id. The merged, sorted output is
 *       written to {@code SORTOUT = AWS.M2.CARDDEMO.TRANSACT.COMBINED(+1)}.</li>
 *   <li><strong>{@code //STEP10 EXEC PGM=IDCAMS} ({@code REPRO}).</strong>
 *       {@code REPRO INFILE(TRANSACT) OUTFILE(TRANVSAM)} bulk-loads the sorted {@code COMBINED} sequential
 *       file into the VSAM KSDS {@code AWS.M2.CARDDEMO.TRANSACT.VSAM.KSDS}.</li>
 * </ol>
 * <p><strong>Net behaviour:</strong> merge the prior transaction-master backup ({@code BKUP}) with the
 * Stage&nbsp;2 interest transactions ({@code SYSTRAN}), order the union ascending by transaction id, and
 * (re)load it into the transaction master. The job performs <strong>no</strong> per-record
 * transformation, deduplication or validation.</p>
 *
 * <h2>Technology substitutions (AAP &sect;0.1.2 / &sect;0.7.6 &mdash; documented at the point of change)</h2>
 * <table border="1">
 *   <caption>{@code COMBTRAN} construct &rarr; Java target</caption>
 *   <tr><th>Legacy construct</th><th>Java replacement</th><th>Location</th></tr>
 *   <tr><td>{@code SORTIN} = {@code BKUP(0)} concatenated with {@code SYSTRAN(0)}</td>
 *       <td>{@code TransactionRepository.findAll()} (BKUP, the current PostgreSQL master) concatenated
 *           with the Stage-2 interest transactions read from S3 {@code carddemo-batch-output} (SYSTRAN)</td>
 *       <td>{@link #combineTransactionsReader()}</td></tr>
 *   <tr><td>{@code SYMNAMES TRAN-ID,1,16,CH} + {@code SORT FIELDS=(TRAN-ID,A)}</td>
 *       <td>{@link TransactionCombineProcessor#BY_TRAN_ID} full {@code List.sort(...)}</td>
 *       <td>{@link #combineTransactionsReader()}</td></tr>
 *   <tr><td>{@code STEP10 IDCAMS REPRO} (bulk load into the KSDS)</td>
 *       <td>{@code TransactionRepository.saveAll(...)} bulk merge-by-PK</td>
 *       <td>{@link #combineTransactionsWriter()}</td></tr>
 *   <tr><td>GDG generations {@code BKUP(0)} / {@code SYSTRAN(0)} / {@code COMBINED(+1)}</td>
 *       <td>The PostgreSQL {@code transaction} table + versioned S3 objects (decision
 *           <strong>D-003</strong>)</td>
 *       <td>repository + S3</td></tr>
 * </table>
 *
 * <h2>Why a collect-then-sort reader (the faithful DFSORT equivalent)</h2>
 * <p>DFSORT performs a <strong>global</strong> ordering of the entire {@code SORTIN} concatenation before
 * a single record is written to {@code SORTOUT}. A streaming, chunk-oriented {@code ItemReader} cannot
 * sort globally, so {@link #combineTransactionsReader()} collects the whole {@code BKUP + SYSTRAN} union
 * into one list, sorts it once with {@link TransactionCombineProcessor#BY_TRAN_ID}, and then streams the
 * sorted result via an {@link IteratorItemReader}. For the bounded volumes of this dataset this is the
 * faithful, parity-preserving equivalent of the DFSORT global sort. The comparator is the
 * <strong>sibling-exposed</strong> {@link TransactionCombineProcessor#BY_TRAN_ID} &mdash; the single
 * source of truth for the {@code SORT FIELDS=(TRAN-ID,A)} field spec; this job deliberately defines
 * <strong>no</strong> comparator of its own.</p>
 *
 * <h2>Why {@code saveAll} reproduces {@code REPRO} exactly</h2>
 * <p>{@code IDCAMS REPRO} replaces the contents of the target cluster. Because {@link Transaction}'s
 * {@code @Id} ({@code tranId}) is an <em>assigned</em> 16-character key (not generated),
 * {@code saveAll} merges by primary key: rows already present in the master (the {@code BKUP} half, read
 * back by {@code findAll()}) update in place, and the new Stage-2 interest rows (the {@code SYSTRAN} half)
 * insert. The load is therefore idempotent with no duplicate keys, matching {@code REPRO}'s full-reload
 * semantics.</p>
 *
 * <h2>SYSTRAN read aligns with Stage&nbsp;2's writer (the handoff contract)</h2>
 * <p>The interest transactions are staged to S3 by {@code InterestCalculationJob} (Stage&nbsp;2) as
 * fixed-width 350-byte {@code CVTRA05Y} records (UTF-8) under keys
 * {@code systran/<yyyyMMdd>/<tranId>.dat} in the {@code carddemo-batch-output} bucket.
 * {@link #combineTransactionsReader()} reads back exactly that representation:
 * {@link #deserializeSystranRecord(String)} is the precise inverse of Stage&nbsp;2's serializer (same
 * field offsets, same {@code yyyy-MM-dd-HH.mm.ss.SSSSSS} timestamp rendering, same implied-decimal amount
 * encoding). If the staging bucket is unavailable in a given environment, the reader degrades gracefully
 * to a {@code BKUP}-only reload (see {@link #readStagedSystranTransactions()}) while always keeping the
 * comparator-based full sort.</p>
 *
 * <h2>Spring Batch 5.x infrastructure (AAP &sect;0.7.8)</h2>
 * <p>Built with the Spring&nbsp;Batch&nbsp;5.x builder API ({@link StepBuilder}/{@link JobBuilder} with an
 * explicit {@link JobRepository} and {@link PlatformTransactionManager}). The deprecated
 * {@code StepBuilderFactory}/{@code JobBuilderFactory} are <strong>not</strong> used, and
 * {@code @EnableBatchProcessing} is <strong>not</strong> declared anywhere (in Spring&nbsp;Boot&nbsp;3.x it
 * would disable Boot's batch auto-configuration). The {@link JobRepository} and
 * {@link PlatformTransactionManager} are the auto-configured beans documented by
 * {@code com.cardemo.config.BatchConfig}.</p>
 *
 * @see TransactionCombineProcessor
 * @see TransactionRepository
 * @see Configuration
 */
// Explicit configuration-bean name to avoid a BeanDefinitionOverrideException. The default component name
// for this @Configuration class is its decapitalized simple name, "combineTransactionsJob", which would
// collide with the Job @Bean method of the same name below (Spring Boot disables bean-definition
// overriding by default). Naming the @Configuration bean distinctly lets the Job bean keep the natural
// name "combineTransactionsJob" (the name the pipeline orchestrator resolves). This mirrors the sibling
// InterestCalculationJob ("interestCalculationJobConfiguration").
@Configuration("combineTransactionsJobConfiguration")
public class CombineTransactionsJob {

    /** SLF4J logger for diagnostic messages (SYSTRAN staging availability and read counts). */
    private static final Logger log = LoggerFactory.getLogger(CombineTransactionsJob.class);

    /**
     * Chunk size for the combine step. This is a <strong>tuning</strong> value only and does not affect
     * parity: the DFSORT global ordering is performed once, up-front, by {@link #combineTransactionsReader()}
     * before any chunk is read, and the {@code saveAll} writer is a content-preserving bulk merge, so the
     * chunk boundary never splits or reorders the sorted stream.
     */
    private static final int CHUNK_SIZE = 100;

    /**
     * S3 key prefix under which Stage&nbsp;2 ({@code InterestCalculationJob}) stages the SYSTRAN interest
     * transactions ({@code systran/<yyyyMMdd>/<tranId>.dat}). Mirrors the prefix Stage&nbsp;2's writer
     * uses; the reader lists this prefix to gather the {@code SYSTRAN(0)} half of the {@code SORTIN}
     * concatenation.
     */
    private static final String S3_SYSTRAN_KEY_PREFIX = "systran/";

    /**
     * Fixed SYSTRAN record length. The legacy {@code TRANSACT} DD is {@code RECFM=F LRECL=350} and the
     * record layout is {@code CVTRA05Y} ({@code 01 TRAN-RECORD}, RECLN&nbsp;350); Stage&nbsp;2 stages each
     * object at exactly this length, so the deserializer parses fixed offsets within a 350-character record
     * (external-interface contract, AAP &sect;0.7.2).
     */
    private static final int SYSTRAN_RECORD_LENGTH = 350;

    /** Scale of {@code TRAN-AMT PIC S9(09)V99} (two fractional digits); mirrors Stage&nbsp;2's encoder. */
    private static final int AMOUNT_SCALE = 2;

    /**
     * Full 26-character DB2 timestamp pattern ({@code yyyy-MM-dd-HH.mm.ss.SSSSSS}) matching the COBOL
     * {@code Z-GET-DB2-FORMAT-TIMESTAMP} rendering of {@code TRAN-ORIG-TS}/{@code TRAN-PROC-TS}
     * ({@code PIC X(26)}). Identical to the formatter Stage&nbsp;2's writer uses, so the read round-trips.
     */
    private static final DateTimeFormatter DB2_TIMESTAMP_FULL =
            DateTimeFormatter.ofPattern("yyyy-MM-dd-HH.mm.ss.SSSSSS");

    /**
     * Identity {@code ItemProcessor} that also exposes the canonical {@code COMBTRAN} sort comparator
     * ({@link TransactionCombineProcessor#BY_TRAN_ID}). Injected so the step wires the (content-preserving)
     * processor and so the reader reuses the exact DFSORT field spec without re-deriving it.
     */
    private final TransactionCombineProcessor transactionCombineProcessor;

    /**
     * Transaction-master repository. {@code findAll()} supplies the {@code BKUP(0)} half of {@code SORTIN};
     * {@code saveAll(...)} performs the {@code IDCAMS REPRO} bulk merge into the master.
     */
    private final TransactionRepository transactionRepository;

    /**
     * Strongly-typed holder of the application-owned AWS resource <em>names</em>. The SYSTRAN staging
     * bucket is read from {@code getS3().getBatchOutputBucket()} ({@code carddemo-batch-output}); the bucket
     * name is therefore resolved from configuration and never hardcoded (AAP &sect;0.7.7).
     */
    private final AwsConfig.AwsResourceProperties awsResourceProperties;

    /**
     * Spring Cloud AWS S3 abstraction used to read the staged SYSTRAN interest transactions
     * ({@code SYSTRAN(0)} GDG &rarr; S3 substitution). Auto-configured by {@code spring-cloud-aws-starter-s3}
     * from {@code spring.cloud.aws.*}; never hand-built here, so the endpoint can only ever resolve to
     * LocalStack (zero live AWS). This is the same {@link S3Template} bean Stage&nbsp;2's writer uses to
     * stage the objects, keeping the two halves of the handoff in lock-step.
     */
    private final S3Template s3Template;

    /**
     * Constructs the combine-job configuration with its collaborators. A single constructor is used, so
     * Spring injects it without an explicit {@code @Autowired}.
     *
     * @param transactionCombineProcessor the identity processor exposing {@code BY_TRAN_ID} (the DFSORT
     *                                    field spec); must not be {@code null}
     * @param transactionRepository       the transaction-master repository (BKUP source + REPRO target);
     *                                    must not be {@code null}
     * @param awsResourceProperties       the AWS resource-name holder (SYSTRAN staging bucket); must not be
     *                                    {@code null}
     * @param s3Template                  the auto-configured S3 template used to read staged SYSTRAN
     *                                    objects; must not be {@code null}
     */
    public CombineTransactionsJob(
            final TransactionCombineProcessor transactionCombineProcessor,
            final TransactionRepository transactionRepository,
            final AwsConfig.AwsResourceProperties awsResourceProperties,
            final S3Template s3Template) {
        this.transactionCombineProcessor = transactionCombineProcessor;
        this.transactionRepository = transactionRepository;
        this.awsResourceProperties = awsResourceProperties;
        this.s3Template = s3Template;
    }

    /**
     * Inline reader that reproduces the {@code COMBTRAN} DFSORT step ({@code STEP05R}): it builds the
     * {@code SORTIN} concatenation of {@code BKUP(0)} + {@code SYSTRAN(0)}, performs the global
     * {@code SORT FIELDS=(TRAN-ID,A)} ordering, and streams the sorted result.
     *
     * <p>{@code @StepScope} ensures the (potentially large) collect-then-sort happens at
     * <strong>step-execution time</strong> rather than at context startup, so the database and S3 are not
     * touched while the application context is building. The reader is rebuilt fresh for each step
     * execution.</p>
     *
     * @return a step-scoped reader over the globally-sorted {@code BKUP + SYSTRAN} union
     */
    @Bean
    @StepScope
    public IteratorItemReader<Transaction> combineTransactionsReader() {
        // DFSORT SORTIN = BKUP(0) concatenated with SYSTRAN(0).
        // BKUP(0): the prior transaction master is the current PostgreSQL transaction table, read in full
        // via findAll() (the saveAll writer below re-merges these rows in place -- a REPRO no-op for them).
        final List<Transaction> combined = new ArrayList<>(transactionRepository.findAll());
        // SYSTRAN(0): the Stage-2 interest transactions staged to S3, deserialized from the same
        // fixed-width 350-byte CVTRA05Y representation InterestCalculationJob wrote.
        combined.addAll(readStagedSystranTransactions());

        // DFSORT SORT FIELDS=(TRAN-ID,A): a GLOBAL ascending sort on the 16-char TRAN-ID. A streaming chunk
        // reader cannot sort globally, so we collect-then-sort the whole union here -- the faithful DFSORT
        // equivalent for these bounded volumes. The ordering is the sibling-exposed
        // TransactionCombineProcessor.BY_TRAN_ID (the single source of truth for the SORT FIELDS spec); this
        // job deliberately defines no comparator of its own.
        combined.sort(TransactionCombineProcessor.BY_TRAN_ID);

        return new IteratorItemReader<>(combined);
    }

    /**
     * Inline bulk writer that reproduces the {@code COMBTRAN} IDCAMS step ({@code STEP10}):
     * {@code REPRO INFILE(COMBINED) OUTFILE(TRANSACT.VSAM.KSDS)}.
     *
     * <p>The writer delegates the whole chunk to {@code TransactionRepository.saveAll}. Because
     * {@code tranId} is the assigned {@code @Id}, {@code saveAll} merges by primary key &mdash; existing
     * master rows update in place and new interest rows insert &mdash; so the load is idempotent with no
     * duplicate keys, matching {@code REPRO}'s full-reload semantics. {@code saveAll} is the
     * <strong>sole</strong> write path; no per-row business logic is performed ({@code COMBTRAN} has no
     * COBOL program and applies no transformation).</p>
     *
     * @return an {@link ItemWriter} that bulk-merges each chunk into the transaction master
     */
    @Bean
    public ItemWriter<Transaction> combineTransactionsWriter() {
        // IDCAMS REPRO bulk load -> JpaRepository.saveAll merge-by-PK. The lambda is the entire write path;
        // chunk.getItems() is the sorted chunk, saved as-is (no transformation -- COMBTRAN is content-
        // preserving).
        return chunk -> transactionRepository.saveAll(chunk.getItems());
    }

    /**
     * Assembles the single chunk-oriented step that collapses {@code COMBTRAN.jcl}'s two steps
     * ({@code STEP05R} DFSORT + {@code STEP10} IDCAMS {@code REPRO}) into one Spring Batch step: the
     * globally-sorted {@code BKUP + SYSTRAN} reader, the identity {@link TransactionCombineProcessor}, and
     * the {@code saveAll} bulk-merge writer.
     *
     * <p>The chunk generics are {@code <Transaction, Transaction>} because the processor is an
     * identity pass-through (input and output types are identical). Spring&nbsp;Batch&nbsp;5.x builders are
     * used with explicit {@link JobRepository} and {@link PlatformTransactionManager} (no
     * {@code StepBuilderFactory}). The {@code @StepScope} {@link #combineTransactionsReader()} is referenced
     * through the {@code @Configuration} proxy, so the step receives the scoped reader proxy.</p>
     *
     * @param jobRepository      the auto-configured Spring Batch job repository
     * @param transactionManager the auto-configured transaction manager bounding each chunk transaction
     * @return the configured combine step
     */
    @Bean
    public Step combineTransactionsStep(final JobRepository jobRepository,
            final PlatformTransactionManager transactionManager) {
        return new StepBuilder("combineTransactionsStep", jobRepository)
                .<Transaction, Transaction>chunk(CHUNK_SIZE, transactionManager)
                .reader(combineTransactionsReader())
                .processor(transactionCombineProcessor)
                .writer(combineTransactionsWriter())
                .build();
    }

    /**
     * Assembles the Stage&nbsp;3 job from its single step, mirroring {@code COMBTRAN.jcl}. The
     * Spring&nbsp;Batch&nbsp;5.x {@link JobBuilder} is used with an explicit {@link JobRepository}.
     *
     * <p>The Stage-3 placement in the 5-stage pipeline
     * ({@code POSTTRAN &rarr; INTCALC &rarr; COMBTRAN &rarr; CREASTMT/TRANREPT}) is the responsibility of
     * the {@code BatchPipelineOrchestrator}; this job simply exposes the combine step under the natural
     * bean name {@code combineTransactionsJob} that the orchestrator resolves.</p>
     *
     * @param jobRepository          the auto-configured Spring Batch job repository
     * @param combineTransactionsStep the single step assembled by
     *                                {@link #combineTransactionsStep(JobRepository, PlatformTransactionManager)}
     * @return the configured combine job
     */
    @Bean
    public Job combineTransactionsJob(final JobRepository jobRepository, final Step combineTransactionsStep) {
        return new JobBuilder("combineTransactionsJob", jobRepository)
                .start(combineTransactionsStep)
                .build();
    }

    /**
     * Reads the {@code SYSTRAN(0)} half of the {@code SORTIN} concatenation &mdash; the Stage-2 interest
     * transactions staged to the S3 {@code carddemo-batch-output} bucket under the {@code systran/} prefix.
     *
     * <p><strong>Integration latitude (agent prompt).</strong> If the SYSTRAN staging bucket is unavailable
     * in a given environment (for example a profile without LocalStack), the reader degrades gracefully:
     * it treats the Stage-2 interest transactions as empty and combines the master ({@code BKUP}) with zero
     * {@code SYSTRAN} rows, logging the condition. The comparator-based full sort is always kept regardless.
     * This keeps the two halves of the SYSTRAN handoff in agreement with Stage&nbsp;2's
     * {@code InterestCalculationJob} writer (same bucket, same {@code systran/} prefix, same fixed-width
     * record).</p>
     *
     * @return the deserialized staged interest transactions (possibly empty, never {@code null})
     */
    private List<Transaction> readStagedSystranTransactions() {
        final String bucket = awsResourceProperties.getS3().getBatchOutputBucket();
        final List<Transaction> staged = new ArrayList<>();

        // Integration latitude: tolerate an absent staging bucket so the combine still runs (BKUP-only
        // reload). bucketExists is a cheap head check; when false, SYSTRAN is treated as empty.
        if (!s3Template.bucketExists(bucket)) {
            log.warn("SYSTRAN staging bucket '{}' is not present; combining the transaction master (BKUP) "
                    + "with zero Stage-2 interest transactions (SYSTRAN).", bucket);
            return staged;
        }

        final List<S3Resource> objects = s3Template.listObjects(bucket, S3_SYSTRAN_KEY_PREFIX);
        for (final S3Resource object : objects) {
            staged.add(readSystranObject(object));
        }
        log.info("Read {} staged SYSTRAN interest transaction(s) from s3://{}/{}",
                staged.size(), bucket, S3_SYSTRAN_KEY_PREFIX);
        return staged;
    }

    /**
     * Reads a single staged SYSTRAN object and deserializes it into a {@link Transaction}.
     *
     * <p>A staged object that exists but cannot be read is a hard data-integrity failure &mdash; the
     * faithful equivalent of a DFSORT {@code SORTIN} read abend &mdash; so an {@link IllegalStateException}
     * is raised (failing the step) rather than silently dropping the record.</p>
     *
     * @param object the S3 resource for one staged SYSTRAN record
     * @return the deserialized transaction
     */
    private static Transaction readSystranObject(final S3Resource object) {
        try (InputStream in = object.getInputStream()) {
            final String record = new String(in.readAllBytes(), StandardCharsets.UTF_8);
            return deserializeSystranRecord(record);
        } catch (final IOException ex) {
            throw new IllegalStateException(
                    "Failed to read staged SYSTRAN object '" + object.getFilename()
                            + "' for the COMBTRAN combine", ex);
        }
    }

    /**
     * Deserializes a fixed-width 350-byte {@code SYSTRAN} record into a {@link Transaction}. This is the
     * precise inverse of Stage&nbsp;2's {@code InterestCalculationJob} serializer, preserving the
     * {@code CVTRA05Y} ({@code 01 TRAN-RECORD}, RECLN&nbsp;350) field order, offsets and lengths
     * (external-interface contract, AAP &sect;0.7.2).
     *
     * <p>Alphanumeric ({@code PIC X}) fields were left-justified and space-padded by the writer, so the
     * trailing space padding is stripped to recover the logical value. Numeric ({@code PIC 9}) fields were
     * right-justified and zero-padded, so they are parsed directly. {@code TRAN-AMT PIC S9(09)V99} was
     * written as 11 implied-decimal digit positions (value&nbsp;&times;&nbsp;100, sign dropped for the
     * non-negative interest amounts), so it is reconstructed as a {@link BigDecimal} with
     * {@link #AMOUNT_SCALE scale&nbsp;2} &mdash; no {@code float}/{@code double} (AAP &sect;0.7.3). The two
     * timestamps were rendered with {@link #DB2_TIMESTAMP_FULL}, so they are parsed with the same pattern.
     * The trailing {@code FILLER PIC X(20)} is reserved padding and is not mapped (matching the
     * {@link Transaction} entity).</p>
     *
     * @param raw the staged object content (expected {@link #SYSTRAN_RECORD_LENGTH} characters)
     * @return the reconstructed transaction
     */
    // CVTRA05Y 01 TRAN-RECORD (RECLN 350) fixed-width layout -- exact inverse of Stage 2's serializer.
    private static Transaction deserializeSystranRecord(final String raw) {
        // Defensive width guard: Stage 2 always emits exactly SYSTRAN_RECORD_LENGTH chars, but pad a short
        // record so the fixed substring offsets below are always valid.
        final String r = raw.length() >= SYSTRAN_RECORD_LENGTH
                ? raw
                : raw + " ".repeat(SYSTRAN_RECORD_LENGTH - raw.length());

        final Transaction tx = new Transaction();
        tx.setTranId(alphaField(r, 0, 16));                              // TRAN-ID            X(16)
        tx.setTranTypeCd(alphaField(r, 16, 18));                         // TRAN-TYPE-CD       X(02)
        tx.setTranCatCd(parseInteger(numericField(r, 18, 22)));          // TRAN-CAT-CD        9(04)
        tx.setTranSource(alphaField(r, 22, 32));                         // TRAN-SOURCE        X(10)
        tx.setTranDesc(alphaField(r, 32, 132));                          // TRAN-DESC          X(100)
        tx.setTranAmt(parseAmount(numericField(r, 132, 143)));           // TRAN-AMT           S9(09)V99
        tx.setTranMerchantId(parseLong(numericField(r, 143, 152)));      // TRAN-MERCHANT-ID   9(09)
        tx.setTranMerchantName(alphaField(r, 152, 202));                 // TRAN-MERCHANT-NAME X(50)
        tx.setTranMerchantCity(alphaField(r, 202, 252));                 // TRAN-MERCHANT-CITY X(50)
        tx.setTranMerchantZip(alphaField(r, 252, 262));                  // TRAN-MERCHANT-ZIP  X(10)
        tx.setTranCardNum(alphaField(r, 262, 278));                      // TRAN-CARD-NUM      X(16)
        tx.setTranOrigTs(parseTimestamp(alphaField(r, 278, 304)));       // TRAN-ORIG-TS       X(26)
        tx.setTranProcTs(parseTimestamp(alphaField(r, 304, 330)));       // TRAN-PROC-TS       X(26)
        // FILLER X(20) [330,350): reserved padding, intentionally not mapped (matches the entity).
        return tx;
    }

    /**
     * Extracts an alphanumeric ({@code PIC X}) field and recovers its logical value by stripping the
     * trailing space padding the writer added (left-justified fields). Leading and internal spaces are
     * preserved.
     *
     * @param record the full fixed-width record
     * @param start  inclusive start offset
     * @param end    exclusive end offset
     * @return the field value with trailing padding removed
     */
    private static String alphaField(final String record, final int start, final int end) {
        return record.substring(start, end).stripTrailing();
    }

    /**
     * Extracts a numeric ({@code PIC 9}) field as its digit string, trimming any incidental whitespace. The
     * value is carried by the digits themselves (leading zeros are insignificant).
     *
     * @param record the full fixed-width record
     * @param start  inclusive start offset
     * @param end    exclusive end offset
     * @return the trimmed digit string
     */
    private static String numericField(final String record, final int start, final int end) {
        return record.substring(start, end).trim();
    }

    /**
     * Parses a zero-padded {@code PIC 9} digit string into an {@link Integer}.
     *
     * @param digits the digit string ({@link String#isEmpty() empty} treated as no value)
     * @return the parsed integer, or {@code null} when {@code digits} is empty
     */
    private static Integer parseInteger(final String digits) {
        return digits.isEmpty() ? null : Integer.valueOf(digits);
    }

    /**
     * Parses a zero-padded {@code PIC 9} digit string into a {@link Long}.
     *
     * @param digits the digit string ({@link String#isEmpty() empty} treated as no value)
     * @return the parsed long, or {@code null} when {@code digits} is empty
     */
    private static Long parseLong(final String digits) {
        return digits.isEmpty() ? null : Long.valueOf(digits);
    }

    /**
     * Reconstructs a {@code TRAN-AMT PIC S9(09)V99} value from its 11 implied-decimal digit positions. The
     * writer rendered {@code value}&nbsp;&times;&nbsp;100 (absolute, no decimal point), so the digits are
     * the unscaled value and the result carries {@link #AMOUNT_SCALE scale&nbsp;2}. No {@code float}/
     * {@code double} is used (AAP &sect;0.7.3); the sign is non-negative (interest amounts), matching the
     * writer which dropped the overpunch sign.
     *
     * @param digits the unscaled digit string (e.g. {@code "00000001234"} for {@code 12.34})
     * @return the scale-2 amount, or {@code null} when {@code digits} is empty
     */
    private static BigDecimal parseAmount(final String digits) {
        if (digits.isEmpty()) {
            return null;
        }
        return new BigDecimal(new BigInteger(digits), AMOUNT_SCALE);
    }

    /**
     * Parses a 26-character DB2 timestamp rendering ({@code yyyy-MM-dd-HH.mm.ss.SSSSSS}) back into a
     * {@link LocalDateTime}. An empty value (the writer's representation of a {@code null} timestamp,
     * space-padded then stripped) maps back to {@code null}.
     *
     * @param value the trimmed timestamp text
     * @return the parsed timestamp, or {@code null} when {@code value} is empty
     */
    private static LocalDateTime parseTimestamp(final String value) {
        return value.isEmpty() ? null : LocalDateTime.parse(value, DB2_TIMESTAMP_FULL);
    }
}
