/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.awsm2.carddemo.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Single menu-option DTO &mdash; one row in the {@code MainMenuDto} or
 * {@code AdminMenuDto} option lists.
 *
 * <p>Mirrors the COBOL working-storage tables that drive the 3270 menu screens:
 * <ul>
 *   <li>{@code app/cpy/COMEN02Y.cpy} &mdash; main-menu option table
 *       (regular-user menu, 10 options)</li>
 *   <li>{@code app/cpy/COADM02Y.cpy} &mdash; admin-menu option table
 *       (admin-user menu, 4 options)</li>
 * </ul>
 *
 * <p>Each COBOL option entry contains an option number, a display label,
 * a target program identifier (for CICS XCTL routing), and a user-type
 * gate ('A' admin, 'U' regular, ' ' any).  In the REST world the
 * target-program string is replaced by a client-side route or by a
 * controller URL &mdash; but the field is preserved verbatim for traceability
 * and demo-parity with the original screens (AAP &sect;0.7.3).
 *
 * <p><b>COBOL field mapping (PIC clauses):</b>
 * <pre>{@code
 *   COMEN02Y.cpy / COADM02Y.cpy field      Java component
 *   -----------------------------------    --------------------
 *   CDEMO-MENU-OPT-NUM     PIC 9(02)   ->  optionNumber (int)
 *   CDEMO-MENU-OPT-NAME    PIC X(35)   ->  label (String, <= 40)
 *   CDEMO-MENU-OPT-PGMNAME PIC X(08)   ->  targetProgram (String, <= 8)
 *   CDEMO-MENU-OPT-USRTYPE PIC X(01)   ->  userType (String, 'A'/'U'/' ')
 *   (none -- runtime gate)                  enabled (boolean)
 *   (none -- new REST route)                targetEndpoint (String)
 * }</pre>
 *
 * <p>The original COBOL drove option dispatch via {@code EVALUATE} on the
 * selected option number and {@code EXEC CICS XCTL PROGRAM(target-program)}.
 * The REST replacement uses {@link #targetEndpoint()} (clients navigate
 * directly via HTTP).  The {@link #targetProgram()} field is preserved
 * purely for audit-readiness and parallel-run validation against the
 * original mainframe behavior.
 *
 * <p>This record is immutable and response-only; it carries no PII, no
 * monetary fields, and no sensitive material, so the default {@code toString()}
 * generated by the record contract is safe to log.
 *
 * <p><b>COBOL Provenance:</b>
 * <ul>
 *   <li>Source: {@code app/cpy/COMEN02Y.cpy} (main menu)</li>
 *   <li>Source: {@code app/cpy/COADM02Y.cpy} (admin menu)</li>
 *   <li>Consumed by: {@code MenuService#buildMainMenu(String)} and
 *       {@code MenuService#buildAdminMenu()}</li>
 *   <li>Aggregated by: {@code MainMenuDto} and {@code AdminMenuDto}</li>
 * </ul>
 *
 * @param optionNumber   the display option number (1-99); maps to
 *                       {@code CDEMO-MENU-OPT-NUM PIC 9(02)}
 * @param label          the human-readable label of the menu option;
 *                       maps to {@code CDEMO-MENU-OPT-NAME PIC X(35)}
 * @param targetProgram  the original COBOL target-program identifier
 *                       (e.g., {@code COACTVWC}); maps to
 *                       {@code CDEMO-MENU-OPT-PGMNAME PIC X(08)}.
 *                       Preserved verbatim for traceability
 * @param targetEndpoint the REST endpoint URL or client-side route
 *                       corresponding to the option (e.g.,
 *                       {@code /api/accounts/{id}}); replaces the
 *                       legacy CICS XCTL routing
 * @param userType       the user-type gate: {@code "A"} admin-only,
 *                       {@code "U"} regular-only, {@code " "} (or
 *                       {@code null}) for both; maps to
 *                       {@code CDEMO-MENU-OPT-USRTYPE PIC X(01)}
 * @param enabled        whether this option is enabled in the current
 *                       session (e.g., disabled until a card is selected)
 *
 * @see <a href=
 *      "https://github.com/aws-samples/aws-mainframe-modernization-carddemo">
 *      AWS CardDemo (source COBOL)</a>
 */
@Schema(name = "MenuOptionDto",
        description = "Single menu-option row presented to the client. Mirrors a "
                + "single entry in the COBOL CDEMO-MENU-OPT (COMEN02Y.cpy) or "
                + "CDEMO-ADMIN-OPT (COADM02Y.cpy) working-storage table.")
public record MenuOptionDto(

        @Schema(description = "Display option number (1-99) shown in the option-number "
                + "column on the legacy BMS screen and used as the dispatch key.",
                example = "1")
        @JsonProperty("optionNumber")
        int optionNumber,

        @Schema(description = "Human-readable label of the menu option (e.g., "
                + "\"Account View\", \"Credit Card Update\", \"User Add (Security)\"). "
                + "Sourced from the COBOL CDEMO-MENU-OPT-NAME / "
                + "CDEMO-ADMIN-OPT-NAME PIC X(35) literals.",
                example = "Account View",
                maxLength = 40)
        @JsonProperty("label")
        String label,

        @Schema(description = "Original COBOL target-program identifier "
                + "(e.g., COACTVWC, COCRDLIC, COUSR00C). Preserved verbatim for "
                + "traceability and parallel-run validation; in the Java target, "
                + "clients should rely on targetEndpoint for navigation.",
                example = "COACTVWC",
                maxLength = 8)
        @JsonProperty("targetProgram")
        String targetProgram,

        @Schema(description = "REST endpoint URL or client-side route corresponding "
                + "to the option (e.g., /api/accounts/{id}). Replaces the legacy "
                + "CICS XCTL routing performed by the original COBOL menu handler.",
                example = "/api/accounts/{id}")
        @JsonProperty("targetEndpoint")
        String targetEndpoint,

        @Schema(description = "User-type gate: 'A' admin-only, 'U' regular-only, "
                + "' ' (or null) for both. The server already filters options by "
                + "the authenticated user role before returning the menu, so the "
                + "client may use this purely for display badging. Sourced from "
                + "COBOL CDEMO-MENU-OPT-USRTYPE PIC X(01).",
                example = "U",
                allowableValues = {"A", "U", " "})
        @JsonProperty("userType")
        String userType,

        @Schema(description = "Whether this option is enabled in the current "
                + "session. Used for options that depend on dynamic context "
                + "(e.g., the user has selected a card before being allowed to "
                + "view its detail).",
                example = "true")
        @JsonProperty("enabled")
        boolean enabled
) {
}
