/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.awsm2.carddemo.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

/**
 * Paged user list response DTO (admin-only).
 *
 * <p>Replaces the 3270 user-list screen rendered by the COBOL/CICS program
 * {@code COUSR00C.cbl} (CICS transaction id {@code CU00}).  In the source,
 * {@code COUSR00C} uses {@code EXEC CICS STARTBR}/{@code READNEXT} on the
 * {@code USRSEC} VSAM KSDS to browse 10 user records at a time
 * (the COBOL working storage declares
 * {@code 02 USER-REC OCCURS 10 TIMES}), with paging driven by the {@code PF7}
 * (page backward) and {@code PF8} (page forward) keys.
 *
 * <p>In the Java target, this is replaced by Spring Data
 * {@code Pageable} on
 * {@code UserSecurityRepository.findAll(Pageable)} with {@code size=10} to
 * match the BMS 10-row table; the {@link #searchFilter()} optionally narrows
 * the result set by user ID / first name / last name substring via a
 * {@code JpaSpecificationExecutor} or {@code @Query} in the repository.
 *
 * <p>Controller endpoint:
 * {@code GET /api/admin/users?search={q}&page={n}&size={s}} &mdash; secured
 * via Spring Security {@code @PreAuthorize("hasRole('ADMIN')")} on
 * {@code UserAdminController.listUsers(...)} per AAP &sect;0.3.4.
 *
 * <p><b>BMS field origin &mdash; per-row mapping (COUSR0A map, 10 occurrences):</b>
 * <pre>{@code
 *   BMS field        Length   CSUSR01Y field      UserRow component
 *   --------------   ------   ----------------    -----------------
 *   USRIDnnI         X(08)    SEC-USR-ID          userId
 *   FNAMEnnI         X(20)    SEC-USR-FNAME       firstName
 *   LNAMEnnI         X(20)    SEC-USR-LNAME       lastName
 *   UTYPEnnI         X(01)    SEC-USR-TYPE        userType
 * }</pre>
 *
 * <p><b>COBOL Provenance (AAP &sect;0.7.3 traceability):</b>
 * <ul>
 *   <li>BMS Mapset: {@code app/bms/COUSR00.bms} (mapset {@code COUSR00},
 *       map {@code COUSR0A}, 10-row user table)</li>
 *   <li>Symbolic Map: {@code app/cpy-bms/COUSR00.CPY}</li>
 *   <li>Program: {@code app/cbl/COUSR00C.cbl} (CICS transaction
 *       {@code CU00})</li>
 *   <li>Record Layout: {@code app/cpy/CSUSR01Y.cpy}
 *       ({@code SEC-USER-DATA}, 80 bytes)</li>
 *   <li>VSAM Cluster: {@code AWS.M2.CARDDEMO.USRSEC.VSAM.KSDS}
 *       (RECLN=80, KEYLEN=8)</li>
 * </ul>
 *
 * <p><b>Security &amp; PCI-DSS handling (AAP &sect;0.7.1, &sect;0.6.6):</b>
 * <ul>
 *   <li>{@code SEC-USR-PWD} ({@code PIC X(08)}) is <b>intentionally
 *       excluded</b> from {@link UserRow}. Passwords are stored as BCrypt
 *       hashes in the {@code UserSecurity} JPA entity (security upgrade vs.
 *       the original plaintext {@code USRSEC} file) and must never appear in
 *       any response body, log line, or audit event.</li>
 *   <li>{@code SEC-USR-FILLER} ({@code PIC X(23)}) is not mapped &mdash; it
 *       is unused padding in the original record layout.</li>
 *   <li>This endpoint is admin-only; access control is enforced at the
 *       controller layer via {@code @PreAuthorize("hasRole('ADMIN')")}.</li>
 *   <li>The default {@code toString()} generated by the {@code record}
 *       contract is safe to log because no PCI/PII/credential field appears
 *       on this DTO.</li>
 * </ul>
 *
 * <p>This record is immutable and response-only; it carries no monetary
 * fields and no sensitive credential material.
 *
 * @param rows           the list of user rows on the current page; up to 10
 *                       entries to match the 10-row BMS table in
 *                       {@code COUSR00.bms}
 * @param page           the current page number (0-indexed, as produced by
 *                       Spring Data {@code Page#getNumber()})
 * @param size           the page size; fixed at 10 to match the legacy BMS
 *                       table capacity
 * @param totalElements  the total number of matching users across all pages
 * @param totalPages     the total number of pages available given
 *                       {@code totalElements} and {@code size}
 * @param first          {@code true} if this is the first page
 *                       (corresponds to the COBOL "top of the page"
 *                       check on the {@code PF7} handler)
 * @param last           {@code true} if this is the last page
 *                       (corresponds to the COBOL "bottom of the page"
 *                       check on the {@code PF8} handler)
 * @param searchFilter   the optional search filter (echoed from the request,
 *                       matching legacy BMS field {@code USRIDIN} which the
 *                       COBOL program copied to {@code SEC-USR-ID} before
 *                       calling {@code STARTBR}); may be {@code null} or
 *                       empty when listing all users
 *
 * @see UserListDto.UserRow
 */
@Schema(name = "UserListDto",
        description = "Paged user list response (admin-only). Replaces the 3270 "
                + "user-list screen rendered by COBOL program COUSR00C / BMS "
                + "mapset COUSR00. Page size is fixed at 10 to match the 10-row "
                + "BMS table.")
public record UserListDto(

        @Schema(description = "User rows on this page. Up to 10 entries to match "
                + "the legacy BMS 10-row table (COUSR00.bms map COUSR0A).")
        @JsonProperty("rows")
        List<UserRow> rows,

        @Schema(description = "Current page number (0-indexed), as produced by "
                + "Spring Data Page#getNumber(). The legacy COBOL program "
                + "(COUSR00C.cbl) maintained CDEMO-CU00-PAGE-NUM (1-indexed); the "
                + "Java target normalizes to 0-indexed paging per Spring Data "
                + "convention.",
                example = "0")
        @JsonProperty("page")
        int page,

        @Schema(description = "Page size. Fixed at 10 to match the 10-row BMS "
                + "table in COUSR00.bms. Any request with a different size is "
                + "coerced to 10 by the controller for fidelity with the legacy "
                + "screen.",
                example = "10")
        @JsonProperty("size")
        int size,

        @Schema(description = "Total number of matching users across all pages, "
                + "as produced by Spring Data Page#getTotalElements(). Reflects "
                + "the search filter when provided.",
                example = "25")
        @JsonProperty("totalElements")
        long totalElements,

        @Schema(description = "Total number of pages available given "
                + "totalElements and size, as produced by Spring Data "
                + "Page#getTotalPages().",
                example = "3")
        @JsonProperty("totalPages")
        int totalPages,

        @Schema(description = "First-page indicator. True when this is page 0. "
                + "Corresponds to the COBOL guard in COUSR00C.cbl PROCESS-PF7-KEY "
                + "that emits \"You are already at the top of the page...\".",
                example = "true")
        @JsonProperty("first")
        boolean first,

        @Schema(description = "Last-page indicator. True when this is the final "
                + "page. Corresponds to the COBOL guard in COUSR00C.cbl "
                + "PROCESS-PF8-KEY that emits \"You are already at the bottom "
                + "of the page...\" and to the CDEMO-CU00-NEXT-PAGE-FLG flag.",
                example = "false")
        @JsonProperty("last")
        boolean last,

        @Schema(description = "Search filter echoed from the request. The legacy "
                + "COBOL field USRIDIN (PIC X(08)) was copied to SEC-USR-ID before "
                + "the STARTBR positioning read; the Java target widens this to a "
                + "substring match against user ID, first name, or last name (via "
                + "repository specification or @Query). Null or empty means list "
                + "all users.",
                example = "ADMIN",
                nullable = true)
        @JsonProperty("searchFilter")
        String searchFilter
) {

    /**
     * One row of the user list &mdash; display-only fields drawn from
     * {@code SEC-USER-DATA} in {@code app/cpy/CSUSR01Y.cpy}.
     *
     * <p>Passwords ({@code SEC-USR-PWD}) and the padding filler
     * ({@code SEC-USR-FILLER}) are <b>intentionally excluded</b>:
     * <ul>
     *   <li>{@code SEC-USR-PWD}: never surfaced on a response per the
     *       PCI-DSS-aligned security stance in AAP &sect;0.7.1 (passwords
     *       are stored as BCrypt hashes in the {@code UserSecurity} JPA
     *       entity and never leave the persistence layer in plaintext or
     *       hashed form).</li>
     *   <li>{@code SEC-USR-FILLER}: 23-byte padding with no business
     *       meaning, retained only in the on-disk layout.</li>
     * </ul>
     *
     * <p>The COBOL {@code COUSR00C.cbl} program populates each row of the
     * 10-row BMS table {@code USER-REC OCCURS 10 TIMES} from the
     * {@code SEC-USER-DATA} record returned by the {@code STARTBR}/
     * {@code READNEXT} browse against {@code USRSEC}; this record carries
     * the same four display fields.
     *
     * @param userId    the user ID; maps to {@code SEC-USR-ID PIC X(08)}
     *                  (also rendered as BMS field {@code USRIDnnI} for the
     *                  nth row, nn = 01..10)
     * @param firstName the user's first name; maps to
     *                  {@code SEC-USR-FNAME PIC X(20)} (BMS field
     *                  {@code FNAMEnnI})
     * @param lastName  the user's last name; maps to
     *                  {@code SEC-USR-LNAME PIC X(20)} (BMS field
     *                  {@code LNAMEnnI})
     * @param userType  the user-type code; maps to
     *                  {@code SEC-USR-TYPE PIC X(01)} (BMS field
     *                  {@code UTYPEnnI}) &mdash; {@code "A"} admin,
     *                  {@code "U"} regular
     */
    @Schema(name = "UserListDto.UserRow",
            description = "Single user row in the paged list. Mirrors one "
                    + "occurrence of the 10-row BMS table COUSR0A and one "
                    + "SEC-USER-DATA record in CSUSR01Y.cpy. Passwords are "
                    + "intentionally excluded.")
    public record UserRow(

            @Schema(description = "User ID. Maps to COBOL SEC-USR-ID "
                    + "PIC X(08) in CSUSR01Y.cpy. The primary key of the "
                    + "USRSEC VSAM KSDS and the JPA primary key of "
                    + "UserSecurity.",
                    example = "ADMIN001",
                    maxLength = 8)
            @JsonProperty("userId")
            String userId,

            @Schema(description = "User's first name. Maps to COBOL "
                    + "SEC-USR-FNAME PIC X(20) in CSUSR01Y.cpy.",
                    example = "Administrator",
                    maxLength = 20)
            @JsonProperty("firstName")
            String firstName,

            @Schema(description = "User's last name. Maps to COBOL "
                    + "SEC-USR-LNAME PIC X(20) in CSUSR01Y.cpy.",
                    example = "User",
                    maxLength = 20)
            @JsonProperty("lastName")
            String lastName,

            @Schema(description = "User type code. Maps to COBOL "
                    + "SEC-USR-TYPE PIC X(01) in CSUSR01Y.cpy. \"A\" denotes an "
                    + "administrator (access to COADM01 admin menu and all "
                    + "user-admin transactions CU00/CU01/CU02/CU03); \"U\" "
                    + "denotes a regular user (access to COMEN01 main menu "
                    + "only).",
                    example = "A",
                    allowableValues = {"A", "U"},
                    maxLength = 1)
            @JsonProperty("userType")
            String userType
    ) {
    }
}
