/*
 * SignOnResponse.java — Authentication Response DTO for CardDemo Application
 *
 * Migrated from COBOL source artifacts:
 *   - app/cpy/COCOM01Y.cpy (CARDDEMO-COMMAREA, lines 19-44)
 *   - app/cpy-bms/COSGN00.CPY (BMS symbolic map for sign-on screen)
 *   - app/cbl/COSGN00C.cbl (Sign-on program authentication flow)
 *
 * This DTO captures the authentication response payload returned after a
 * successful sign-on. In the original COBOL application, COSGN00C.cbl
 * authenticates the user against the USRSEC VSAM dataset and populates the
 * CARDDEMO-COMMAREA with the authenticated user's identity and routing
 * information before issuing CICS RETURN TRANSID('CM01') COMMAREA.
 *
 * In the Java target, the CICS pseudo-conversational model (RETURN TRANSID
 * with COMMAREA state) is replaced by a stateless REST response containing
 * a JWT or session token. This DTO is the JSON response body from
 * AuthController.POST /api/auth/signin.
 *
 * COBOL COMMAREA field mapping (from COCOM01Y.cpy):
 *   CDEMO-USER-ID      PIC X(08)  → userId (String, max 8 chars)
 *   CDEMO-USER-TYPE    PIC X(01)  → userType (UserType enum)
 *     88 CDEMO-USRTYP-ADMIN VALUE 'A' → UserType.ADMIN
 *     88 CDEMO-USRTYP-USER  VALUE 'U' → UserType.USER
 *   CDEMO-TO-TRANID    PIC X(04)  → toTranId (String, e.g., "CM01")
 *   CDEMO-TO-PROGRAM   PIC X(08)  → toProgram (String, e.g., "COMEN01C")
 *   (no COBOL equivalent)         → token (JWT/session token, replaces COMMAREA state)
 *
 * Security note: The token field is intentionally excluded from toString()
 * to prevent accidental credential leakage in logs and diagnostic output.
 *
 * @see com.cardemo.model.enums.UserType
 */
package com.cardemo.model.dto;

import com.cardemo.model.enums.UserType;

/**
 * Authentication response DTO returned upon successful user sign-on.
 *
 * <p>Encapsulates the authenticated user's identity, role, security token,
 * and CICS-equivalent routing information. This replaces the COBOL
 * CARDDEMO-COMMAREA population performed by COSGN00C.cbl after
 * successful password verification.</p>
 *
 * <p><strong>Authentication flow mapping:</strong></p>
 * <ol>
 *   <li>COSGN00C reads USRSEC by user ID → {@code AuthenticationService.authenticate()}</li>
 *   <li>Verifies password (plaintext in COBOL → BCrypt in Java)</li>
 *   <li>Populates COMMAREA fields → builds {@code SignOnResponse}</li>
 *   <li>CICS RETURN TRANSID COMMAREA → returns JSON with token</li>
 * </ol>
 *
 * <p>Consumed by: {@code AuthController.POST /api/auth/signin} as the
 * response payload.</p>
 */
public class SignOnResponse {

    /**
     * JWT or session token generated by the authentication service.
     *
     * <p>No direct COBOL equivalent — the original application used CICS
     * pseudo-conversational RETURN TRANSID with COMMAREA for session
     * continuity. In the Java target, a JWT token replaces the
     * COMMAREA-based state passing mechanism.</p>
     *
     * <p><strong>Security:</strong> This field is intentionally excluded
     * from {@link #toString()} to prevent accidental credential leakage
     * in log output.</p>
     */
    private String token;

    /**
     * Authenticated user's role type.
     *
     * <p>Maps from COBOL: {@code CDEMO-USER-TYPE PIC X(01)} in COCOM01Y.cpy
     * (line 26), with 88-level conditions:</p>
     * <ul>
     *   <li>{@code CDEMO-USRTYP-ADMIN VALUE 'A'} → {@link UserType#ADMIN}</li>
     *   <li>{@code CDEMO-USRTYP-USER VALUE 'U'} → {@link UserType#USER}</li>
     * </ul>
     *
     * <p>Determines post-login routing: {@link UserType#ADMIN} routes to the
     * admin menu (COADM01C), while {@link UserType#USER} routes to the
     * regular user main menu (COMEN01C).</p>
     */
    private UserType userType;

    /**
     * Authenticated user's identifier.
     *
     * <p>Maps from COBOL: {@code CDEMO-USER-ID PIC X(08)} in COCOM01Y.cpy
     * (line 25). Maximum 8 characters, matching the {@code SEC-USR-ID}
     * field in the USRSEC VSAM dataset (CSUSR01Y.cpy).</p>
     */
    private String userId;

    /**
     * Target transaction identifier for post-login navigation.
     *
     * <p>Maps from COBOL: {@code CDEMO-TO-TRANID PIC X(04)} in COCOM01Y.cpy
     * (line 23). After successful sign-on, COSGN00C sets this to the
     * destination CICS transaction ID (e.g., {@code "CM01"} for the main
     * menu transaction or {@code "CA01"} for admin menu).</p>
     *
     * <p>In the REST API context, this provides the client with routing
     * metadata to determine which screen or module to display next.</p>
     */
    private String toTranId;

    /**
     * Target program name for post-login navigation.
     *
     * <p>Maps from COBOL: {@code CDEMO-TO-PROGRAM PIC X(08)} in COCOM01Y.cpy
     * (line 24). After successful sign-on, COSGN00C sets this to the
     * destination program name (e.g., {@code "COMEN01C"} for the regular
     * user main menu or {@code "COADM01C"} for the admin menu).</p>
     *
     * <p>In the REST API context, this provides the client with routing
     * metadata indicating the logical service endpoint to invoke next.</p>
     */
    private String toProgram;

    /**
     * Default no-argument constructor.
     *
     * <p>Required for JSON deserialization frameworks (Jackson) and
     * Spring MVC response body serialization.</p>
     */
    public SignOnResponse() {
        // No-args constructor for framework compatibility
    }

    /**
     * Constructs a fully populated sign-on response.
     *
     * @param token     JWT or session token; replaces CICS COMMAREA state
     * @param userType  authenticated user's role ({@link UserType#ADMIN} or
     *                  {@link UserType#USER})
     * @param userId    authenticated user identifier (max 8 chars, maps
     *                  CDEMO-USER-ID)
     * @param toTranId  target transaction ID for post-login routing (max 4
     *                  chars, maps CDEMO-TO-TRANID)
     * @param toProgram target program name for post-login routing (max 8
     *                  chars, maps CDEMO-TO-PROGRAM)
     */
    public SignOnResponse(String token, UserType userType, String userId,
                          String toTranId, String toProgram) {
        this.token = token;
        this.userType = userType;
        this.userId = userId;
        this.toTranId = toTranId;
        this.toProgram = toProgram;
    }

    /**
     * Returns the JWT or session token.
     *
     * @return the authentication token, or {@code null} if not yet set
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the JWT or session token.
     *
     * @param token the authentication token to set
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * Returns the authenticated user's role type.
     *
     * @return {@link UserType#ADMIN} or {@link UserType#USER}, or
     *         {@code null} if not yet set
     */
    public UserType getUserType() {
        return userType;
    }

    /**
     * Sets the authenticated user's role type.
     *
     * @param userType the user role ({@link UserType#ADMIN} or
     *                 {@link UserType#USER})
     */
    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    /**
     * Returns the authenticated user's identifier.
     *
     * @return the user ID (max 8 characters), or {@code null} if not yet set
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the authenticated user's identifier.
     *
     * @param userId the user ID to set (max 8 characters, matching
     *               CDEMO-USER-ID PIC X(08))
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * Returns the target transaction identifier for post-login routing.
     *
     * @return the transaction ID (max 4 characters), or {@code null} if not set
     */
    public String getToTranId() {
        return toTranId;
    }

    /**
     * Sets the target transaction identifier for post-login routing.
     *
     * @param toTranId the target transaction ID (max 4 characters, matching
     *                 CDEMO-TO-TRANID PIC X(04))
     */
    public void setToTranId(String toTranId) {
        this.toTranId = toTranId;
    }

    /**
     * Returns the target program name for post-login routing.
     *
     * @return the program name (max 8 characters), or {@code null} if not set
     */
    public String getToProgram() {
        return toProgram;
    }

    /**
     * Sets the target program name for post-login routing.
     *
     * @param toProgram the target program name (max 8 characters, matching
     *                  CDEMO-TO-PROGRAM PIC X(08))
     */
    public void setToProgram(String toProgram) {
        this.toProgram = toProgram;
    }

    /**
     * Returns a string representation of this sign-on response.
     *
     * <p><strong>Security:</strong> The {@code token} field is intentionally
     * excluded from this representation to prevent accidental credential
     * leakage in log files, debug output, and exception messages.</p>
     *
     * @return a string containing userId, userType, toTranId, and toProgram
     */
    @Override
    public String toString() {
        return "SignOnResponse{"
                + "userId='" + userId + '\''
                + ", userType=" + userType
                + ", toTranId='" + toTranId + '\''
                + ", toProgram='" + toProgram + '\''
                + '}';
    }
}
