/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.awsm2.carddemo.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * Spring {@code @Configuration} that declares the {@link OpenAPI} bean used by
 * springdoc-openapi 2.x to generate the OpenAPI 3 contract for the CardDemo
 * REST API.
 *
 * <p>The OpenAPI document is served at {@code /v3/api-docs} (JSON) and rendered
 * as Swagger UI at {@code /swagger-ui.html}; both paths are configured in
 * {@code application.yml} under {@code springdoc.api-docs.path} and
 * {@code springdoc.swagger-ui.path} respectively. Path scanning for
 * {@code @RestController} classes is constrained to
 * {@code com.awsm2.carddemo.controller} via {@code springdoc.packages-to-scan}
 * in {@code application.yml}, which keeps batch jobs, AWS adapters, and other
 * internal components out of the public API surface.</p>
 *
 * <p>Per AAP &sect;0.3.4, the OpenAPI document is the public contract for the
 * 16 REST endpoint groups that replace the original CICS 3270 transactions
 * driven by the 18 online COBOL programs ({@code app/cbl/CO*.cbl}) and
 * documented by the 17 BMS mapsets ({@code app/bms/*.bms}).</p>
 *
 * <p><b>Replaces:</b> BMS mapset documentation and CICS terminal screen
 * specifications &mdash; the OpenAPI contract is now the single source of
 * truth for the public REST API surface.</p>
 *
 * <p>The {@code SecurityScheme} declared here documents the JWT bearer-token
 * authentication scheme implemented by {@code SecurityConfig} and
 * {@code JwtAuthenticationFilter} per AAP &sect;0.3.4 (session management:
 * "JWT bearer tokens issued by {@code /api/auth/signin}"). Controllers that
 * expose public endpoints (such as {@code AuthController#signin()}) opt out
 * of the global security requirement by annotating the method with
 * {@code @SecurityRequirements({})}.</p>
 *
 * <h2>Profile behavior</h2>
 * <ul>
 *   <li><b>local</b> &mdash; Swagger UI enabled; server URL defaults to
 *       {@code http://localhost:8080} so the embedded Swagger UI can issue
 *       requests against the local Spring Boot service.</li>
 *   <li><b>dev</b> &mdash; Swagger UI enabled with the dev environment ALB
 *       DNS as the server URL (sourced from
 *       {@code carddemo.openapi.server-url} in {@code application-dev.yml}).</li>
 *   <li><b>prod</b> &mdash; per AAP &sect;0.3.4, Swagger UI is gated by Spring
 *       Profile in production. The {@code application-prod.yml} overlay sets
 *       {@code springdoc.swagger-ui.enabled: false}; ALB rules additionally
 *       block {@code /swagger-ui*} paths externally. This config class itself
 *       performs no profile-specific gating &mdash; profile overlays do.</li>
 * </ul>
 *
 * <h2>AAP cross-references</h2>
 * <ul>
 *   <li>&sect;0.3.4 &mdash; API documentation: OpenAPI 3 generated by
 *       springdoc-openapi, served at {@code /api-docs} and
 *       {@code /swagger-ui.html} (gated by Spring Profile in production).</li>
 *   <li>&sect;0.5.1 &mdash; Dependency
 *       {@code org.springdoc:springdoc-openapi-starter-webmvc-ui} 2.x on the
 *       classpath via {@code pom.xml}.</li>
 *   <li>&sect;0.7.1 &mdash; Stateless infrastructure wiring; no business
 *       logic, no AWS SDK calls, no JPA references.</li>
 * </ul>
 */
@Configuration
public class OpenApiConfig {

    /**
     * Constant security scheme name shared between the {@link Components}
     * definition and the global {@link SecurityRequirement}. Swagger UI uses
     * this identifier to wire the "Authorize" dialog to the HTTP bearer
     * scheme.
     */
    private static final String SECURITY_SCHEME_NAME = "BearerAuth";

    /**
     * Spring application name; injected from {@code spring.application.name}
     * in {@code application.yml} (default value {@code carddemo}). Available
     * for inclusion in the OpenAPI document metadata or for future extension
     * (e.g., tagging operations with the producing service).
     */
    @Value("${spring.application.name:carddemo}")
    private String applicationName;

    /**
     * Service version surfaced in the OpenAPI {@link Info} block. Sourced
     * from the {@code SERVICE_VERSION} environment variable when the service
     * is deployed to ECS Fargate (the CI/CD pipeline writes the artifact
     * version into the task definition); falls back to
     * {@code 0.1.0-SNAPSHOT} during local development.
     */
    @Value("${SERVICE_VERSION:0.1.0-SNAPSHOT}")
    private String serviceVersion;

    /**
     * Public-facing API server URL displayed by Swagger UI as the default
     * target host. Overridden per profile:
     * <ul>
     *   <li>{@code local} &mdash; {@code http://localhost:8080} (default,
     *       baked into this {@code @Value} annotation)</li>
     *   <li>{@code dev} / {@code prod} &mdash;
     *       {@code carddemo.openapi.server-url} in the profile overlay
     *       points to the ALB DNS name (HTTPS)</li>
     * </ul>
     */
    @Value("${carddemo.openapi.server-url:http://localhost:8080}")
    private String serverUrl;

    /**
     * Contact email surfaced in the OpenAPI {@link Contact} block. Provided
     * via {@code carddemo.openapi.contact-email} in profile overlays so
     * downstream API consumers can reach the owning team. Defaults to a
     * placeholder for local development; production overlays MUST set a real
     * value.
     */
    @Value("${carddemo.openapi.contact-email:noreply@example.com}")
    private String contactEmail;

    /**
     * Default no-arg constructor. This configuration class has no constructor
     * dependencies &mdash; the {@code @Value}-injected fields are populated
     * by Spring's
     * {@link org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor
     * AutowiredAnnotationBeanPostProcessor} after instantiation, before the
     * {@link #cardDemoOpenAPI()} factory method is invoked.
     */
    public OpenApiConfig() {
        // No-op: Spring populates the @Value fields after construction.
    }

    /**
     * Builds the OpenAPI 3 contract document for the CardDemo REST API.
     *
     * <p>The bean is discovered automatically by springdoc-openapi 2.x's
     * autoconfiguration ({@code SpringDocConfiguration}) and used as the
     * base document onto which scanned {@code @RestController}-level
     * operation metadata is merged.</p>
     *
     * <p>The document declares:</p>
     * <ul>
     *   <li>API title, version, description, contact, and license
     *       (Apache 2.0 &mdash; matches the repository {@code LICENSE}
     *       file at the project root per AAP &sect;0.2.2)</li>
     *   <li>Server URL (profile-dependent: {@code localhost:8080} in local,
     *       ALB DNS in dev/prod)</li>
     *   <li>{@code BearerAuth} security scheme &mdash; HTTP bearer with the
     *       {@code JWT} bearer format, declared inside
     *       {@link Components#securitySchemes} so it appears in the
     *       Swagger UI "Authorize" dialog (per AAP &sect;0.3.4 session
     *       management)</li>
     *   <li>Global {@link SecurityRequirement} applying {@code BearerAuth}
     *       to every operation by default; controllers may opt out per
     *       endpoint via {@code @SecurityRequirements({})} (used by
     *       {@code AuthController#signin()} for the public sign-on
     *       endpoint that issues the JWT)</li>
     * </ul>
     *
     * <p>The HTTP bearer scheme signals to API consumers and to Swagger UI
     * that the {@code Authorization: Bearer &lt;token&gt;} header is required
     * for authenticated endpoints, where the token is the JWT issued by
     * {@code POST /api/auth/signin} (replacement for the original CICS
     * {@code COSGN00C} signon transaction).</p>
     *
     * @return the configured {@link OpenAPI} document; never {@code null}
     */
    @Bean
    public OpenAPI cardDemoOpenAPI() {
        // Replaces: BMS mapset field-contract documentation (app/bms/*.bms)
        // and CICS terminal screen specifications. The OpenAPI document is
        // now the single source of truth for the public REST API surface
        // consumed by external clients and downstream services.

        return new OpenAPI()
            .info(new Info()
                .title("CardDemo API")
                .description("REST API for the CardDemo credit-card management system. "
                    + "This service is the Java/Spring Boot 3.x port of the AWS "
                    + "Mainframe Modernization CardDemo COBOL application. Each "
                    + "endpoint replaces a CICS 3270 terminal transaction documented "
                    + "in the original BMS mapsets (app/bms/*.bms) and the 18 online "
                    + "COBOL programs (app/cbl/CO*.cbl). All monetary values follow "
                    + "the COBOL PIC S9(n)V99 contract (java.math.BigDecimal with "
                    + "RoundingMode.HALF_EVEN). Authenticated endpoints require a JWT "
                    + "bearer token obtained from POST /api/auth/signin.")
                .version(serviceVersion)
                .contact(new Contact()
                    .name("CardDemo Team")
                    .email(contactEmail))
                .license(new License()
                    .name("Apache License 2.0")
                    .url("https://www.apache.org/licenses/LICENSE-2.0")))
            .servers(List.of(
                new Server()
                    .url(serverUrl)
                    .description("CardDemo API server (" + applicationName + ")")))
            // Global security requirement: every operation requires BearerAuth
            // unless the controller method opts out via @SecurityRequirements({}).
            .addSecurityItem(new SecurityRequirement().addList(SECURITY_SCHEME_NAME))
            .components(new Components()
                .addSecuritySchemes(SECURITY_SCHEME_NAME, new SecurityScheme()
                    .name(SECURITY_SCHEME_NAME)
                    .type(SecurityScheme.Type.HTTP)
                    .scheme("bearer")
                    .bearerFormat("JWT")
                    .in(SecurityScheme.In.HEADER)
                    .description("JWT bearer token issued by POST /api/auth/signin "
                        + "(replaces CICS COSGN00C signon transaction). Pass as "
                        + "'Authorization: Bearer <token>' header on every "
                        + "authenticated request.")));
    }
}
