###############################################################################
# infrastructure/terraform/elasticache.tf
#
# Amazon ElastiCache Redis replication group for the CardDemo cache-aside layer.
#
# Purpose:
#   Provisions the Redis cache infrastructure that backs high-frequency account
#   balance reads issued by the Spring Boot application (per AAP §0.1.1,
#   §0.3.3, §0.7.1). The cache-aside pattern delegates cache population to the
#   application — on a cache miss, the service reads from RDS PostgreSQL,
#   writes the result to Redis with a TTL aligned to transaction frequency,
#   and returns the value. The cache substantially reduces RDS read load for
#   the most-trafficked entities (Account balances, CardCrossReference
#   lookups) without ever becoming the system of record.
#
# Replaces:
#   No direct mainframe equivalent. The source z/OS CardDemo system performed
#   every account-balance lookup against a VSAM KSDS read; there was no
#   caching layer. ElastiCache Redis is a NEW architectural capability
#   introduced by this migration per AAP §0.1.1 "caching (none → Amazon
#   ElastiCache Redis)".
#
# Cache pattern (per AAP §0.3.3):
#   * Cache-Aside — read-through with TTL-based expiration; on cache miss
#     the application populates the cache from RDS.
#   * Eviction — `maxmemory-policy = allkeys-lru` (mandated by AAP §0.1.1).
#     When memory pressure hits maxmemory, Redis evicts the least-recently-
#     used keys regardless of TTL.
#   * Expiration monitoring — `notify-keyspace-events = Ex` publishes
#     expired-key events to Redis Pub/Sub for downstream observability.
#
# Resources provisioned (in dependency order resolved by Terraform):
#   1. aws_security_group.elasticache              — Redis ENI security group.
#                                                    Inbound port 6379 (TLS)
#                                                    from consumer SGs added
#                                                    separately by ecs.tf /
#                                                    batch.tf to avoid cycles.
#   2. aws_elasticache_subnet_group.carddemo       — Private subnet placement
#                                                    across multiple AZs.
#   3. aws_elasticache_parameter_group.carddemo    — redis7 family with
#                                                    allkeys-lru eviction +
#                                                    expired-key notifications.
#   4. random_password.redis_auth_token            — 64-char alphanumeric
#                                                    AUTH token (generated
#                                                    once, persisted in state).
#   5. aws_secretsmanager_secret.redis_auth        — KMS-encrypted Secrets
#                                                    Manager secret holding
#                                                    the AUTH token JSON.
#   6. aws_secretsmanager_secret_version.redis_auth_value
#                                                  — Initial AUTH token
#                                                    payload (the Spring Boot
#                                                    RedisConfig reads this
#                                                    secret at runtime per
#                                                    AAP §0.7.1).
#   7. aws_cloudwatch_log_group.elasticache_slow   — KMS-encrypted log group
#                                                    for Redis SLOWLOG output.
#   8. aws_cloudwatch_log_group.elasticache_engine — KMS-encrypted log group
#                                                    for Redis engine logs.
#   9. aws_elasticache_replication_group.carddemo  — Multi-node replication
#                                                    group with KMS at rest,
#                                                    TLS in transit (1.2+),
#                                                    AUTH, automatic
#                                                    failover, Multi-AZ,
#                                                    7-day snapshots, and
#                                                    log delivery to (7)+(8).
#
# Security posture (PCI-DSS-aligned per AAP §0.6.6, §0.7.1):
#   * Encryption at rest — KMS customer-managed CMK (`aws_kms_key.carddemo`
#     from kms.tf) for Redis storage, the Secrets Manager AUTH secret, and
#     both CloudWatch log groups.
#   * Encryption in transit — TLS 1.2+ (transit_encryption_enabled = true).
#     The application's Lettuce client (RedisConfig.java) must connect with
#     `useSsl = true`.
#   * Authentication — Redis AUTH token, generated by random_password and
#     stored only in Secrets Manager (never in plaintext config files,
#     environment variables, or container images).
#   * Network — placed in private subnets only via the subnet group; no
#     public access path exists.
#   * Observability — slow-log and engine-log shipped to KMS-encrypted
#     CloudWatch log groups with 30-day retention (AAP §0.6.6).
#
# Coordination with sibling files:
#   * kms.tf — provides `aws_kms_key.carddemo` used by this file.
#   * variables.tf — exposes `var.environment`, `var.redis_node_type`,
#     `var.redis_num_cache_clusters`, `var.redis_engine_version`,
#     `var.redis_port`.
#   * main.tf — provides `local.common_tags`, `data.aws_vpc.carddemo`,
#     `data.aws_subnets.private`.
#   * ecs.tf, batch.tf — append ingress rules on
#     `aws_security_group.elasticache` to allow inbound 6379 from their own
#     task / job SGs (kept separate to avoid SG dependency cycles).
#   * outputs.tf — re-exports `elasticache_primary_endpoint`,
#     `elasticache_reader_endpoint`, `elasticache_port`, and
#     `elasticache_auth_secret_arn` for consumption by Spring Boot env vars
#     and CI/CD smoke tests.
#   * src/main/java/com/awsm2/carddemo/config/RedisConfig.java — Lettuce
#     connection factory reads the AUTH token from Secrets Manager via the
#     Spring Cloud AWS Secrets Manager integration.
#   * src/main/java/com/awsm2/carddemo/adapter/CacheService.java — cache-
#     aside implementation using RedisTemplate.
#
# References:
#   * AAP §0.1.1 — Core refactoring objective: cache-aside via ElastiCache
#     Redis for high-frequency account balance reads with allkeys-lru
#     eviction.
#   * AAP §0.3.3 — Design pattern: Cache-Aside with TTL aligned to
#     transaction frequency.
#   * AAP §0.6.6 — Cross-cutting: KMS CMK at rest, TLS 1.2+ in transit,
#     CloudWatch Logs encrypted via KMS.
#   * AAP §0.7.1 — Refactoring rules: AUTH credentials from Secrets Manager
#     only, never hardcoded.
###############################################################################

# =============================================================================
# Section 1 — Security group for the Redis ENIs
# =============================================================================
# The Redis nodes live on ENIs in the private subnets selected by the subnet
# group below. This security group is attached to every Redis ENI and gates
# inbound connectivity to the Redis listener port (var.redis_port, default
# 6379).
#
# Ingress strategy — defer to consumer modules:
#   This SG intentionally declares NO ingress rules inline. Consumer modules
#   (ecs.tf for the Spring Boot ECS service, batch.tf for AWS Batch jobs that
#   need cache access) attach their own `aws_security_group_rule` resources
#   that source from THEIR task / job SGs into THIS SG on port 6379. Keeping
#   ingress declarations out of this file prevents the classic Terraform SG
#   dependency cycle (where SG A needs to know SG B's ID and SG B needs to
#   know SG A's ID).
#
# Egress strategy — permissive:
#   Redis nodes legitimately need to make outbound connections to KMS (for
#   data-key decryption), Secrets Manager (for rotation grants), and S3
#   (for snapshot uploads). Rather than enumerating every AWS service
#   endpoint here, we allow all outbound traffic — the Interface VPC
#   endpoints provisioned in main.tf keep that traffic on the AWS backbone
#   and the actual authorization surface is enforced by KMS / Secrets
#   Manager / S3 IAM policies.
#
# Members exposed for downstream consumers (per the file schema):
#   id, arn, name, description, vpc_id, owner_id, tags_all.
# =============================================================================

resource "aws_security_group" "elasticache" {
  name        = "carddemo-${var.environment}-elasticache-sg"
  description = "ElastiCache Redis - inbound from ECS task and Batch on port 6379 (TLS); ingress rules attached by ecs.tf and batch.tf"
  vpc_id      = data.aws_vpc.carddemo.id

  # NOTE: ingress rules are intentionally omitted here. ecs.tf and batch.tf
  # attach `aws_security_group_rule` resources that reference this SG's id
  # as the destination. This prevents a Terraform dependency cycle between
  # the Redis SG and the consumer SGs.

  egress {
    description = "All outbound - Redis nodes call KMS, Secrets Manager, and S3 over the AWS backbone via VPC endpoints"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(local.common_tags, {
    Name    = "carddemo-${var.environment}-elasticache-sg"
    Purpose = "ElastiCache Redis cache-aside layer security group"
  })

  # Replacing this SG would force a replacement of the replication group
  # (security_group_ids is ForceNew on aws_elasticache_replication_group).
  # The create_before_destroy lifecycle minimizes blast radius if a name
  # collision forces an in-place rename.
  lifecycle {
    create_before_destroy = true
  }
}

# =============================================================================
# Section 2 — Subnet group (Multi-AZ private subnet placement)
# =============================================================================
# The subnet group defines the set of subnets across which ElastiCache
# distributes replication-group nodes. Two requirements drive this:
#
#   * Private-only placement — AAP §0.7.1 mandates that Redis never sit in
#     a public subnet. data.aws_subnets.private is filtered to the
#     operator-supplied private subnet IDs by main.tf, so this group
#     inherits that guarantee transparently.
#
#   * Multi-AZ spread — When `multi_az_enabled = true` on the replication
#     group below (active whenever var.redis_num_cache_clusters > 1), AWS
#     places the primary in one AZ and replicas in different AZs drawn
#     from this subnet group. The operator must therefore supply private
#     subnets in at least 2 distinct AZs in var.private_subnet_ids.
#
# Members exposed for downstream consumers (per the file schema):
#   id, arn, name, description, subnet_ids, tags_all.
# =============================================================================

resource "aws_elasticache_subnet_group" "carddemo" {
  name        = "carddemo-${var.environment}-redis-subnet-group"
  description = "Private subnets across multiple AZs for the CardDemo ElastiCache Redis replication group"
  subnet_ids  = data.aws_subnets.private.ids

  tags = merge(local.common_tags, {
    Name    = "carddemo-${var.environment}-redis-subnet-group"
    Purpose = "Multi-AZ private-subnet placement for Redis nodes"
  })
}

# =============================================================================
# Section 3 — Parameter group (allkeys-lru eviction + expiration events)
# =============================================================================
# Parameter groups are Redis configuration profiles that ElastiCache applies
# to every node in the replication group. CardDemo's parameter group sets:
#
#   * maxmemory-policy = allkeys-lru — Mandated by AAP §0.1.1. When the
#     node's memory reaches `maxmemory` (sized by `node_type`), Redis
#     evicts the least-recently-used key across the entire keyspace
#     regardless of whether it has a TTL. This matches the cache-aside
#     usage pattern: most keys carry a TTL aligned to transaction
#     frequency, but a pure-LRU eviction provides a safety net for traffic
#     bursts where TTLs have not yet expired.
#
#   * notify-keyspace-events = Ex — Enables expired-key notifications via
#     Redis Pub/Sub channel `__keyevent@<db>__:expired`. The Spring Boot
#     application's `AuditLogService` listens to this channel to capture
#     cache-expiration metrics in CloudWatch (per AAP §0.6.6 observability).
#     "E" enables keyevent notifications; "x" subscribes to expired events.
#
# Family selection — `redis7`:
#   Redis 7.x (default `engine_version = "7.1"`) requires the `redis7`
#   parameter group family. ElastiCache rejects family/version mismatches
#   at apply time.
#
# Members exposed for downstream consumers (per the file schema):
#   id, arn, name, family, description, tags_all.
# =============================================================================

resource "aws_elasticache_parameter_group" "carddemo" {
  name        = "carddemo-${var.environment}-redis-params"
  family      = "redis7"
  description = "CardDemo Redis parameters: allkeys-lru eviction (AAP §0.1.1) + expired-key notifications"

  # AAP §0.1.1 mandates allkeys-lru as the eviction policy for the cache-
  # aside layer. Other policies (volatile-lru, allkeys-random, noeviction)
  # would either bypass LRU semantics for keys with TTL (volatile-*) or
  # cause OOM rejections (noeviction).
  parameter {
    name  = "maxmemory-policy"
    value = "allkeys-lru"
  }

  # Publish expired-key events to Redis Pub/Sub so the application can
  # surface cache-expiration metrics in CloudWatch. "Ex" = keyevent
  # notifications for expired keys (lowercase "x") via the "E" channel
  # prefix.
  parameter {
    name  = "notify-keyspace-events"
    value = "Ex"
  }

  tags = merge(local.common_tags, {
    Name    = "carddemo-${var.environment}-redis-params"
    Purpose = "Redis parameter group with allkeys-lru eviction"
  })

  # Parameter group changes that require restart (e.g., family changes)
  # would otherwise force a replication-group replacement. The lifecycle
  # block lets Terraform create the new parameter group before destroying
  # the old one, minimizing downtime.
  lifecycle {
    create_before_destroy = true
  }
}

# =============================================================================
# Section 4 — Redis AUTH token managed in AWS Secrets Manager
# =============================================================================
# Per AAP §0.7.1 ("All credentials fetched at runtime from AWS Secrets Manager
# — never hardcoded, never in application.yml, never in plain environment
# variables"), the Redis AUTH token must be stored in Secrets Manager and
# read at runtime by the Spring Boot application via Spring Cloud AWS
# Secrets Manager integration.
#
# Bootstrap flow:
#   1. `random_password.redis_auth_token` generates a 64-character
#      alphanumeric token at apply time. The Redis AUTH protocol restricts
#      tokens to alphanumeric characters (no special characters), so
#      `special = false` is required.
#   2. `aws_secretsmanager_secret.redis_auth` creates the KMS-encrypted
#      secret container. KMS envelope encryption protects the secret at
#      rest using the customer-managed CMK from kms.tf.
#   3. `aws_secretsmanager_secret_version.redis_auth_value` stores the
#      JSON-encoded payload `{ "auth_token": "<random-value>" }`. The JSON
#      structure matches what Spring Cloud AWS Secrets Manager expects when
#      it auto-binds the secret to Spring properties.
#   4. `aws_elasticache_replication_group.carddemo` references
#      `random_password.redis_auth_token.result` directly for its
#      `auth_token` argument (Terraform must be able to resolve the value
#      at apply time, before Spring Boot consults Secrets Manager).
#
# Rotation strategy:
#   * `auth_token_update_strategy = "ROTATE"` on the replication group
#     instructs ElastiCache to perform a non-disruptive rotation when the
#     auth_token argument changes — both the old and the new token are
#     accepted during a brief overlap window.
#   * A future rotation Lambda (declared in secrets.tf when rotation is
#     enabled) will publish new versions of this secret; the Spring Boot
#     application's @RefreshScope-annotated Lettuce connection factory
#     re-reads the rotated token on the next refresh event without a
#     restart per AAP §0.6.4.
# =============================================================================

# -----------------------------------------------------------------------------
# Random AUTH token — 64 alphanumeric characters.
#
# Members exposed for downstream consumers (per the file schema):
#   result, length, special.
#
# Length rationale: 64 characters of [A-Za-z0-9] provide ~381 bits of
# entropy — well in excess of the PCI-DSS Requirement 8.2 minimum of 7
# characters and the practical NIST SP 800-63B Level 3 floor of 64 bits.
#
# `special = false` is mandatory: Redis 6/7 AUTH validation rejects tokens
# containing punctuation or whitespace. `min_special = 0` reinforces the
# constraint defensively.
#
# `min_numeric = 1` + `min_lower = 1` + `min_upper = 1` guarantee character
# class diversity so the generated string is not, e.g., all uppercase, which
# Redis would still accept but which would marginally reduce effective
# entropy.
# -----------------------------------------------------------------------------
resource "random_password" "redis_auth_token" {
  length      = 64
  special     = false # Redis AUTH protocol: alphanumeric only
  min_numeric = 1
  min_lower   = 1
  min_upper   = 1
  min_special = 0
}

# -----------------------------------------------------------------------------
# Secrets Manager secret container.
#
# `kms_key_id` references the customer-managed KMS CMK from kms.tf, per
# AAP §0.7.1 mandate that all secrets be encrypted at rest with a CMK
# (not the AWS-managed `aws/secretsmanager` default key). Using a CMK
# enables CloudTrail key-usage events for compliance reporting and
# IAM-based access scoping at the key-policy level.
#
# `recovery_window_in_days` uses the AWS default (30 days). This permits
# accidental-deletion recovery within the window. Dev sandboxes that need
# rapid teardown can override via `terraform destroy -auto-approve` after
# scheduling deletion with a 0-day window via the API.
#
# Members exposed for downstream consumers (per the file schema):
#   id, arn, name, description, kms_key_id, tags_all.
# -----------------------------------------------------------------------------
resource "aws_secretsmanager_secret" "redis_auth" {
  name        = "carddemo-${var.environment}-redis-auth"
  description = "Redis AUTH token for CardDemo ElastiCache replication group (AAP §0.7.1 — credentials in Secrets Manager only)"
  kms_key_id  = aws_kms_key.carddemo.arn

  tags = merge(local.common_tags, {
    Name    = "carddemo-${var.environment}-redis-auth"
    Purpose = "Redis AUTH token for cache-aside layer"
  })
}

# -----------------------------------------------------------------------------
# Initial AUTH token version.
#
# Stores the JSON-encoded payload `{ "auth_token": "<value>" }` as the
# AWSCURRENT version of the secret. The Spring Boot RedisConfig reads
# this JSON via the Spring Cloud AWS Secrets Manager binder and extracts
# the `auth_token` field for the Lettuce connection factory.
#
# When a future rotation Lambda is added (secrets.tf), it will publish new
# versions via the PutSecretValue API; AWSCURRENT will shift to the new
# version and AWSPREVIOUS will retain the Terraform-managed version
# briefly so the replication-group rotation can validate the new value.
#
# Members exposed for downstream consumers (per the file schema):
#   id, secret_id, version_id, version_stages, arn.
# -----------------------------------------------------------------------------
resource "aws_secretsmanager_secret_version" "redis_auth_value" {
  secret_id = aws_secretsmanager_secret.redis_auth.id

  secret_string = jsonencode({
    auth_token = random_password.redis_auth_token.result
  })

  # Default version_stages is ["AWSCURRENT"] which is exactly what we want
  # for the initial version. The rotation Lambda manages subsequent stage
  # transitions automatically.
}

# =============================================================================
# Section 5 — CloudWatch log groups for Redis slow-log and engine-log
# =============================================================================
# ElastiCache supports streaming two log types to CloudWatch Logs:
#
#   * slow-log    — Redis SLOWLOG entries (commands exceeding the
#                   slowlog-log-slower-than threshold, which defaults to
#                   10ms). Critical for diagnosing latency regressions in
#                   the cache-aside read path.
#   * engine-log  — Redis server-side events (rebalances, snapshot starts,
#                   replication progress, OOM warnings). Critical for
#                   observability of background ElastiCache activity.
#
# Both log groups are KMS-encrypted (`kms_key_id` references the CardDemo
# CMK from kms.tf) per AAP §0.6.6 "CloudWatch Logs encrypted via KMS",
# and both use a 30-day retention window which matches the default
# observability retention applied across the module.
#
# Naming convention: `/aws/elasticache/<resource-name-prefix>/<log-type>`
# keeps log groups grouped under the same hierarchical prefix in the
# CloudWatch console, mirroring the convention used by RDS, ECS, and
# Step Functions log groups elsewhere in this module.
#
# Members exposed for downstream consumers (per the file schema):
#   id, arn, name, retention_in_days, kms_key_id, tags_all (for both).
# =============================================================================

resource "aws_cloudwatch_log_group" "elasticache_slow" {
  name              = "/aws/elasticache/carddemo-${var.environment}/slow-log"
  retention_in_days = 30
  kms_key_id        = aws_kms_key.carddemo.arn

  tags = merge(local.common_tags, {
    Name    = "carddemo-${var.environment}-redis-slow-log"
    Purpose = "Redis SLOWLOG output for cache-aside latency observability"
  })
}

resource "aws_cloudwatch_log_group" "elasticache_engine" {
  name              = "/aws/elasticache/carddemo-${var.environment}/engine-log"
  retention_in_days = 30
  kms_key_id        = aws_kms_key.carddemo.arn

  tags = merge(local.common_tags, {
    Name    = "carddemo-${var.environment}-redis-engine-log"
    Purpose = "Redis engine events (snapshots, replication, OOM)"
  })
}

# =============================================================================
# Section 6 — Replication group (the actual Redis cluster)
# =============================================================================
# The replication group is the central resource of this file. It provisions
# `var.redis_num_cache_clusters` nodes (one primary + N-1 replicas) running
# Redis `var.redis_engine_version` on `var.redis_node_type` instance class,
# wired together with KMS-at-rest encryption, TLS-in-transit, AUTH, Multi-
# AZ failover, 7-day snapshots, and CloudWatch log delivery.
#
# High-availability semantics:
#   * `automatic_failover_enabled` and `multi_az_enabled` are both bound
#     to the boolean expression `var.redis_num_cache_clusters > 1`. When
#     true (the prod default of 2 nodes), ElastiCache continuously monitors
#     the primary's health and promotes a replica to primary on detected
#     failure with sub-minute RTO. When false (dev single-node), failover
#     is operator-driven and Multi-AZ is moot.
#   * `multi_az_enabled = true` REQUIRES `automatic_failover_enabled =
#     true` per AWS API contract. Both bool expressions resolve from the
#     same condition so the constraint is always satisfied.
#
# Encryption configuration (AAP §0.6.6, §0.7.1):
#   * `at_rest_encryption_enabled = true` — Mandatory. Redis snapshots
#     persisted to S3 and AOF storage volumes are encrypted with the CMK
#     referenced by `kms_key_id`. Without this flag, encryption-at-rest
#     defaults to OFF on ElastiCache.
#   * `kms_key_id = aws_kms_key.carddemo.arn` — Customer-managed CMK
#     (mandated by AAP §0.7.1 "Encrypt all RDS data at rest using AWS KMS
#     customer-managed keys (CMKs)" which the AAP applies equally to
#     ElastiCache per §0.6.6).
#   * `transit_encryption_enabled = true` — Mandatory. Forces TLS 1.2+
#     for all client connections; required for `auth_token` to function
#     (AWS rejects auth_token configuration when transit encryption is
#     disabled).
#   * `auth_token` — References the random_password value directly so
#     ElastiCache provisions with the same token that was just persisted
#     to Secrets Manager. The Spring Boot application later reads the
#     same token from Secrets Manager at runtime.
#   * `auth_token_update_strategy = "ROTATE"` — Non-disruptive token
#     rotation when the auth_token argument changes. The replication
#     group accepts both old and new tokens during a brief overlap
#     window so clients can refresh without dropped connections.
#
# Snapshot strategy:
#   * `snapshot_retention_limit = 7` — Daily snapshots retained for 7
#     days. Snapshots are encrypted with the same CMK as live data via
#     AWS-managed grants.
#   * `snapshot_window = "03:00-04:00"` — Off-hours UTC window aligning
#     with the EOD batch pipeline's quiet period (POSTTRAN → INTCALC
#     runs in the 22:00-02:00 UTC window per AAP §0.6.3 EOD pipeline).
#
# Maintenance window:
#   * `maintenance_window = "sun:04:30-sun:05:30"` — Weekly window after
#     the snapshot completes; ElastiCache applies engine patches during
#     this window. `apply_immediately = false` defers in-place changes
#     to this window unless an operator overrides via API.
#
# Log delivery (Section 5 log groups):
#   * Two `log_delivery_configuration` blocks ship slow-log and engine-
#     log streams to the KMS-encrypted CloudWatch log groups defined
#     above. Both use `log_format = "json"` for machine-parseable output
#     (the Spring Boot CloudWatch alerting wires regex filters against
#     these JSON-structured events).
#
# Members exposed for downstream consumers (per the file schema):
#   id, arn, replication_group_id, description, engine, engine_version,
#   engine_version_actual, node_type, num_cache_clusters, port,
#   primary_endpoint_address, reader_endpoint_address,
#   configuration_endpoint_address, member_clusters, parameter_group_name,
#   subnet_group_name, security_group_ids, automatic_failover_enabled,
#   multi_az_enabled, at_rest_encryption_enabled,
#   transit_encryption_enabled, kms_key_id, snapshot_retention_limit,
#   snapshot_window, maintenance_window, tags_all.
# =============================================================================

resource "aws_elasticache_replication_group" "carddemo" {
  replication_group_id = "carddemo-${var.environment}-redis"
  description          = "CardDemo Redis cache-aside layer (account balance reads) - AAP §0.1.1"

  # Engine selection — Redis 7.x family. Redis 6.x is on the deprecation
  # path; Redis 7.x adds ACLs, multi-DB clients on shared connections, and
  # better OOM handling.
  engine         = "redis"
  engine_version = var.redis_engine_version

  # Sizing controlled by variables.tf — node class and replica count are
  # the primary cost / capacity knobs per environment.
  node_type          = var.redis_node_type
  num_cache_clusters = var.redis_num_cache_clusters
  port               = var.redis_port

  # Configuration linkage — references the parameter group, subnet group,
  # and security group defined earlier in this file.
  parameter_group_name = aws_elasticache_parameter_group.carddemo.name
  subnet_group_name    = aws_elasticache_subnet_group.carddemo.name
  security_group_ids   = [aws_security_group.elasticache.id]

  # High availability — both flags activate only when >= 2 nodes exist.
  # ElastiCache rejects multi_az_enabled = true with a single-node cluster.
  automatic_failover_enabled = var.redis_num_cache_clusters > 1
  multi_az_enabled           = var.redis_num_cache_clusters > 1

  # Encryption-at-rest — mandatory per AAP §0.7.1.
  at_rest_encryption_enabled = true
  kms_key_id                 = aws_kms_key.carddemo.arn

  # Encryption-in-transit — mandatory per AAP §0.6.6. Forces TLS 1.2+.
  transit_encryption_enabled = true

  # Authentication — AUTH token sourced from the random_password created
  # above. Same value is stored in Secrets Manager for application access.
  auth_token                 = random_password.redis_auth_token.result
  auth_token_update_strategy = "ROTATE"

  # Backups — daily snapshot retained 7 days in S3 (KMS-encrypted via grant).
  snapshot_retention_limit = 7
  snapshot_window          = "03:00-04:00" # UTC; runs before maintenance window

  # Maintenance — weekly window after the snapshot completes. apply_
  # immediately = false defers operator-initiated in-place changes to
  # this window unless explicitly overridden.
  maintenance_window = "sun:04:30-sun:05:30" # UTC
  apply_immediately  = false

  # Slow-log delivery to CloudWatch Logs (JSON format for filter parsing).
  log_delivery_configuration {
    destination      = aws_cloudwatch_log_group.elasticache_slow.name
    destination_type = "cloudwatch-logs"
    log_format       = "json"
    log_type         = "slow-log"
  }

  # Engine-log delivery to CloudWatch Logs (JSON format for filter parsing).
  log_delivery_configuration {
    destination      = aws_cloudwatch_log_group.elasticache_engine.name
    destination_type = "cloudwatch-logs"
    log_format       = "json"
    log_type         = "engine-log"
  }

  tags = merge(local.common_tags, {
    Name    = "carddemo-${var.environment}-redis"
    Purpose = "Cache-aside layer for high-frequency account balance reads"
  })

  # Explicit dependency on the secret version ensures that the AUTH token
  # is durably persisted in Secrets Manager BEFORE the replication group
  # is provisioned with the same token. Without this, a transient apply
  # failure between Secrets Manager and ElastiCache provisioning could
  # leave the token in the replication group without a corresponding
  # secret entry for the application to read.
  depends_on = [
    aws_secretsmanager_secret_version.redis_auth_value,
    aws_cloudwatch_log_group.elasticache_slow,
    aws_cloudwatch_log_group.elasticache_engine,
  ]
}

