###############################################################################
# infrastructure/terraform/opensearch.tf
#
# Amazon OpenSearch Service domain for the CardDemo target architecture.
#
# Purpose
# -------
# Provisions a VPC-internal, KMS-encrypted, fine-grained-access-controlled
# Amazon OpenSearch Service domain that serves as the canonical
# indexed-and-searchable retention layer for:
#
#   1. Application audit-trail events emitted by the Spring Boot
#      OpenSearchIndexer adapter and the AuditLogService
#      (src/main/java/com/awsm2/carddemo/adapter/OpenSearchIndexer.java,
#      AuditLogService.java). These events carry the transaction IDs,
#      timestamps, operator codes, and reason codes that the original
#      COBOL audit trail writes preserved verbatim per AAP Section 0.6.6.
#
#   2. CloudTrail events forwarded into OpenSearch for searchable
#      regulatory queries and fraud investigation per AAP Section 0.6.6
#      ("Amazon OpenSearch indexes both CloudTrail events and
#      application-emitted audit logs ... preserved verbatim from COBOL
#      audit trail writes").
#
#   3. Log aggregation across ECS Fargate tasks, AWS Batch jobs, and
#      Step Functions executions (the structured JSON logs emitted by
#      Logback/logstash-logback-encoder are shipped to CloudWatch Logs
#      first; selective subscription filters can forward to this domain).
#
# Security posture (per AAP Section 0.6.6 + Section 0.7.1, MANDATORY)
# -------------------------------------------------------------------
#   * encrypt_at_rest.enabled       = true (KMS CMK from kms.tf)
#   * node_to_node_encryption        = true (TLS within the cluster)
#   * domain_endpoint_options:
#       - enforce_https              = true (no plaintext HTTP)
#       - tls_security_policy        = Policy-Min-TLS-1-2-PFS-2023-10
#         (PCI-DSS-aligned TLS 1.2+ minimum, PFS-enforced cipher suites)
#   * vpc_options                    = present + private subnets only
#     (the absence of vpc_options would create a public-internet domain,
#      which is FORBIDDEN by AAP Section 0.6.6 and PCI-DSS scope rules)
#   * advanced_security_options:
#       - enabled                            = true
#       - internal_user_database_enabled     = true
#       - master_user_password               = sourced from Secrets Manager
#         (NEVER hardcoded; the password is generated by random_password
#          and stored in aws_secretsmanager_secret.opensearch_master from
#          secrets.tf -- this file writes the AWSCURRENT version and reads
#          it back via jsondecode(secret_string)["password"])
#   * access_policies                = whitelisted IAM principals only
#     (NEVER Principal "*"; only the ECS task role from iam.tf is granted
#      es:ESHttp* on the domain ARN pattern)
#   * Tags                           = local.common_tags applied
#     (Project / Environment / Owner / ManagedBy by provider default_tags;
#      Name / Purpose merged in per-resource for console clarity)
#
# Inputs (from sibling .tf files, MUST be present prior to terraform plan)
# ------------------------------------------------------------------------
#   * main.tf  : local.common_tags, data.aws_caller_identity.current,
#                data.aws_vpc.carddemo (id + cidr_block),
#                data.aws_subnets.private (ids)
#   * kms.tf   : aws_kms_key.carddemo (primary CardDemo CMK with
#                es.amazonaws.com principal statement in the key policy
#                granting kms:Decrypt / kms:GenerateDataKey /
#                kms:CreateGrant / kms:DescribeKey -- see kms.tf
#                Statement 10 "AllowOpenSearch")
#   * iam.tf   : aws_iam_role.ecs_task_role (ECS Fargate application
#                runtime role -- granted es:ESHttp* in this file's
#                access_policies; the role itself already has the
#                matching outbound permissions in its inline policy
#                via data.aws_iam_policy_document.ecs_task_runtime
#                Statement "OpenSearchESHttp")
#   * secrets.tf: aws_secretsmanager_secret.opensearch_master (KMS-
#                encrypted secret container; this file writes the
#                AWSCURRENT version)
#   * cloudwatch.tf: aws_cloudwatch_log_group.opensearch (KMS-encrypted
#                CloudWatch Log Group receiving INDEX_SLOW_LOGS,
#                SEARCH_SLOW_LOGS, ES_APPLICATION_LOGS, and AUDIT_LOGS)
#   * variables.tf: var.aws_region, var.environment,
#                var.opensearch_instance_type,
#                var.opensearch_instance_count,
#                var.opensearch_volume_size
#
# Outputs (consumed by other .tf files / the Spring Boot application)
# -------------------------------------------------------------------
#   * aws_opensearch_domain.carddemo.endpoint
#       -> outputs.tf -> OPENSEARCH_ENDPOINT environment variable in
#       ECS task definition -> Spring application-prod.yml
#       opensearch.uri property -> OpenSearchIndexer high-level REST
#       client.
#   * aws_opensearch_domain.carddemo.dashboard_endpoint
#       -> human operators access the OpenSearch Dashboards UI for
#       fraud investigation and regulatory queries (AAP Section 0.6.6).
#   * aws_secretsmanager_secret_version.opensearch_master.arn
#       -> ecs.tf injects this secret via the ECS task definition
#       secrets[].valueFrom for OPENSEARCH_PASSWORD environment
#       variable per AAP Section 0.6.4 (no plaintext credentials in
#       env vars or config files).
#
# References
# ----------
#   * AAP Section 0.6.6 -- Cross-Cutting: Audit, Observability, and PCI-DSS.
#     "Amazon OpenSearch indexes both CloudTrail events and
#     application-emitted audit logs (transaction IDs, timestamps,
#     operator codes -- preserved verbatim from COBOL audit trail
#     writes)."
#   * AAP Section 0.6.4 -- AWS Secrets Manager Dynamic Rotation Without
#     Restart. The OpenSearch master credential is rotated via secrets.tf
#     and re-read by the Spring application via @RefreshScope without
#     JVM restart.
#   * AAP Section 0.7.1 -- Refactoring rules: all credentials fetched at
#     runtime from AWS Secrets Manager; all data at rest encrypted via
#     AWS KMS customer-managed keys.
#   * AAP Section 0.7.2 -- PCI-DSS encryption-at-rest, encryption-in-
#     transit, and audit-logging requirements. OpenSearch slow logs and
#     audit logs flow to CloudWatch with KMS encryption and >= 365-day
#     retention for regulatory queries.
#   * Replaces: SDSF-based mainframe log inspection (the operator pattern
#     used in samples/jcl/* and the JCL workflows under app/jcl/). The
#     z/OS LPAR's SDSF + JES2 log spool is replaced by CloudWatch Logs
#     forwarding into OpenSearch.
###############################################################################

# =============================================================================
# Section 1 -- OpenSearch master user password (random + Secrets Manager)
# =============================================================================
# OpenSearch fine-grained access control (FGAC) requires a master user
# (username + password) that is used to bootstrap roles and role
# mappings. The username is fixed at "carddemo_admin"; the password is
# generated by the Random provider here and stored in the Secrets-
# Manager-owned container declared in secrets.tf
# (`aws_secretsmanager_secret.opensearch_master`).
#
# Per AAP Section 0.7.1 the password is NEVER hardcoded, NEVER inlined
# in application.yml, NEVER exposed as a plaintext environment variable.
# The flow is:
#
#   1. random_password.opensearch_master generates a 32-character
#      password at apply time. Character class diversification (min_*)
#      satisfies OpenSearch FGAC password complexity requirements
#      (>= 1 uppercase, >= 1 lowercase, >= 1 digit, >= 1 special).
#
#   2. aws_secretsmanager_secret_version.opensearch_master writes the
#      JSON-encoded payload { "username": "carddemo_admin", "password":
#      "<random>" } as the AWSCURRENT version of the secrets.tf-owned
#      secret container. The domain endpoint is deliberately OMITTED
#      from this JSON to keep the dependency chain acyclic; the
#      endpoint is published separately via outputs.tf.
#
#   3. aws_opensearch_domain.carddemo.advanced_security_options.
#      master_user_options.master_user_password reads the password back
#      from aws_secretsmanager_secret_version.opensearch_master via
#      jsondecode(secret_string)["password"]. Terraform resolves the
#      implicit dependency by ordering version create BEFORE the domain
#      attribute read.
#
#   4. ecs.tf injects the secret ARN into the ECS task definition as
#      a secret reference (secrets[].valueFrom) for the
#      OPENSEARCH_PASSWORD environment variable. The Spring Boot
#      application's @RefreshScope-wrapped OpenSearch client re-reads
#      the rotated password on the next refresh event per AAP
#      Section 0.6.4.
#
# OpenSearch FGAC special-character restrictions
# ----------------------------------------------
# OpenSearch master-user passwords must satisfy the following per the
# AWS service contract (verified at provider version `~> 5.0`):
#   * 8-128 characters
#   * at least one uppercase, one lowercase, one digit, one special
#   * special characters limited to: ~ ! @ # $ % ^ & * ( ) _ + - = { }
#     [ ] | ; : , . ? <space is forbidden>
#
# The override_special set below intersects the OpenSearch-allowed
# specials with characters that are JSON-safe (no double-quote /
# backslash, which would require escaping in the secret_string
# jsonencode) and shell-safe (no $ which conflicts with shell variable
# expansion when the secret is consumed by ECS task command lines).
# =============================================================================

resource "random_password" "opensearch_master" {
  length      = 32
  special     = true
  min_lower   = 1
  min_upper   = 1
  min_numeric = 1
  min_special = 2

  # OpenSearch-FGAC-safe special characters. Intersection of the
  # OpenSearch master-user password allowlist with characters that
  # are JSON-safe (no " or \) and shell-safe (no $, no whitespace).
  # The remaining set { ! # % & ( ) * + - . / : ; < = > ? @ [ ] ^ _ { | } ~ }
  # is deliberately reduced to: ! @ # ^ * - _ + = . ? ( ) [ ] { } | ~
  # which AWS Secrets Manager confirms accepts without URL-encoding
  # ambiguity when the secret is read by Spring Cloud AWS Secrets
  # Manager binder.
  override_special = "!@#^*-_+=.?()[]{}|~"
}

# -----------------------------------------------------------------------------
# Secret version: writes the AWSCURRENT JSON payload to the secrets.tf-owned
# container. The application reads the `password` field from the JSON envelope
# (matching the same pattern used by rds.tf / elasticache.tf).
#
# secret_id is the ID of `aws_secretsmanager_secret.opensearch_master` from
# secrets.tf (Section 2). KMS encryption is inherited from the container
# (kms_key_id = aws_kms_key.carddemo.arn).
#
# lifecycle.ignore_changes = [secret_string] permits the future custom
# rotation flow (operator-driven `aws secretsmanager rotate-secret` per
# the secrets.tf documentation, or a future rotation Lambda) to publish
# new versions via PutSecretValue without Terraform attempting to revert
# the value on the next apply -- the standard non-drift pattern used by
# rds.tf, elasticache.tf, and jwt_signing_key in secrets.tf.
#
# Members exposed for downstream consumers (per the file schema):
#   id, secret_id, version_id, version_stages, arn.
# -----------------------------------------------------------------------------
resource "aws_secretsmanager_secret_version" "opensearch_master" {
  secret_id = aws_secretsmanager_secret.opensearch_master.id

  # JSON envelope payload -- username + password only.
  #
  # The OpenSearch domain endpoint is intentionally OMITTED from this
  # JSON because the domain itself reads `password` back from this
  # secret_version via jsondecode() in its
  # advanced_security_options.master_user_options.master_user_password
  # attribute (see Section 4 below). Including the endpoint here would
  # create a Terraform cyclic dependency:
  #
  #     secret_version.secret_string -> domain.endpoint
  #     domain.master_user_password  -> secret_version.secret_string
  #
  # Instead, the endpoint is exposed as a Terraform output from
  # outputs.tf (`opensearch_endpoint`) and the ECS task definition
  # injects it via the OPENSEARCH_ENDPOINT environment variable
  # alongside this secret's ARN for the OPENSEARCH_PASSWORD secret
  # reference. The Spring Boot OpenSearchConfig bean composes the URI
  # from the endpoint + the master credentials at startup, with
  # @RefreshScope re-binding on rotation per AAP Section 0.6.4.
  #
  # The Spring Cloud AWS Secrets Manager binder auto-binds top-level
  # JSON keys to Spring `Environment` properties, so the application
  # reads `password` directly without manually parsing the secret.
  secret_string = jsonencode({
    username = "carddemo_admin"
    password = random_password.opensearch_master.result
  })

  # Default version_stages is ["AWSCURRENT"] which is exactly what we
  # want for the initial version. Subsequent rotation flows manage
  # AWSCURRENT / AWSPREVIOUS / AWSPENDING stage transitions
  # automatically.

  lifecycle {
    # Allow operator-driven or Lambda-driven rotation to publish new
    # versions via PutSecretValue without Terraform drift (per AAP
    # Section 0.6.4). Without this guard, every apply after a rotation
    # would revert the secret to the Terraform-bootstrapped value.
    ignore_changes = [secret_string]
  }
}

# =============================================================================
# Section 2 -- OpenSearch security group (VPC-internal access only)
# =============================================================================
# VPC security group attached to the OpenSearch domain ENIs (one per
# subnet under vpc_options.subnet_ids). Allows HTTPS (443) ingress from
# every workload running inside the CardDemo VPC by reference to the
# operator-provisioned VPC CIDR block.
#
# Ingress strategy -- VPC-CIDR rule + future per-SG refinement
# ------------------------------------------------------------
# The schema purpose (depends_on_files -> main.tf) explicitly mandates
# "VPC-CIDR-based ingress that avoids a circular dependency on ecs.tf's
# aws_security_group.ecs_task". This is intentional: ecs.tf has not yet
# been created at the time this file is provisioned, and referencing a
# not-yet-defined SG would either fail terraform plan (if ecs.tf is
# absent) or create a classic SG-A-needs-SG-B / SG-B-needs-SG-A cycle.
#
# The VPC-CIDR ingress is functionally equivalent for security purposes:
# all CardDemo workloads (ECS tasks, AWS Batch jobs, AWS Glue jobs,
# Lambda functions) are deployed exclusively into the private subnets
# whose CIDR ranges are subsets of data.aws_vpc.carddemo.cidr_block.
# Subnet-level access is further restricted by NACLs and by IAM-based
# access control on the OpenSearch domain itself (access_policies in
# Section 4).
#
# A future iteration MAY tighten ingress by adding an explicit
# aws_security_group_rule resource in ecs.tf that sources from
# aws_security_group.ecs_task.id and destination = this SG's id, while
# keeping the VPC-CIDR rule as a defense-in-depth fallback OR removing
# it as the per-SG rule supersedes it.
#
# Egress strategy -- permissive
# -----------------------------
# OpenSearch nodes need outbound access to:
#   * KMS (kms.<region>.amazonaws.com) for data-key decrypt on every
#     index segment write, plus daily snapshot encryption operations.
#   * S3 (s3.<region>.amazonaws.com) for automated snapshot uploads
#     (snapshot_options.automated_snapshot_start_hour = 3 below).
#   * CloudWatch Logs (logs.<region>.amazonaws.com) for slow-log /
#     audit-log delivery.
# Rather than enumerating each AWS service endpoint, allow all outbound
# traffic; the Interface VPC endpoints provisioned in main.tf
# (aws_vpc_endpoint.kms, .logs) keep that traffic on the AWS backbone
# and the actual authorization surface is enforced by KMS, S3, and
# CloudWatch Logs IAM policies.
#
# Members exposed for downstream consumers (per the file schema):
#   id, arn, name, description, vpc_id, ingress, egress, tags_all.
# =============================================================================

resource "aws_security_group" "opensearch" {
  name        = "carddemo-${var.environment}-opensearch-sg"
  description = "Amazon OpenSearch domain - inbound HTTPS (443) from CardDemo VPC CIDR; consumer-SG refinement attached by ecs.tf when present"
  vpc_id      = data.aws_vpc.carddemo.id

  # HTTPS (443) ingress from the VPC CIDR. All CardDemo workloads
  # (ECS tasks, AWS Batch jobs, AWS Glue jobs, Lambda functions) are
  # deployed into private subnets whose CIDR ranges are subsets of
  # data.aws_vpc.carddemo.cidr_block, so this rule grants them HTTPS
  # access to the OpenSearch domain ENI in each subnet.
  ingress {
    description = "HTTPS from within the CardDemo VPC (ECS tasks, Batch jobs, Glue, Lambda)"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = [data.aws_vpc.carddemo.cidr_block]
  }

  # Permissive egress -- OpenSearch nodes call KMS for data-key
  # operations, S3 for snapshot uploads, and CloudWatch Logs for
  # slow-log / audit-log delivery. The Interface VPC endpoints in
  # main.tf (kms, logs) keep that traffic on the AWS backbone.
  egress {
    description = "All outbound - KMS, S3, CloudWatch Logs via VPC endpoints"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(local.common_tags, {
    Name    = "carddemo-${var.environment}-opensearch-sg"
    Purpose = "OpenSearch domain ENI security group (HTTPS from VPC CIDR)"
  })

  # Replacing this SG would force a replacement of the OpenSearch
  # domain (vpc_options.security_group_ids is ForceNew on
  # aws_opensearch_domain). The create_before_destroy lifecycle
  # minimises blast radius if a name collision forces an in-place
  # rename.
  lifecycle {
    create_before_destroy = true
  }
}

# =============================================================================
# Section 3 -- OpenSearch domain access policy
# =============================================================================
# IAM-based access policy attached to the OpenSearch domain via the
# `access_policies` argument of aws_opensearch_domain.carddemo. Grants
# `es:ESHttp*` actions (the union of ESHttpGet / ESHttpPost / ESHttpPut
# / ESHttpDelete / ESHttpHead / ESHttpPatch -- the entire surface area
# of the OpenSearch HTTP API) on every index in the domain to the ECS
# task role only.
#
# Principal scope -- NEVER "*"
# ----------------------------
# Per AAP Section 0.6.6 + Section 0.7.1 the domain MUST NOT be publicly
# accessible. The access policy whitelists exactly one IAM principal:
# aws_iam_role.ecs_task_role.arn (the Spring Boot application runtime
# role from iam.tf). This is enforced at two layers:
#
#   1. Network layer  -- vpc_options.subnet_ids restricts the domain
#      ENIs to private subnets only; the aws_security_group.opensearch
#      restricts ingress to the VPC CIDR.
#   2. Identity layer -- access_policies grants permissions to the ECS
#      task role's IAM ARN only; the ECS task role's matching outbound
#      policy in iam.tf (data.aws_iam_policy_document.ecs_task_runtime
#      Statement "OpenSearchESHttp") completes the chain.
#
# Resource ARN pattern
# --------------------
# arn:<partition>:es:<region>:<account>:domain/carddemo-<env>/* -- the
# trailing /* covers every index path (e.g., domain/carddemo-prod/
# audit-2026.01/_doc, domain/carddemo-prod/cloudtrail-2026.01/_search).
# The partition is sourced from local.partition (typically "aws"; may
# be "aws-us-gov" or "aws-cn" in those partitions).
#
# Members exposed for downstream consumers (per the file schema):
#   json (rendered by aws_opensearch_domain.carddemo.access_policies).
# =============================================================================

data "aws_iam_policy_document" "opensearch_access" {
  # Statement 1 -- ECS task role HTTP access to OpenSearch indices.
  #
  # The application's OpenSearchIndexer adapter
  # (src/main/java/com/awsm2/carddemo/adapter/OpenSearchIndexer.java)
  # and AuditLogService write transaction-audit events to the domain
  # via the OpenSearch REST high-level client. The client signs every
  # HTTP request with the ECS task role's temporary credentials
  # (from the IMDSv2 instance metadata exposed by the ECS Fargate
  # agent), so the domain validates this exact principal ARN.
  statement {
    sid    = "AllowECSTaskRoleESHttp"
    effect = "Allow"

    actions = [
      "es:ESHttp*"
    ]

    resources = [
      "arn:${local.partition}:es:${var.aws_region}:${local.account_id}:domain/carddemo-${var.environment}",
      "arn:${local.partition}:es:${var.aws_region}:${local.account_id}:domain/carddemo-${var.environment}/*"
    ]

    principals {
      type        = "AWS"
      identifiers = [aws_iam_role.ecs_task_role.arn]
    }
  }
}

# =============================================================================
# Section 4 -- Amazon OpenSearch Service domain
# =============================================================================
# The central resource of this file. Provisions a VPC-internal,
# KMS-encrypted, fine-grained-access-controlled OpenSearch domain
# running OpenSearch_2.11 on var.opensearch_instance_type instance
# class with gp3 EBS storage, KMS-CMK encryption at rest, node-to-node
# TLS encryption, HTTPS-only endpoint at TLS 1.2+ with PFS, four
# CloudWatch log_publishing_options blocks, daily automated snapshots
# at 03:00 UTC, and conditional Multi-AZ + dedicated master nodes
# + auto-tune in production.
#
# Engine version selection
# ------------------------
# OpenSearch_2.11 was the latest GA major.minor release at AAP
# composition time (May 2026 demo date), supported on every AWS
# region. Future engine upgrades follow the AWS OpenSearch in-place
# blue/green upgrade flow with minimal disruption; Terraform tracks
# the engine_version as a configurable attribute (avoid drift by
# bumping the version here when upgrading).
#
# Cluster topology -- per-environment sizing
# ------------------------------------------
# Production (var.environment == "prod"):
#   * 3 data nodes (var.opensearch_instance_count) for ISR=2 + 1 AZ
#     failure tolerance.
#   * 3 dedicated master nodes (m6g.large.search) -- mandatory for
#     production-grade cluster state stability per AWS OpenSearch
#     operational best practices.
#   * zone_awareness_enabled = true with availability_zone_count = 3
#     -- distributes shards across 3 AZs with replica placement
#     guarantees.
#   * auto_tune_options.desired_state = "ENABLED" -- AWS auto-tune
#     adjusts JVM heap, GC, and queue settings based on observed
#     workload patterns.
#
# Dev / staging (var.environment != "prod"):
#   * var.opensearch_instance_count data nodes (default 2 per
#     variables.tf), no dedicated master nodes, no zone awareness,
#     auto-tune disabled. Reduces cost ~70% vs prod while preserving
#     the same wire protocol + IAM contract.
#
# EBS storage
# -----------
# gp3 (general-purpose SSD with provisioned IOPS) at
# var.opensearch_volume_size GiB per node (default 100). The volume
# size sizes for the retention window (default 365 days of audit /
# CloudTrail events at the observed CardDemo transaction rate);
# production deployments should size from real-world ingestion
# observed during the parallel-run cutover validation period.
#
# Encryption (MANDATORY per AAP Section 0.6.6 + Section 0.7.1)
# ------------------------------------------------------------
#   * encrypt_at_rest.enabled        = true
#   * encrypt_at_rest.kms_key_id     = aws_kms_key.carddemo.arn
#     (the primary CardDemo CMK from kms.tf; the key policy in kms.tf
#      Statement "AllowOpenSearch" grants the es.amazonaws.com service
#      principal kms:Decrypt / kms:GenerateDataKey / kms:CreateGrant /
#      kms:DescribeKey on this key)
#   * node_to_node_encryption.enabled = true
#     (TLS within the cluster; mandatory for fine-grained access
#      control per the AWS service contract)
#   * domain_endpoint_options.enforce_https = true
#     (rejects plaintext HTTP at the load balancer)
#   * domain_endpoint_options.tls_security_policy
#       = "Policy-Min-TLS-1-2-PFS-2023-10"
#     (PCI-DSS-aligned TLS 1.2+ minimum with Perfect Forward Secrecy
#      cipher suites enforced)
#
# Fine-grained access control (FGAC)
# ----------------------------------
# advanced_security_options.enabled = true activates the per-index
# / per-document / per-field access-control engine. The master user
# (carddemo_admin) bootstraps the role hierarchy; subsequent role
# mappings are managed by the application or operators via the
# Dashboards UI / API.
#
# Log publishing -- four CloudWatch log groups for slow logs + audit
# ------------------------------------------------------------------
# Per AAP Section 0.6.6, all four OpenSearch log types are streamed
# to CloudWatch Logs for searchable retention:
#   * INDEX_SLOW_LOGS      -- slow-write paths (>1s index by default)
#   * SEARCH_SLOW_LOGS     -- slow-search paths (>1s query by default)
#   * ES_APPLICATION_LOGS  -- OpenSearch server-side warnings / errors
#   * AUDIT_LOGS           -- every authenticated request (PCI-DSS
#                             Requirement 10 access-audit trail)
# All four route to aws_cloudwatch_log_group.opensearch (KMS-encrypted
# with var.cloudwatch_log_retention_days retention; see cloudwatch.tf
# Section 1.5).
#
# Snapshots
# ---------
# AWS-managed automated snapshots (every OpenSearch domain receives
# them; cannot be disabled). snapshot_options.automated_snapshot_start_hour
# = 3 schedules the daily snapshot for 03:00 UTC -- aligns with the
# RDS automated backup window and avoids overlap with the end-of-day
# batch pipeline (POSTTRAN -> INTCALC -> COMBTRAN -> CREASTMT/TRANREPT
# from app/jcl/POSTTRAN.jcl + INTCALC.jcl + etc. typically completes
# by 02:00 UTC).
#
# Members exposed for downstream consumers (per the file schema):
#   arn, domain_id, domain_name, endpoint, dashboard_endpoint,
#   engine_version, kibana_endpoint, vpc_options, cluster_config,
#   encrypt_at_rest, node_to_node_encryption, domain_endpoint_options,
#   advanced_security_options, ebs_options, log_publishing_options,
#   snapshot_options, auto_tune_options, tags_all.
# =============================================================================

resource "aws_opensearch_domain" "carddemo" {
  domain_name    = "carddemo-${var.environment}"
  engine_version = "OpenSearch_2.11"

  # ---------------------------------------------------------------------------
  # Cluster topology -- conditional sizing for prod vs dev / staging.
  #
  # Production deployments get a 3-data-node + 3-dedicated-master-node
  # configuration with zone awareness across 3 AZs. Non-production
  # deployments get a single-zone cluster with var.opensearch_instance_count
  # data nodes (default 2 per variables.tf) and no dedicated masters.
  # ---------------------------------------------------------------------------
  cluster_config {
    instance_type  = var.opensearch_instance_type
    instance_count = var.opensearch_instance_count

    # Dedicated master nodes -- prod only.
    # Without dedicated masters the cluster state is managed by the
    # data nodes themselves, which can destabilize under heavy
    # ingestion. Production therefore mandates 3 dedicated masters
    # (m6g.large.search is the smallest production-recommended class
    # per AWS service guidance).
    dedicated_master_enabled = var.environment == "prod"
    dedicated_master_type    = var.environment == "prod" ? "m6g.large.search" : null
    dedicated_master_count   = var.environment == "prod" ? 3 : null

    # Zone awareness -- prod only.
    # Distributes shards and replicas across the configured AZs;
    # paired with dedicated masters this provides single-AZ-failure
    # tolerance.
    zone_awareness_enabled = var.environment == "prod"

    # The zone_awareness_config block is REQUIRED when
    # zone_awareness_enabled = true and FORBIDDEN otherwise.
    # `dynamic` solves the conditional-presence problem (Terraform
    # cannot omit a block based on a boolean; it can only iterate
    # over an empty / non-empty list).
    dynamic "zone_awareness_config" {
      for_each = var.environment == "prod" ? [1] : []

      content {
        availability_zone_count = 3
      }
    }
  }

  # ---------------------------------------------------------------------------
  # EBS storage -- gp3 volumes sized per node.
  #
  # gp3 (default 3000 IOPS / 125 MiB/s baseline) is suitable for the
  # OpenSearch audit / CloudTrail workload; provisioned IOPS / throughput
  # can be tuned upward via additional ebs_options arguments if observed
  # ingestion exceeds baseline. var.opensearch_volume_size defaults to
  # 100 GiB per variables.tf.
  # ---------------------------------------------------------------------------
  ebs_options {
    ebs_enabled = true
    volume_type = "gp3"
    volume_size = var.opensearch_volume_size
  }

  # ---------------------------------------------------------------------------
  # VPC integration -- private-subnet-only deployment.
  #
  # MANDATORY per AAP Section 0.6.6: the domain MUST NOT be publicly
  # accessible. Provisioning the domain with vpc_options creates one
  # ENI per subnet (so the domain endpoint resolves to private IPs)
  # and disables the public endpoint entirely.
  #
  # subnet_ids = data.aws_subnets.private.ids (operator-provisioned
  # private subnets, validated by variables.tf to span >= 2 AZs).
  # security_group_ids = [aws_security_group.opensearch.id] (the SG
  # defined in Section 2 above; VPC-CIDR ingress).
  # ---------------------------------------------------------------------------
  vpc_options {
    subnet_ids         = data.aws_subnets.private.ids
    security_group_ids = [aws_security_group.opensearch.id]
  }

  # ---------------------------------------------------------------------------
  # Encryption at rest -- MANDATORY (AAP Section 0.6.6 + Section 0.7.1).
  #
  # All domain data, snapshots, and underlying EBS volumes are
  # encrypted with the CardDemo primary CMK (aws_kms_key.carddemo
  # from kms.tf). The KMS key policy in kms.tf grants the
  # es.amazonaws.com service principal the necessary kms:Decrypt /
  # kms:GenerateDataKey / kms:CreateGrant / kms:DescribeKey actions
  # (see kms.tf Statement 10 "AllowOpenSearch").
  # ---------------------------------------------------------------------------
  encrypt_at_rest {
    enabled    = true
    kms_key_id = aws_kms_key.carddemo.arn
  }

  # ---------------------------------------------------------------------------
  # Node-to-node encryption -- MANDATORY.
  #
  # TLS within the cluster encrypts every inter-node packet (shard
  # replication, master election, peer discovery). Required by the
  # AWS service contract when advanced_security_options.enabled is
  # true (fine-grained access control); also mandated by AAP
  # Section 0.6.6 for PCI-DSS data-in-transit compliance.
  # ---------------------------------------------------------------------------
  node_to_node_encryption {
    enabled = true
  }

  # ---------------------------------------------------------------------------
  # Domain endpoint options -- HTTPS only, TLS 1.2+ with PFS.
  #
  # enforce_https = true rejects plaintext HTTP at the load balancer.
  # tls_security_policy = Policy-Min-TLS-1-2-PFS-2023-10 enforces:
  #   * TLS minimum protocol version 1.2 (no TLS 1.0 / 1.1)
  #   * Perfect Forward Secrecy cipher suites only (ECDHE / DHE)
  #   * 2023-10 baseline -- the latest AWS-curated PFS policy at AAP
  #     composition time; aligns with PCI-DSS Requirement 4 and the
  #     AAP Section 0.6.6 TLS 1.2+ mandate.
  # custom_endpoint_enabled = false -- the auto-generated domain
  # endpoint (carddemo-<env>-<random>.us-east-1.es.amazonaws.com) is
  # sufficient; a custom endpoint would add ACM certificate management
  # without functional benefit for an internal VPC domain.
  # ---------------------------------------------------------------------------
  domain_endpoint_options {
    enforce_https           = true
    tls_security_policy     = "Policy-Min-TLS-1-2-PFS-2023-10"
    custom_endpoint_enabled = false
  }

  # ---------------------------------------------------------------------------
  # Advanced security options -- fine-grained access control (FGAC).
  #
  # enabled = true activates the per-index / per-document / per-field
  # access-control engine. internal_user_database_enabled = true uses
  # the OpenSearch built-in user database (vs. SAML / Cognito); the
  # master user (carddemo_admin) bootstraps the role hierarchy.
  # Subsequent role mappings are managed by the application or
  # operators via the Dashboards UI / API.
  #
  # master_user_password is sourced from Secrets Manager (NEVER
  # hardcoded). The jsondecode() call extracts the password field
  # from the JSON envelope written by aws_secretsmanager_secret_version
  # .opensearch_master.secret_string above (Section 1).
  #
  # Dependency order (acyclic):
  #   1. random_password.opensearch_master      (no deps)
  #   2. aws_secretsmanager_secret_version.opensearch_master
  #         secret_string = {username, password = random_password.result}
  #         depends on (1)
  #   3. aws_opensearch_domain.carddemo
  #         master_user_password = jsondecode(version.secret_string).password
  #         depends on (2)
  #
  # The secret_string deliberately OMITS the domain endpoint (see
  # Section 1) to keep this chain acyclic; the endpoint is published
  # separately via outputs.tf for ECS task-definition consumption.
  # ---------------------------------------------------------------------------
  advanced_security_options {
    enabled                        = true
    internal_user_database_enabled = true

    master_user_options {
      master_user_name     = "carddemo_admin"
      master_user_password = jsondecode(aws_secretsmanager_secret_version.opensearch_master.secret_string)["password"]
    }
  }

  # ---------------------------------------------------------------------------
  # Log publishing -- four log groups streamed to CloudWatch.
  #
  # Each log type emits to the same CloudWatch log group
  # (aws_cloudwatch_log_group.opensearch from cloudwatch.tf, KMS-CMK
  # encrypted, var.cloudwatch_log_retention_days retention). Operators
  # can subscribe selectively per log type via CloudWatch Logs
  # Insights queries.
  # ---------------------------------------------------------------------------

  # Slow indexing operations (writes that exceed the configured
  # threshold; default 1s). Critical for diagnosing ingestion
  # regressions.
  log_publishing_options {
    cloudwatch_log_group_arn = aws_cloudwatch_log_group.opensearch.arn
    log_type                 = "INDEX_SLOW_LOGS"
    enabled                  = true
  }

  # Slow search operations (queries that exceed the configured
  # threshold; default 1s). Critical for diagnosing query regressions.
  log_publishing_options {
    cloudwatch_log_group_arn = aws_cloudwatch_log_group.opensearch.arn
    log_type                 = "SEARCH_SLOW_LOGS"
    enabled                  = true
  }

  # OpenSearch server-side warnings / errors (rebalance failures,
  # shard relocation issues, disk-space pressure). Critical for
  # operational observability.
  log_publishing_options {
    cloudwatch_log_group_arn = aws_cloudwatch_log_group.opensearch.arn
    log_type                 = "ES_APPLICATION_LOGS"
    enabled                  = true
  }

  # Fine-grained access control audit log -- every authenticated
  # request (PCI-DSS Requirement 10 access-audit trail). MANDATORY
  # per AAP Section 0.6.6.
  log_publishing_options {
    cloudwatch_log_group_arn = aws_cloudwatch_log_group.opensearch.arn
    log_type                 = "AUDIT_LOGS"
    enabled                  = true
  }

  # ---------------------------------------------------------------------------
  # Access policies -- IAM-based access control for the ECS task role.
  #
  # The rendered JSON from data.aws_iam_policy_document.opensearch_access
  # (Section 3) restricts HTTP access to the ECS task role principal
  # only. Combined with the network-layer restriction (VPC-internal
  # + SG ingress) this enforces defense-in-depth access control.
  # NEVER Principal "*" -- explicitly rejected per AAP Section 0.6.6.
  # ---------------------------------------------------------------------------
  access_policies = data.aws_iam_policy_document.opensearch_access.json

  # ---------------------------------------------------------------------------
  # Auto-tune -- prod only.
  #
  # AWS-managed JVM heap / GC / queue tuning. ENABLED in prod (where
  # workload patterns stabilize and auto-tune's recommendations have
  # the most leverage); DISABLED in dev (where the workload is bursty
  # and the cost of auto-tune's maintenance windows is not justified).
  #
  # rollback_on_disable = "NO_ROLLBACK" preserves the current tuned
  # configuration if auto-tune is later disabled, rather than
  # reverting to AWS defaults (which would cause a service window).
  # ---------------------------------------------------------------------------
  auto_tune_options {
    desired_state       = var.environment == "prod" ? "ENABLED" : "DISABLED"
    rollback_on_disable = "NO_ROLLBACK"
  }

  # ---------------------------------------------------------------------------
  # Snapshots -- daily AWS-managed automated snapshots at 03:00 UTC.
  #
  # Every OpenSearch domain receives AWS-managed automated snapshots
  # (cannot be disabled). The start hour aligns with the RDS automated
  # backup window and avoids overlap with the end-of-day batch
  # pipeline (POSTTRAN -> INTCALC -> COMBTRAN -> CREASTMT/TRANREPT
  # from app/jcl/POSTTRAN.jcl typically completes by 02:00 UTC).
  # ---------------------------------------------------------------------------
  snapshot_options {
    automated_snapshot_start_hour = 3
  }

  tags = merge(local.common_tags, {
    Name    = "carddemo-${var.environment}-opensearch"
    Purpose = "Amazon OpenSearch domain - audit trail + CloudTrail event indexing (AAP Section 0.6.6)"
  })

  # ---------------------------------------------------------------------------
  # Dependency wiring -- explicit depends_on for resources Terraform
  # cannot infer from attribute references.
  #
  # The domain depends on the CardDemo CMK's key policy being applied
  # (kms_key_policy attached via aws_kms_key_policy in kms.tf -- if
  # introduced as a separate resource) BEFORE the domain is created,
  # otherwise the OpenSearch service's call to kms:GenerateDataKey
  # would fail with AccessDenied. The aws_kms_key.carddemo.arn
  # attribute reference in encrypt_at_rest.kms_key_id provides the
  # implicit dependency, so an explicit depends_on is not required.
  # ---------------------------------------------------------------------------
}
