###############################################################################
# infrastructure/terraform/variables.tf
#
# Terraform input variables for the CardDemo AWS infrastructure module.
#
# Purpose:
#   Declares every input variable consumed by the sibling .tf files in this
#   folder (main.tf, kms.tf, iam.tf, secrets.tf, rds.tf, elasticache.tf,
#   msk.tf, s3.tf, alb.tf, ecr.tf, ecs.tf, batch.tf, glue.tf,
#   stepfunctions.tf, waf.tf, shield.tf, macie.tf, cloudtrail.tf,
#   opensearch.tf, cloudwatch.tf, outputs.tf). This is one of the three
#   foundational files (main.tf, variables.tf, outputs.tf) that establishes
#   the configuration contract for the entire Terraform module.
#
# Conventions (per AAP §0.3.1 and the folder summary in ../README.md):
#   * snake_case variable names throughout (HCL idiom).
#   * Every variable declares an explicit `type`; none rely on the implicit
#     `any` type that Terraform falls back to when the type is omitted.
#   * Every variable carries a human-readable `description` consumed by
#     `terraform output`, `terraform-docs`, and IDE tooltips.
#   * Variables that MUST be supplied by the operator have no `default`
#     (e.g., `environment`, `vpc_id`, `private_subnet_ids`,
#     `public_subnet_ids`, `alb_acm_certificate_arn`); omitting them causes
#     `terraform plan` / `terraform apply` to fail with a clear prompt.
#   * `validation` blocks guard critical inputs (region format, environment
#     enum, multi-AZ subnet count, KMS deletion window, retention windows).
#   * No secrets are defaulted here — credentials are generated by
#     `random_password` resources and stored in AWS Secrets Manager
#     (per AAP §0.7.1).
#
# References:
#   * AAP §0.7.2 — non-sensitive environment variable contract surfaced to
#     the Spring Boot application (AWS_REGION, ECS_CLUSTER_NAME,
#     RDS_SECRET_ARN, KMS_KEY_ARN, MSK_BOOTSTRAP_SERVERS, S3_OUTPUT_BUCKET,
#     OPENSEARCH_ENDPOINT).
#   * AAP §0.6.1 — BigDecimal precision requires PostgreSQL NUMERIC; pinned
#     to PostgreSQL 16.x.
#   * AAP §0.6.2 — RDS Multi-AZ; ElastiCache Redis cache-aside pattern.
#   * AAP §0.6.3 — Step Functions + AWS Batch replace JCL job streams.
#   * AAP §0.6.5 — MSK topic partitioning by account ID; default partition
#     count >= producer concurrency.
#   * AAP §0.6.6 — PCI-DSS controls: TLS 1.2+, KMS CMKs, Secrets Manager,
#     CloudTrail, OpenSearch, Macie.
#   * Folder summary — mandatory tags: Project=CardDemo, Environment=<env>,
#     Owner=blitzy-sandbox, ManagedBy=Terraform.
#
# Operator workflow:
#   Provide a terraform.tfvars file with at minimum:
#     environment              = "dev"
#     vpc_id                   = "vpc-xxxxxxxx"
#     private_subnet_ids       = ["subnet-aaa", "subnet-bbb"]
#     public_subnet_ids        = ["subnet-ccc", "subnet-ddd"]
#     alb_acm_certificate_arn  = "arn:aws:acm:us-east-1:...:certificate/..."
#   Then run `terraform plan` and `terraform apply` from this directory.
###############################################################################

###############################################################################
# Section 1 — Core variables (region, environment, project, owner)
#
# These variables establish the deployment context and feed the mandatory
# tag set (`local.common_tags` in main.tf):
#   Project    = var.project_name   (default: "CardDemo")
#   Environment= var.environment    (one of dev | staging | prod)
#   Owner      = var.owner_tag      (default: "blitzy-sandbox")
#   ManagedBy  = "Terraform"        (hard-coded in main.tf)
###############################################################################

variable "aws_region" {
  description = "Primary AWS region for all CardDemo resources. Must be a valid AWS region identifier (e.g., us-east-1, eu-west-2, ap-southeast-1). Maps to the AWS_REGION environment variable consumed by the Spring Boot application per AAP §0.7.2."
  type        = string
  default     = "us-east-1"

  validation {
    condition     = can(regex("^[a-z]{2}-[a-z]+-[0-9]$", var.aws_region))
    error_message = "aws_region must be a valid AWS region identifier in the format <continent>-<area>-<index> (e.g., us-east-1, eu-west-2, ap-southeast-1)."
  }
}

variable "environment" {
  description = "Deployment environment. Drives resource naming (carddemo-<env>-<resource>), tagging (Environment=<env>), and per-environment policy gates such as deletion protection and Multi-AZ. Must be one of: dev, staging, prod."
  type        = string

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of: dev, staging, prod."
  }
}

variable "project_name" {
  description = "Project name applied as the Project tag on every resource. Per the folder summary in ../README.md, this MUST be 'CardDemo' for traceability back to the AAP. Overriding is reserved for parallel test deployments under a different project namespace."
  type        = string
  default     = "CardDemo"
}

variable "owner_tag" {
  description = "Owner tag applied to every resource. Per the folder summary in ../README.md, the default 'blitzy-sandbox' aligns with the demo deployment account. Override for production deployments owned by a specific platform team."
  type        = string
  default     = "blitzy-sandbox"
}

###############################################################################
# Section 2 — Network variables (VPC + subnets, bring-your-own-VPC pattern)
#
# CardDemo follows a bring-your-own-VPC pattern: the operator pre-provisions
# the VPC, public subnets, private subnets, NAT gateways, and route tables.
# This Terraform module references those resources by ID and provisions only
# the workload (security groups, RDS, ElastiCache, MSK, ECS, ALB, etc.).
#
# Subnet layout requirements:
#   * private_subnet_ids: at least 2 subnets across at least 2 AZs for RDS
#     Multi-AZ, ElastiCache Multi-AZ, MSK across-AZ broker placement, and
#     ECS task placement.
#   * public_subnet_ids: at least 2 subnets across at least 2 AZs for the
#     internet-facing ALB.
###############################################################################

variable "vpc_id" {
  description = "VPC ID where all CardDemo resources are deployed. Bring-your-own-VPC: the VPC must already exist and have DNS resolution + DNS hostnames enabled. No default — the operator must supply this value via terraform.tfvars or -var."
  type        = string

  validation {
    condition     = can(regex("^vpc-[0-9a-f]{8,17}$", var.vpc_id))
    error_message = "vpc_id must be a valid VPC identifier (e.g., vpc-0123456789abcdef0)."
  }
}

variable "private_subnet_ids" {
  description = "Private subnet IDs hosting workloads that should not be directly reachable from the internet: RDS instances, ElastiCache replication groups, MSK broker ENIs, ECS Fargate tasks, AWS Batch compute environments, AWS Glue jobs, and Lambda functions. Must contain at least 2 subnets across at least 2 Availability Zones to satisfy RDS / ElastiCache / MSK Multi-AZ requirements per AAP §0.6.2."
  type        = list(string)

  validation {
    condition     = length(var.private_subnet_ids) >= 2
    error_message = "At least 2 private subnets across at least 2 Availability Zones are required for RDS Multi-AZ, ElastiCache replication groups, and MSK broker placement."
  }
}

variable "public_subnet_ids" {
  description = "Public subnet IDs hosting only the internet-facing Application Load Balancer. Must contain at least 2 subnets across at least 2 Availability Zones for ALB high availability. Workloads (ECS tasks, batch jobs, databases) are NEVER placed in public subnets."
  type        = list(string)

  validation {
    condition     = length(var.public_subnet_ids) >= 2
    error_message = "At least 2 public subnets across at least 2 Availability Zones are required for the Application Load Balancer."
  }
}

###############################################################################
# Section 3 — KMS variables
#
# AWS KMS customer-managed keys (CMKs) provide envelope encryption for every
# at-rest data store: RDS, S3, ElastiCache, CloudWatch Logs, MSK, OpenSearch.
# Per AAP §0.6.6 and §0.7.1, all CardDemo data at rest must be encrypted
# with KMS CMKs (not the AWS-managed default keys).
###############################################################################

variable "kms_deletion_window_in_days" {
  description = "Pending deletion window for KMS keys before permanent deletion. AWS allows 7-30 days; 30 (default) maximizes recovery time for accidental key scheduling deletes. Production should never lower this below the regulatory data-retention window."
  type        = number
  default     = 30

  validation {
    condition     = var.kms_deletion_window_in_days >= 7 && var.kms_deletion_window_in_days <= 30
    error_message = "kms_deletion_window_in_days must be between 7 and 30 (AWS-imposed bounds)."
  }
}

###############################################################################
# Section 4 — RDS variables
#
# RDS PostgreSQL Multi-AZ replaces the legacy VSAM KSDS clusters per
# AAP §0.6.2. PostgreSQL 16.x is mandated because:
#   * AAP §0.6.1 requires NUMERIC(precision, scale) for monetary fields
#     (preserving COBOL PIC S9(n)V99 semantics with BigDecimal arithmetic)
#     — PostgreSQL NUMERIC is arbitrary-precision and matches COBOL decimal
#     arithmetic exactly.
#   * AAP §0.7.1 requires @Transactional with READ_COMMITTED isolation as
#     the floor — PostgreSQL 16 defaults to READ_COMMITTED.
###############################################################################

variable "rds_instance_class" {
  description = "RDS instance class. Recommendations: db.t3.medium for dev (~2 vCPU / 4 GiB), db.m6g.large for staging (~2 vCPU / 8 GiB), db.r6g.xlarge or larger for prod (~4 vCPU / 32 GiB). Graviton (g) classes offer the best price/performance for PostgreSQL workloads."
  type        = string
  default     = "db.t3.medium"
}

variable "rds_engine_version" {
  description = "PostgreSQL engine version. Pinned to 16.x because PostgreSQL 16 NUMERIC arbitrary precision exactly preserves COBOL PIC S9(n)V99 / COMP-3 decimal arithmetic (AAP §0.6.1). Patch the minor version (e.g., 16.4 -> 16.5) through this variable when AWS publishes security updates."
  type        = string
  default     = "16.4"
}

variable "rds_allocated_storage" {
  description = "Initial RDS allocated storage in gigabytes. Storage autoscaling expands up to rds_max_allocated_storage. 100 GiB is sufficient for dev / staging; prod should size based on observed transaction volume and the 35-day automated backup retention window."
  type        = number
  default     = 100
}

variable "rds_max_allocated_storage" {
  description = "RDS storage autoscaling cap in gigabytes. Once allocated storage hits this ceiling, RDS stops autoscaling and the operator must intervene. Set high enough to absorb growth between maintenance windows."
  type        = number
  default     = 500
}

variable "rds_backup_retention_period" {
  description = "RDS automated backup retention in days. Per AAP §0.7.2, the default is 35 days (maximum) with point-in-time recovery. Reducing below 7 forfeits compliance-grade recoverability."
  type        = number
  default     = 35

  validation {
    condition     = var.rds_backup_retention_period >= 7 && var.rds_backup_retention_period <= 35
    error_message = "rds_backup_retention_period must be between 7 and 35 days (per AAP §0.7.2 / PCI-DSS data-retention floor)."
  }
}

variable "rds_db_name" {
  description = "Initial PostgreSQL database name created at first boot. Application schemas (managed by Flyway in src/main/resources/db/migration/) are applied inside this database. Lowercase letters and digits only; PostgreSQL identifier rules apply."
  type        = string
  default     = "carddemo"
}

variable "rds_master_username" {
  description = "RDS master username. The master password is NEVER set via Terraform variables — it is generated at apply time by a `random_password` resource and stored in AWS Secrets Manager (per AAP §0.7.1). The username is metadata only and may be visible in logs / console."
  type        = string
  default     = "carddemo_admin"
}

variable "rds_multi_az" {
  description = "Enable RDS Multi-AZ deployment for high availability and synchronous standby per AAP §0.6.2. Required for prod; optional for dev to save cost. When true, RDS maintains a hot standby in a second AZ and fails over automatically on primary failure."
  type        = bool
  default     = true
}

variable "rds_deletion_protection" {
  description = "Enable RDS deletion protection. When true, neither the AWS console nor `terraform destroy` can delete the RDS instance without first toggling this flag off. MUST be true for prod to prevent accidental data loss; may be false in dev for rapid teardown."
  type        = bool
  default     = true
}

variable "rds_rotation_days" {
  description = "Rotation cadence (days) for the RDS master credential stored in AWS Secrets Manager. 30 days satisfies PCI-DSS Requirement 8.6.3 (90-day max) with margin. Rotation is performed by a Lambda function provisioned in secrets.tf and triggers @RefreshScope reloads in the Spring Boot application without restart per AAP §0.6.4."
  type        = number
  default     = 30
}

###############################################################################
# Section 5 — ElastiCache (Redis) variables
#
# Per AAP §0.7.1, ElastiCache Redis serves the cache-aside pattern for
# high-frequency account balance reads, with TTL aligned to transaction
# frequency and allkeys-lru eviction. Multi-AZ is achieved by deploying at
# least 2 cache clusters in a single replication group across at least 2 AZs.
###############################################################################

variable "redis_node_type" {
  description = "ElastiCache Redis node instance class. Recommendations: cache.t3.micro for dev (~0.5 GiB), cache.t3.medium for staging (~3 GiB), cache.r6g.large or larger for prod (~13 GiB). Graviton (g) classes offer the best price/performance for Redis."
  type        = string
  default     = "cache.t3.micro"
}

variable "redis_num_cache_clusters" {
  description = "Number of Redis nodes (primary + replicas) in the replication group. >= 2 enables automatic failover and Multi-AZ resilience; 1 is acceptable for dev / cost-sensitive deployments but provides no HA."
  type        = number
  default     = 2

  validation {
    condition     = var.redis_num_cache_clusters >= 1
    error_message = "redis_num_cache_clusters must be at least 1; values >= 2 are required for Multi-AZ automatic failover."
  }
}

variable "redis_engine_version" {
  description = "Redis engine version. 7.x is the current recommended major version; ElastiCache continues to support 6.x for legacy workloads. Spring Data Redis 3.x (via spring-boot-starter-data-redis in pom.xml) is compatible with Redis 6.x and 7.x."
  type        = string
  default     = "7.1"
}

variable "redis_port" {
  description = "Redis TCP listener port. 6379 is the Redis default; change only if a competing service occupies the port in the VPC. The application reads the port via the spring.data.redis.port configuration property."
  type        = number
  default     = 6379
}

###############################################################################
# Section 6 — MSK (Managed Streaming for Kafka) variables
#
# Per AAP §0.6.5, MSK Kafka topics carry inter-service transaction events:
#   * transaction.posted   (published by TransactionAddService, BillPaymentService)
#   * account.updated      (published by AccountUpdateService, BillPaymentService,
#                           InterestCalculationService)
#   * ledger.balanced      (published by end-of-day reconciliation)
#   * report.requested     (published by ReportSubmissionService; consumed by
#                           the Step Functions trigger Lambda)
#
# Partition key = account ID (11-digit, zero-padded). With partitions >=
# producer concurrency, per-account ordering is guaranteed end-to-end.
###############################################################################

variable "msk_kafka_version" {
  description = "Apache Kafka broker version supported by MSK. 3.6.0 is the current MSK-recommended version with KRaft mode (no Zookeeper). Spring Kafka 3.x in pom.xml is compatible with Kafka 2.4+ broker versions."
  type        = string
  default     = "3.6.0"
}

variable "msk_broker_instance_type" {
  description = "MSK broker instance class. Recommendations: kafka.t3.small for dev (~2 vCPU / 2 GiB), kafka.m5.large for staging (~2 vCPU / 8 GiB), kafka.m7g.large or larger for prod. Graviton (m7g) classes offer the best price/performance."
  type        = string
  default     = "kafka.t3.small"
}

variable "msk_number_of_broker_nodes" {
  description = "Total number of broker nodes across the MSK cluster. MUST be a multiple of the AZ count (e.g., 3 brokers across 3 AZs = 1 per AZ). Minimum 3 brokers for prod to support replication factor 3 with one AZ failure."
  type        = number
  default     = 3
}

variable "msk_ebs_volume_size" {
  description = "Per-broker EBS volume size in gigabytes. Sized to absorb the rolling 7-day retention window of all topics + safety margin. Default 100 GiB is sufficient for dev; prod should size based on observed message volume."
  type        = number
  default     = 100
}

variable "msk_topic_partitions" {
  description = "Default partition count for transaction-event topics. Must be >= producer concurrency for the topic's primary producer (per AAP §0.6.5: 12 partitions for a 12-task ECS service). Higher partition counts increase parallelism but consume broker resources."
  type        = number
  default     = 12
}

variable "msk_topic_replication_factor" {
  description = "Default replication factor for transaction-event topics. 3 is the prod recommendation (ISR = 2 with one AZ failure). May be reduced to 2 in dev to save broker capacity; never go below 2 in any environment that values durability."
  type        = number
  default     = 3
}

###############################################################################
# Section 7 — S3 lifecycle variables
#
# S3 versioned buckets replace GDG sequential output generations per
# AAP §0.6.2. Lifecycle policies transition old object versions to Glacier
# for cost optimisation and eventually expire them per the regulatory
# retention window.
###############################################################################

variable "s3_lifecycle_glacier_days" {
  description = "Days after which non-current S3 object versions transition to Glacier (or Glacier Deep Archive) storage class. 90 days is the default; aligns with quarterly access patterns for batch output reports and statements."
  type        = number
  default     = 90
}

variable "s3_lifecycle_expiration_days" {
  description = "Days after which non-current S3 object versions are permanently expired. Default 2555 days (7 years) satisfies the longest financial-services regulatory retention window. Reduce only if the retention policy explicitly permits."
  type        = number
  default     = 2555
}

###############################################################################
# Section 8 — ECS Fargate variables
#
# Per AAP §0.1.1, Spring Boot tasks run on ECS Fargate behind an ALB, with
# auto-scaling driven by CPU utilisation and MSK consumer lag.
###############################################################################

variable "ecs_task_cpu" {
  description = "ECS task CPU units (1 vCPU = 1024 units). Fargate accepts only a discrete set: 256, 512, 1024, 2048, 4096, 8192, 16384. Each value pairs with a defined memory range — see ecs_task_memory."
  type        = number
  default     = 1024
}

variable "ecs_task_memory" {
  description = "ECS task memory in megabytes. Must pair with ecs_task_cpu per the Fargate compatibility matrix (e.g., 1024 CPU pairs with 2048-8192 MB). Spring Boot 3.x + Spring Kafka + Spring Batch comfortably fit in 2048 MB for the default 1024 CPU."
  type        = number
  default     = 2048
}

variable "ecs_desired_count" {
  description = "Initial desired count of ECS tasks for the application service. Auto-scaling adjusts within ecs_min_capacity .. ecs_max_capacity based on observed load."
  type        = number
  default     = 2
}

variable "ecs_min_capacity" {
  description = "Auto-scaling minimum task count. Must be >= 2 for production to survive a single-AZ failure with at least one healthy task per remaining AZ."
  type        = number
  default     = 2
}

variable "ecs_max_capacity" {
  description = "Auto-scaling maximum task count. Sized to absorb peak traffic plus safety margin. Account-level Fargate vCPU quotas may impose an upper bound."
  type        = number
  default     = 10
}

variable "app_image_tag" {
  description = "Container image tag to deploy from ECR. NEVER use 'latest' in prod — the CI/CD pipeline (../.github/workflows/deploy.yml) injects an immutable image digest. The 'latest' default is safe only for local development against a registry that always carries a latest pointer."
  type        = string
  default     = "latest"
}

variable "app_port" {
  description = "Application listener port inside the container. Maps to the Spring Boot `server.port` property (see src/main/resources/application.yml). The ALB target group forwards traffic to this port."
  type        = number
  default     = 8080
}

###############################################################################
# Section 9 — ALB variables
#
# Per AAP §0.6.6, the ALB enforces TLS 1.2+ via an HTTPS listener bound to
# an ACM certificate. AWS WAF (waf.tf) attaches to the ALB; Shield Standard
# is enabled by default and Shield Advanced is optional (shield.tf).
###############################################################################

variable "alb_acm_certificate_arn" {
  description = "ACM certificate ARN for the ALB HTTPS listener. Must already exist in the same region as the ALB (or be provisioned alongside this configuration by an aws_acm_certificate resource). No default — the operator must supply this value."
  type        = string

  validation {
    condition     = can(regex("^arn:aws[a-zA-Z-]*:acm:[a-z]{2}-[a-z]+-[0-9]:[0-9]{12}:certificate/[a-f0-9-]+$", var.alb_acm_certificate_arn))
    error_message = "alb_acm_certificate_arn must be a valid ACM certificate ARN (e.g., arn:aws:acm:us-east-1:123456789012:certificate/abcd-...)."
  }
}

variable "alb_idle_timeout" {
  description = "ALB idle timeout in seconds. 60 is the AWS default and adequate for typical REST request/response cycles. Increase for long-polling or large file streaming."
  type        = number
  default     = 60
}

variable "alb_access_logs_enabled" {
  description = "Enable ALB access logging to an S3 logs bucket. Required for PCI-DSS audit per AAP §0.6.6. The destination bucket is provisioned by s3.tf with SSE-KMS and the standard ALB log delivery policy."
  type        = bool
  default     = true
}

###############################################################################
# Section 10 — ECR variables
#
# ECR holds the application container image. Lifecycle policies keep the
# repository tidy by capping the number of retained tagged images and
# expiring untagged images.
###############################################################################

variable "ecr_keep_n_images" {
  description = "Number of most-recently-pushed tagged images to retain in ECR. Older tagged images are deleted by the lifecycle policy. 30 retains roughly one month of daily deploys."
  type        = number
  default     = 30
}

variable "ecr_untagged_days" {
  description = "Days after which untagged ECR images expire (lifecycle policy). 7 days catches CI builds that produced an image but failed before tagging."
  type        = number
  default     = 7
}

variable "ecr_force_delete" {
  description = "Allow `terraform destroy` to delete the ECR repository even when it contains images. MUST be false in prod to prevent accidental image loss; true is acceptable in dev for rapid teardown."
  type        = bool
  default     = false
}

###############################################################################
# Section 11 — AWS Batch variables
#
# Per AAP §0.6.3, AWS Batch on Fargate runs the Spring Batch jars
# orchestrated by Step Functions. Each Batch job definition references a
# container image (built from the same Dockerfile as the ECS service) and a
# compute environment scoped to private subnets.
###############################################################################

variable "batch_max_vcpus" {
  description = "Maximum vCPUs the AWS Batch Fargate compute environment may consume across concurrent jobs. 16 supports up to 16 concurrent jobs at batch_job_vcpu=1."
  type        = number
  default     = 16
}

variable "batch_job_vcpu" {
  description = "Per-job container vCPU on Fargate. 1 vCPU is sufficient for the Spring Batch job definitions in src/main/java/com/awsm2/carddemo/batch/. Increase to 2 or 4 if a specific job becomes CPU-bound."
  type        = number
  default     = 1
}

variable "batch_job_memory" {
  description = "Per-job container memory in megabytes on Fargate. 2048 MiB matches the ECS service default. Must be paired with batch_job_vcpu per the Fargate compatibility matrix."
  type        = number
  default     = 2048
}

###############################################################################
# Section 12 — AWS Glue variables
#
# Per AAP §0.6.2, AWS Glue Spark jobs perform bulk-load ETL from S3-staged
# ASCII fixtures (app/data/ASCII/*.txt) into RDS PostgreSQL. The Glue jobs
# are referenced by the file-provisioning Step Functions state machine
# (src/main/resources/stepfunctions/file-provisioning.asl.json).
###############################################################################

variable "glue_worker_type" {
  description = "AWS Glue Spark worker type. G.1X (4 vCPU / 16 GB) is the default; G.2X (8 vCPU / 32 GB) and G.4X (16 vCPU / 64 GB) are available for larger workloads. Choose based on the ASCII fixture size and Spark parallelism requirements."
  type        = string
  default     = "G.1X"
}

variable "glue_number_of_workers" {
  description = "Number of Spark workers per Glue job. Higher values parallelise the bulk load but cost more. 2 workers are sufficient for the CardDemo ASCII fixture sizes (single-digit MB per file)."
  type        = number
  default     = 2
}

variable "glue_crawler_enabled" {
  description = "Enable an AWS Glue Crawler to populate the Glue Data Catalog with the schema of the S3-staged ASCII fixtures. Optional; useful when downstream Athena queries are required for ad-hoc analysis."
  type        = bool
  default     = false
}

###############################################################################
# Section 13 — Step Functions variables
#
# Per AAP §0.6.3, Step Functions state machines orchestrate:
#   * src/main/resources/stepfunctions/eod-batch-pipeline.asl.json
#     — daily end-of-day pipeline (POSTTRAN → INTCALC → COMBTRAN → Parallel
#       { CREASTMT, TRANREPT }).
#   * src/main/resources/stepfunctions/file-provisioning.asl.json
#     — one-time / on-demand bulk data loading.
###############################################################################

variable "stepfunctions_logging_enabled" {
  description = "Enable Step Functions ALL-level logging to CloudWatch Logs. Required for PCI-DSS audit (per AAP §0.6.6) so every state transition is captured. Disabling reduces cost in dev but forfeits audit trail."
  type        = bool
  default     = true
}

variable "eod_scheduled_enabled" {
  description = "Schedule the daily end-of-day batch pipeline via EventBridge Scheduler. When true, EventBridge invokes the eod-batch-pipeline state machine on a cron schedule (default 23:00 UTC, configured in stepfunctions.tf). Set to false in dev to avoid noisy nightly runs."
  type        = bool
  default     = false
}

###############################################################################
# Section 14 — OpenSearch variables
#
# Per AAP §0.6.6, OpenSearch indexes CloudTrail events and application
# audit logs for searchable retention, fraud investigation, and regulatory
# queries. The domain is provisioned in private subnets only and accessed
# from the ECS tasks via VPC endpoint.
###############################################################################

variable "opensearch_instance_type" {
  description = "OpenSearch data node instance class. t3.small.search (~2 vCPU / 2 GiB) is the dev default; r6g.large.search or larger is recommended for prod to absorb CloudTrail + audit log ingestion."
  type        = string
  default     = "t3.small.search"
}

variable "opensearch_instance_count" {
  description = "Number of OpenSearch data nodes. >= 2 enables zone awareness (data replicated across at least 2 AZs) for HA. Higher counts increase ingestion throughput and search latency budget."
  type        = number
  default     = 2
}

variable "opensearch_volume_size" {
  description = "Per-node EBS volume size for OpenSearch (GiB). Sized to hold the indexed retention window plus replicas. 100 GiB is sufficient for dev; prod should size from observed ingestion rate."
  type        = number
  default     = 100
}

variable "opensearch_rotation_days" {
  description = "Rotation cadence (days) for the OpenSearch fine-grained-access master credential stored in AWS Secrets Manager. 90 days satisfies PCI-DSS Requirement 8.6.3."
  type        = number
  default     = 90
}

###############################################################################
# Section 15 — AWS Shield Advanced variable
#
# Shield Standard is enabled by default on every ALB (no Terraform action
# required). Shield Advanced is a paid subscription (~$3,000/month per
# account) that provides L7 DDoS protection, incident response, and cost
# protection. Disabled by default; enable only for production.
###############################################################################

variable "shield_advanced_enabled" {
  description = "Subscribe to AWS Shield Advanced and protect the ALB. Approximately $3,000 USD per month per account (12-month minimum commitment); enable only for production deployments that require L7 DDoS protection and the AWS Shield Response Team (SRT) incident response."
  type        = bool
  default     = false
}

###############################################################################
# Section 16 — GitHub Actions OIDC federation variables
#
# To avoid long-lived AWS access keys in GitHub, the CI/CD pipeline
# (../.github/workflows/*.yml) assumes an IAM role via OIDC federation.
# The OIDC provider and the deploy role are provisioned by iam.tf and
# trusted only for the configured repository.
###############################################################################

variable "github_oidc_enabled" {
  description = "Provision the GitHub Actions OIDC identity provider and the matching deploy IAM role. When false, the OIDC resources are not created and the CI/CD pipeline must authenticate via another mechanism (not recommended)."
  type        = bool
  default     = true
}

variable "github_repo_owner" {
  description = "GitHub repository owner (user or organization). Used in the OIDC role trust policy's `sub` claim condition to restrict role assumption to workflow runs originating from this repository. Empty string disables the sub-claim restriction (NOT recommended)."
  type        = string
  default     = ""
}

variable "github_repo_name" {
  description = "GitHub repository name. Used together with github_repo_owner in the OIDC role trust policy's `sub` claim condition (e.g., repo:<owner>/<name>:*). Empty string disables the sub-claim restriction (NOT recommended)."
  type        = string
  default     = ""
}

###############################################################################
# Section 17 — CloudWatch variables
#
# Per AAP §0.6.6, CloudWatch + Container Insights captures ECS task-level
# metrics, logs, and alarms. Spring Actuator metrics are exported via
# Micrometer → CloudWatch under namespace `CardDemo`.
###############################################################################

variable "cloudwatch_log_retention_days" {
  description = "Default CloudWatch Logs retention in days for application log groups (ECS, Batch, Step Functions, Glue). 365 days satisfies the PCI-DSS audit log retention floor (1 year). Allowed values: 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 2192, 2557, 2922, 3288, 3653."
  type        = number
  default     = 365
}
