package com.carddemo.repository;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.carddemo.entity.Transaction;

/**
 * Spring Data JPA repository for the {@link Transaction} aggregate — the migrated
 * posted-transaction master originally persisted in the VSAM KSDS {@code TRANSACT}
 * file (copybook {@code CVTRA05Y}, {@code TRAN-RECORD}, 350-byte record, source
 * commit SHA {@code 27d6c6f}).
 *
 * <p>This interface is the idiomatic Spring Data replacement for the legacy VSAM
 * keyed-access model. It backs the online transaction programs — Transaction List
 * ({@code CT00} / {@code COTRN00C}), Transaction View ({@code CT01} /
 * {@code COTRN01C}) and Transaction Add ({@code CT02} / {@code COTRN02C}) — as well
 * as the statement and transaction-detail report batch flows ({@code CBSTM03A} /
 * {@code CBTRN03C}).</p>
 *
 * <h2>VSAM access-path parity</h2>
 * <p>The legacy {@code TRANSACT} cluster exposes one base key plus one alternate
 * index; each maps to a Spring Data access method:</p>
 * <ul>
 *   <li><b>Base KSDS key</b> — {@code KEYS(16 0)} over {@code TRAN-ID PIC X(16)}
 *       (offset&nbsp;0, length&nbsp;16). This is the JPA {@code @Id} ({@code String tranId}),
 *       so unique primary-key reads are served by the inherited
 *       {@link JpaRepository#findById(Object) findById(String)}. Transaction Add
 *       ({@code COTRN02C}) writes new records through the inherited
 *       {@link JpaRepository#save(Object) save(..)}, with the 16-character
 *       {@code TRAN-ID} generated by the service layer.</li>
 *   <li><b>Alternate index</b> {@code TRANSACT.VSAM.AIX} — defined by IDCAMS in
 *       {@code app/jcl/TRANFILE.jcl} / {@code app/jcl/TRANIDX.jcl} as
 *       {@code KEYS(26 304) NONUNIQUEKEY} and annotated "ALTERNATE INDEX ON
 *       PROCESSED TIMESTAMP". Offset&nbsp;304, length&nbsp;26 resolves against the
 *       {@code CVTRA05Y} layout to {@code TRAN-PROC-TS PIC X(26)} (the processing
 *       timestamp) — <em>not</em> the card number. Because the alternate key is
 *       non-unique, its finder returns a {@link List}. See
 *       {@link #findByTranProcTs(String)}.</li>
 * </ul>
 *
 * <p>The Transaction List browse ({@code COTRN00C}) pages through records in
 * {@code TRAN-ID} order, ten rows at a time (the COBOL loop terminates at
 * {@code WS-IDX >= 11}). That paging is expressed by the service layer using the
 * inherited {@link JpaRepository#findAll(Pageable) findAll(Pageable)} with
 * {@code PageRequest.of(page, 10, Sort.by("tranId"))}; no bespoke method is needed
 * here.</p>
 *
 * <h2>Index dependency (not owned here)</h2>
 * <p>For access-path parity with the VSAM alternate index and for efficient
 * card-scoped reads, both the {@code tran_proc_ts} and {@code tran_card_num}
 * columns must be indexed. Those indexes are declared by the Flyway
 * {@code V2__indexes.sql} migration (owned by the database-migration agent) and are
 * intentionally <em>not</em> created here. Under {@code spring.jpa.hibernate.ddl-auto:
 * validate}, this repository operates over the Flyway-managed, non-reserved
 * {@code transaction} table.</p>
 *
 * @see Transaction
 */
@Repository
public interface TransactionRepository extends JpaRepository<Transaction, String> {

    /**
     * Finds every transaction whose processing timestamp equals the supplied value,
     * reproducing lookups through the physical VSAM alternate index
     * {@code TRANSACT.VSAM.AIX} ({@code KEYS(26 304)} over {@code TRAN-PROC-TS}).
     *
     * <p>The alternate index is declared {@code NONUNIQUEKEY}, so multiple
     * transactions may share the same processing timestamp; the result is therefore
     * a {@link List} that is empty when no record matches. The parameter is the
     * 26-character timestamp text ({@code yyyy-mm-dd-hh.mm.ss.ffffff}) preserved
     * verbatim on {@link Transaction#getTranProcTs()} — it is matched exactly, with
     * no wildcard semantics.</p>
     *
     * @param tranProcTs the 26-character {@code TRAN-PROC-TS} processing-timestamp
     *                   text to match exactly; must not be {@code null}
     * @return all matching transactions in no guaranteed order; never {@code null},
     *         possibly empty
     */
    List<Transaction> findByTranProcTs(String tranProcTs);

    /**
     * Returns a page of transactions for a single card number, supporting the
     * statement-generation ({@code CBSTM03A}) and transaction-detail report
     * ({@code CBTRN03C}) flows, which select the transactions belonging to a given
     * card / customer.
     *
     * <p>Although the physical VSAM alternate index is keyed on the processing
     * timestamp, transactions are <em>functionally</em> queried by card number for
     * these statement and report use cases. The parameter matches the 16-character
     * {@code TRAN-CARD-NUM} value carried on {@link Transaction#getTranCardNum()}
     * exactly (no wildcard semantics). The result is paginated so that report and
     * statement processing can consume the rows in bounded chunks.</p>
     *
     * @param tranCardNum the 16-character {@code TRAN-CARD-NUM} card number to match
     *                    exactly; must not be {@code null}
     * @param pageable    the pagination and sort specification; must not be
     *                    {@code null}
     * @return a {@link Page} of matching transactions for the requested slice; never
     *         {@code null}, possibly empty
     */
    Page<Transaction> findByTranCardNum(String tranCardNum, Pageable pageable);
}
