/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.awsm2.carddemo.repository;

import com.awsm2.carddemo.domain.Transaction;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Spring Data JPA repository for the {@link Transaction} entity &mdash; the
 * central financial journal of the CardDemo system.
 *
 * <p><strong>Replaces VSAM cluster:</strong>
 * {@code AWS.M2.CARDDEMO.TRANSACT.VSAM.KSDS} (defined in
 * {@code app/jcl/TRANFILE.jcl} with {@code KEYS(16 0)} &mdash; 16-byte
 * primary key {@code TRAN-ID} at offset 0; {@code RECORDSIZE(350 350)};
 * {@code INDEXED}) plus its alternate index
 * {@code AWS.M2.CARDDEMO.TRANSACT.VSAM.AIX} declared with
 * {@code KEYS(26 304)} &mdash; 26-byte composite key spanning
 * {@code (TRAN-CARD-NUM, TRAN-PROC-TS)}. The Java target replaces the
 * AIX with the PostgreSQL composite secondary index
 * {@code idx_transactions_card_proc_ts} on
 * {@code (tran_card_num, tran_proc_ts)} declared by V005.</p>
 *
 * <p>The COBOL access patterns are:
 * <ul>
 *   <li>random read by 16-character {@code TRAN-ID}
 *       ({@code app/cbl/COTRN01C.cbl} &mdash; transaction-detail
 *       screen);</li>
 *   <li>STARTBR/READPREV to find {@code MAX(TRAN-ID)} for the
 *       "next ID" generation pattern in {@code app/cbl/COTRN02C.cbl}
 *       ({@code TransactionAddService}) and
 *       {@code app/cbl/COBIL00C.cbl} ({@code BillPaymentService});</li>
 *   <li>paged browse by primary key for the {@code COTRN00.bms}
 *       10-row-per-page list ({@code app/cbl/COTRN00C.cbl});</li>
 *   <li>alternate-index browse on {@code (TRAN-CARD-NUM, TRAN-PROC-TS)}
 *       for date-windowed report generation
 *       ({@code app/cbl/CBTRN03C.cbl}) and statement generation
 *       ({@code app/cbl/CBSTM03A.CBL}/{@code CBSTM03B.CBL}).</li>
 * </ul>
 * The PostgreSQL B-tree on the primary key satisfies the random-read and
 * MAX-ID patterns; the composite secondary index
 * {@code idx_transactions_card_proc_ts} declared by V005 replaces the
 * VSAM AIX/PATH and supports the
 * {@link #findByTranCardNumAndTranProcTsBetweenOrderByTranProcTsAsc(String,
 * LocalDateTime, LocalDateTime, Pageable)} derived query.</p>
 *
 * <p><strong>Source copybook:</strong> {@code app/cpy/CVTRA05Y.cpy}
 * ({@code TRAN-RECORD}, RECLN 350; 13 business fields plus a 20-byte
 * trailing {@code FILLER} that has no relational counterpart).</p>
 *
 * <p><strong>Schema:</strong> Flyway migration
 * {@code src/main/resources/db/migration/V005__create_transaction.sql}
 * creates the {@code transactions} table. Hibernate
 * {@code spring.jpa.hibernate.ddl-auto: validate} verifies that the
 * {@link Transaction} mapping aligns with the V005 DDL at application
 * startup.</p>
 *
 * <h2>Application-Generated Transaction IDs (AAP &sect;0.6.2)</h2>
 *
 * <p>Per AAP &sect;0.6.2 and the CP4 review, transaction IDs are
 * generated by the <strong>MAX-TRAN-ID + 1</strong> pattern translated
 * from the COBOL source:
 * <ol>
 *   <li>{@link #findMaxTranId()} returns the current maximum
 *       16-character {@code tran_id} value (or {@link Optional#empty()}
 *       if no rows exist);</li>
 *   <li>The service ({@code TransactionAddService} or
 *       {@code BillPaymentService}) parses the string as a numeric
 *       value, increments it by 1, and re-formats with
 *       {@code String.format("%016d", n + 1)} to zero-pad back to
 *       exactly 16 characters;</li>
 *   <li>The generated ID is set on the {@link Transaction#setTranId(String)}
 *       field before {@link #save(Object)} is called.</li>
 * </ol>
 * <p>This mirrors the COBOL
 * {@code STARTBR / READPREV / ADD 1 TO WS-TRAN-ID-N} pattern at
 * {@code app/cbl/COTRN02C.cbl} L444-L451 and
 * {@code app/cbl/COBIL00C.cbl} L209-L217 verbatim. The Java target
 * elects NOT to use a JPA sequence because the COBOL parallel-run
 * validation requires that two systems running side-by-side produce
 * byte-identical IDs &mdash; that constraint is preserved only by the
 * MAX-ID + 1 pattern. Concurrent inserts MAY race; the database
 * enforces uniqueness via the PRIMARY KEY constraint and the loser of
 * the race re-issues a fresh MAX query and retries (handled in the
 * service layer per AAP &sect;0.7.3 Minimal Change Clause).</p>
 *
 * <h2>No {@code @Version} (AAP &sect;0.4.1)</h2>
 *
 * <p>This entity does <em>not</em> carry a JPA {@code @Version} column
 * &mdash; transactions are append-only (immutable once posted), and
 * the source COBOL never performs {@code REWRITE} on this cluster.
 * Optimistic locking is unnecessary; the AAP explicitly limits
 * {@code @Version} to the {@code Account} and {@code Card} entities.</p>
 *
 * <h2>PCI-DSS Cardholder Data Scope (AAP &sect;0.6.6)</h2>
 *
 * <p>This repository operates over the PAN (Primary Account Number)
 * via the {@code tran_card_num} foreign-key column. Callers
 * <strong>MUST NOT</strong> log the {@code tranCardNum} value directly;
 * the CloudWatch log-filter regex declared by
 * {@code infrastructure/terraform/cloudwatch.tf} detects PAN-like
 * sequences and triggers alerts (AAP &sect;0.6.6). Encryption at rest
 * is delegated to RDS via the customer-managed KMS key; encryption in
 * transit is enforced by the {@code rds.force_ssl=1} parameter.</p>
 *
 * <h2>Consumers (Java services replacing the COBOL programs)</h2>
 * <ul>
 *   <li>{@code TransactionDetailService} ({@code COTRN01C}) &mdash;
 *       random read by 16-character {@code tranId} via
 *       {@link #findById(Object)}; miss surfaces as
 *       {@code RecordNotFoundException} (COBOL {@code FILE STATUS 23}).</li>
 *   <li>{@code TransactionListService} ({@code COTRN00C}) &mdash;
 *       paginated browse for the {@code COTRN00.bms} 10-row-per-page
 *       list, via {@link #findAll(Pageable)} or
 *       {@link #findByTranCardNumOrderByTranProcTsDesc(String, Pageable)}
 *       when filtered by card.</li>
 *   <li>{@code TransactionAddService} ({@code COTRN02C}) &mdash; calls
 *       {@link #findMaxTranId()} to compute the next 16-character ID,
 *       then {@link #save(Object)} to persist; publishes
 *       {@code transaction.posted} to MSK partitioned by account ID
 *       (AAP &sect;0.6.5).</li>
 *   <li>{@code BillPaymentService} ({@code COBIL00C}) &mdash; same
 *       MAX-ID + 1 pattern; persists the offsetting transaction row
 *       inside a {@code @Transactional} boundary that simultaneously
 *       decrements {@code acct_curr_bal}.</li>
 *   <li>{@code TransactionPostingService} ({@code CBTRN02C}) &mdash;
 *       bulk insert of accepted daily-transaction records after the
 *       4-stage validation cascade; reject codes 100-109 are preserved
 *       verbatim per AAP &sect;0.4.1.</li>
 *   <li>{@code TransactionReportService} ({@code CBTRN03C} report
 *       variant) &mdash; date-windowed report generation via
 *       {@link #findByTranProcTsBetween(LocalDateTime, LocalDateTime,
 *       Pageable)} or
 *       {@link #findByTranCardNumAndTranProcTsBetweenOrderByTranProcTsAsc(String,
 *       LocalDateTime, LocalDateTime, Pageable)}; output written to S3
 *       via {@code S3OutputService}.</li>
 *   <li>{@code StatementGenerationService} ({@code CBSTM03A/03B})
 *       &mdash; per-card statement-cycle scan via
 *       {@link #findByTranCardNumAndTranProcTsBetweenOrderByTranProcTsAsc(String,
 *       LocalDateTime, LocalDateTime, Pageable)}; the composite
 *       secondary index supports the date-range scan.</li>
 * </ul>
 *
 * <h2>Exception translation</h2>
 *
 * <p>The {@link Repository &#64;Repository} stereotype enables Spring's
 * persistence exception translation. {@code GlobalExceptionHandler}
 * then maps:
 * <ul>
 *   <li>{@code EmptyResultDataAccessException} &rarr;
 *       {@code RecordNotFoundException} &rarr; HTTP 404;</li>
 *   <li>{@code DataIntegrityViolationException} on duplicate insert
 *       &rarr; {@code DuplicateRecordException} &rarr; HTTP 409;</li>
 * </ul>
 *
 * <h2>No-AWS-SDK isolation (AAP &sect;0.7.1)</h2>
 *
 * <p>This repository contains no AWS SDK client wiring. All AWS service
 * integrations are isolated in the {@code com.awsm2.carddemo.adapter}
 * package. The repository is pure Spring Data JPA and depends only on
 * the {@link Transaction} domain entity and standard Spring framework
 * types.</p>
 *
 * @see com.awsm2.carddemo.domain.Transaction
 *      the JPA entity mapped to the {@code transactions} table
 */
@Repository
public interface TransactionRepository extends JpaRepository<Transaction, String> {

    /**
     * Returns the maximum 16-character {@code tran_id} value across all
     * rows in the {@code transactions} table &mdash; the JPA replacement
     * for the COBOL VSAM {@code STARTBR ... HIGH-VALUES / READPREV}
     * pattern used by {@code app/cbl/COTRN02C.cbl} L444-L451 and
     * {@code app/cbl/COBIL00C.cbl} L209-L217 to compute the "next"
     * transaction ID.
     *
     * <p>The JPQL behind this annotated query is:</p>
     * <pre>
     *     SELECT MAX(t.tranId) FROM Transaction t
     * </pre>
     * <p>which, executed against PostgreSQL, performs an index-only
     * scan over the {@code pk_transactions} primary-key B-tree to
     * return the maximum value in O(log n) time. {@link Optional#empty()}
     * is returned when the table is empty (rather than {@code null})
     * so that callers can use {@link Optional#orElse(Object)} to
     * default to {@code "0000000000000000"} for the first-row insert.</p>
     *
     * <p><strong>Generation pattern (AAP &sect;0.6.2):</strong>
     * Calling services use this method as follows:</p>
     * <pre>
     *     String maxId = transactionRepository.findMaxTranId()
     *                          .orElse("0000000000000000");
     *     long next = Long.parseLong(maxId) + 1L;
     *     String nextId = String.format("%016d", next);
     *     transaction.setTranId(nextId);
     *     transactionRepository.save(transaction);
     * </pre>
     * <p>Concurrent inserts MAY race; the database enforces uniqueness
     * via the {@code pk_transactions} constraint and the loser of the
     * race re-issues a fresh {@link #findMaxTranId()} and retries.</p>
     *
     * @return the maximum {@code tran_id} value, or
     *         {@link Optional#empty()} if no transactions exist
     */
    @Query("SELECT MAX(t.tranId) FROM Transaction t")
    Optional<String> findMaxTranId();

    /**
     * Returns the transactions associated with a specific card,
     * ordered by descending processing timestamp &mdash; the paged
     * browse used by the {@code COTRN00.bms} 10-row-per-page list
     * screen ({@code app/cbl/COTRN00C.cbl}).
     *
     * <p>Spring Data JPA translates this derived method name into:</p>
     * <pre>
     *     SELECT t FROM Transaction t
     *      WHERE t.tranCardNum = :cardNum
     *      ORDER BY t.tranProcTs DESC
     * </pre>
     * <p>which uses the {@code idx_transactions_card_proc_ts} composite
     * secondary index declared by V005.</p>
     *
     * @param cardNum  the 16-character {@code tran_card_num}; never
     *                 {@code null}
     * @param pageable Spring Data paging request supplying
     *                 {@code pageNumber} and {@code pageSize}; never
     *                 {@code null}
     * @return a {@link Page} envelope containing the matching rows;
     *         never {@code null}
     */
    Page<Transaction> findByTranCardNumOrderByTranProcTsDesc(String cardNum, Pageable pageable);

    /**
     * Returns the transactions for a specific card within an inclusive
     * processing-timestamp window, ordered by ascending processing
     * timestamp &mdash; the per-card chronological scan used by
     * {@code StatementGenerationService} ({@code CBSTM03A/CBSTM03B}) and
     * {@code TransactionReportService} ({@code CBTRN03C}).
     *
     * <p>Spring Data JPA translates this derived method name into:</p>
     * <pre>
     *     SELECT t FROM Transaction t
     *      WHERE t.tranCardNum = :cardNum
     *        AND t.tranProcTs BETWEEN :start AND :end
     *      ORDER BY t.tranProcTs ASC
     * </pre>
     * <p>which fully exploits the {@code idx_transactions_card_proc_ts}
     * composite secondary index for both the equality and the range
     * predicate.</p>
     *
     * @param cardNum  the 16-character {@code tran_card_num}; never
     *                 {@code null}
     * @param start    inclusive lower bound of the processing-timestamp
     *                 window; never {@code null}
     * @param end      inclusive upper bound of the processing-timestamp
     *                 window; never {@code null}
     * @param pageable Spring Data paging request; never {@code null}
     * @return a {@link Page} envelope containing the matching rows;
     *         never {@code null}
     */
    Page<Transaction> findByTranCardNumAndTranProcTsBetweenOrderByTranProcTsAsc(
            String cardNum,
            LocalDateTime start,
            LocalDateTime end,
            Pageable pageable);

    /**
     * Returns the transactions whose processing timestamp falls inside
     * the supplied inclusive window &mdash; the cross-card date-range
     * scan used by {@code TransactionReportService} ({@code CBTRN03C})
     * when generating a system-wide report.
     *
     * <p>Spring Data JPA translates this derived method name into:</p>
     * <pre>
     *     SELECT t FROM Transaction t
     *      WHERE t.tranProcTs BETWEEN :start AND :end
     * </pre>
     *
     * @param start    inclusive lower bound; never {@code null}
     * @param end      inclusive upper bound; never {@code null}
     * @param pageable Spring Data paging request; never {@code null}
     * @return a {@link Page} envelope containing the matching rows;
     *         never {@code null}
     */
    Page<Transaction> findByTranProcTsBetween(LocalDateTime start, LocalDateTime end, Pageable pageable);

    /**
     * Returns the eager list of all transactions for a specific card
     * &mdash; convenience helper for callers that need the full
     * per-card history (use with caution; row count is unbounded in
     * principle).
     *
     * @param cardNum the 16-character {@code tran_card_num}; never
     *                {@code null}
     * @return the matching rows; never {@code null}
     */
    List<Transaction> findByTranCardNum(String cardNum);
}
