/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.awsm2.carddemo.repository;

import com.awsm2.carddemo.domain.UserSecurity;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data JPA repository for the {@link UserSecurity} entity &mdash; the
 * authentication/authorization aggregate that powers signon and user
 * administration in the CardDemo Java target.
 *
 * <p><strong>Replaces VSAM cluster:</strong>
 * {@code AWS.M2.CARDDEMO.USRSEC.VSAM.KSDS} (defined in
 * {@code app/jcl/DUSRSECJ.jcl}:L62&ndash;L73 with
 * {@code KEYS(8 0)}, {@code RECORDSIZE(80 80)}, {@code REUSE},
 * {@code INDEXED}, {@code FREESPACE(10 15)}, {@code CISZ(8192)} &mdash;
 * 8-byte primary key {@code SEC-USR-ID} at relative key position 0).
 * The relational target is the {@code user_security} table created by
 * Flyway migration {@code V010__create_user_security.sql} and seeded by
 * {@code V015__seed_default_users.sql} (10 default users:
 * {@code ADMIN001}&ndash;{@code ADMIN005} and
 * {@code USER0001}&ndash;{@code USER0005}). The COBOL VSAM
 * {@code READ}/{@code WRITE}/{@code REWRITE}/{@code DELETE} verbs are
 * replaced by the inherited Spring Data JPA methods
 * ({@link #findById(Object)}, {@link #save(Object)},
 * {@link #deleteById(Object)}, {@link #existsById(Object)}), and the
 * CICS {@code STARTBR}/{@code READNEXT} browse loop used for the user
 * list is replaced by the custom derived paged query
 * {@link #findBySecUsrIdGreaterThanEqualOrderBySecUsrIdAsc(String, Pageable)}.</p>
 *
 * <p><strong>Source copybook:</strong> {@code app/cpy/CSUSR01Y.cpy} &mdash;
 * the {@code SEC-USER-DATA} layout (RECLN 80 bytes): 8-byte primary key
 * {@code SEC-USR-ID} ({@code PIC X(08)}), 20-byte first/last names
 * ({@code SEC-USR-FNAME}/{@code SEC-USR-LNAME PIC X(20)}), 8-byte
 * password ({@code SEC-USR-PWD PIC X(08)} &mdash; <em>upgraded to BCrypt
 * hash in the Java target, see Security Upgrade below</em>), 1-byte role
 * discriminator ({@code SEC-USR-TYPE PIC X(01)} &mdash; {@code 'A'}=admin
 * or {@code 'U'}=user), and a 23-byte trailing {@code FILLER PIC X(23)}
 * that is omitted in the relational model.</p>
 *
 * <h2>Security Upgrade (AAP &sect;0.1.1, &sect;0.7.1)</h2>
 *
 * <p>The COBOL {@code SEC-USR-PWD} field is {@code PIC X(08)} &mdash; 8
 * plaintext characters fixed-width inside the 80-byte SEC-USER-DATA
 * record. In the Java target, the corresponding {@code sec_usr_pwd}
 * column is widened to {@code VARCHAR(60)} to hold BCrypt
 * (strength {@code 12}) hashes generated by Spring Security's
 * {@code BCryptPasswordEncoder}; the
 * {@code $2[abxy]$<cost>$<22-char-salt><31-char-hash>} format fits
 * exactly within the 60-character column (Flyway migration
 * {@code V010__create_user_security.sql}, seeded by
 * {@code V015__seed_default_users.sql} with pre-computed hashes derived
 * offline from the original COBOL plaintext defaults &mdash;
 * {@code 'PASSWORDA'} for admins, {@code 'PASSWORDU'} for users).</p>
 *
 * <p>Repository operations on this interface remain identical regardless
 * of whether the column holds plaintext or hashed values &mdash; the
 * 60-character hash is stored and retrieved as an opaque blob. Password
 * <em>verification</em> is performed by {@code BCryptPasswordEncoder.matches(rawPassword,
 * storedHash)} in the security layer
 * ({@code src/main/java/com/awsm2/carddemo/security/}), <strong>NEVER
 * via a JPA query on this repository</strong>. There is no
 * {@code findBySecUsrIdAndSecUsrPwd(String, String)} method here, and no
 * {@code @Query} that matches passwords &mdash; such a method would
 * (a) leak the password onto the SQL string in trace logs, breaking
 * PCI-DSS (AAP &sect;0.6.6), and (b) be incompatible with BCrypt's
 * per-hash random salt (two hashes of the same plaintext differ, so
 * SQL equality on the hash column is meaningless for authentication).</p>
 *
 * <h2>Primary key contract (KEYS(8 0))</h2>
 *
 * <p>The generic type parameter {@code String} matches
 * {@link UserSecurity#getSecUsrId()} which is a {@code VARCHAR(8)}
 * column preserving the COBOL {@code SEC-USR-ID PIC X(08)} 8-character
 * alphanumeric primary key. The IDCAMS {@code KEYS(8 0)} clause in
 * {@code app/jcl/DUSRSECJ.jcl} declares the key length (8 bytes) and
 * relative key position (offset 0 within the 80-byte record) &mdash;
 * those bytes are now the relational {@code sec_usr_id} primary-key
 * column. Identifiers are administratively assigned upstream (e.g.,
 * {@code "ADMIN001"}, {@code "USER0001"}) and preserved verbatim:
 * there is no {@code @GeneratedValue} on the entity's {@code @Id}
 * field, so callers MUST set the identifier before invoking
 * {@link #save(Object)}.</p>
 *
 * <h2>Browse pattern (CICS STARTBR / READNEXT)</h2>
 *
 * <p>The COBOL user-list program {@code app/cbl/COUSR00C.cbl} performs
 * a CICS keyed-browse pattern to list users 10-per-page:</p>
 * <pre>
 *     EXEC CICS STARTBR
 *               DATASET  ('USRSEC')
 *               RIDFLD   (SEC-USR-ID)
 *     *         GTEQ                   (default key-comparison)
 *               RESP     (WS-RESP-CD)
 *     END-EXEC.
 *     PERFORM 10 TIMES
 *         EXEC CICS READNEXT
 *                   DATASET  ('USRSEC')
 *                   INTO     (SEC-USER-DATA)
 *                   RIDFLD   (SEC-USR-ID)
 *                   RESP     (WS-RESP-CD)
 *         END-EXEC.
 *     END-PERFORM.
 *     EXEC CICS ENDBR DATASET('USRSEC') END-EXEC.
 * </pre>
 * <p>The semantics are: position the browse cursor at the first key
 * greater-than-or-equal to {@code SEC-USR-ID} (the GTEQ comparison),
 * then read up to 10 sequential records in ascending key order. These
 * semantics are reproduced by the custom derived query
 * {@link #findBySecUsrIdGreaterThanEqualOrderBySecUsrIdAsc(String, Pageable)}
 * &mdash; Spring Data translates the method name into the JPQL
 * {@code SELECT u FROM UserSecurity u WHERE u.secUsrId >= :startId ORDER BY u.secUsrId ASC}
 * which is logically identical to the CICS browse loop. Page size of
 * {@code 10} is the {@code COUSR00.bms} default
 * (per {@code app/bms/COUSR00.bms} &mdash; the
 * {@code USER-REC OCCURS 10 TIMES} working-storage array in
 * {@code COUSR00C.cbl}:L56&ndash;L64).</p>
 *
 * <h2>Consumers (Java services replacing the COBOL programs)</h2>
 * <ul>
 *   <li>{@code SignonService} &mdash; performs {@link #findById(Object)}
 *       by 8-character user ID, then verifies the supplied password
 *       against the stored BCrypt hash via
 *       {@code BCryptPasswordEncoder.matches(...)} in the security
 *       layer (replacement for {@code app/cbl/COSGN00C.cbl}). A miss
 *       on {@code findById} surfaces as {@code RecordNotFoundException}
 *       per the COBOL {@code FILE STATUS 23} (NOTFND) contract.</li>
 *   <li>{@code UserListService} &mdash; paginated browse
 *       (10 rows / page per {@code app/bms/COUSR00.bms}) via
 *       {@link #findBySecUsrIdGreaterThanEqualOrderBySecUsrIdAsc(String, Pageable)},
 *       passing {@code PageRequest.of(pageNumber, 10)} (replacement
 *       for {@code app/cbl/COUSR00C.cbl}).</li>
 *   <li>{@code UserAddService} &mdash; duplicate-key detection via
 *       {@link #existsById(Object)} (preserves the COBOL
 *       {@code FILE STATUS 22} DUPKEY contract surfaced as
 *       {@code DuplicateRecordException}), then BCrypt-hashes the
 *       caller-supplied plaintext password and persists via
 *       {@link #save(Object)} (replacement for
 *       {@code app/cbl/COUSR01C.cbl}; preserves the COBOL
 *       {@code EXEC CICS WRITE DATASET('USRSEC')} contract).</li>
 *   <li>{@code UserUpdateService} &mdash; {@link #findById(Object)} +
 *       in-place mutation + {@link #save(Object)}; re-hashes the
 *       password via {@code BCryptPasswordEncoder} when changed
 *       (replacement for {@code app/cbl/COUSR02C.cbl}; preserves the
 *       COBOL {@code EXEC CICS READ ... REWRITE} contract).</li>
 *   <li>{@code UserDeleteService} &mdash; {@link #findById(Object)}
 *       (confirmation display) followed by {@link #deleteById(Object)}
 *       (replacement for {@code app/cbl/COUSR03C.cbl}; preserves the
 *       COBOL {@code EXEC CICS READ ... DELETE} contract).</li>
 * </ul>
 *
 * <h2>Role-based access (CHECK constraint {@code chk_user_security_type})</h2>
 *
 * <p>The {@link UserSecurity#getSecUsrType()} field carries the role
 * discriminator inherited from the COBOL {@code SEC-USR-TYPE PIC X(01)}
 * field: {@code 'A'} for ADMIN, {@code 'U'} for USER. This repository
 * does <em>NOT</em> filter by {@code sec_usr_type} &mdash; role-based
 * access is enforced in Spring Security's {@code SecurityConfig}
 * ({@code 'A'} &rarr; {@code "ROLE_ADMIN"}; {@code 'U'} &rarr;
 * {@code "ROLE_USER"}) and surfaced to endpoints via
 * {@code @PreAuthorize}. This repository returns all user types
 * unconditionally and lets the security layer make the
 * authorisation decision (AAP &sect;0.7.1).</p>
 *
 * <h2>Exception translation</h2>
 *
 * <p>The {@link Repository @Repository} stereotype annotation enables
 * Spring's {@code PersistenceExceptionTranslationPostProcessor} to
 * convert JPA-specific exceptions
 * ({@code jakarta.persistence.OptimisticLockException},
 * {@code jakarta.persistence.EntityNotFoundException}, JDBC
 * {@code SQLIntegrityConstraintViolationException}, etc.) into Spring's
 * unchecked {@code DataAccessException} hierarchy
 * ({@code ObjectOptimisticLockingFailureException},
 * {@code EmptyResultDataAccessException},
 * {@code DataIntegrityViolationException}). The
 * {@code GlobalExceptionHandler} (@RestControllerAdvice) further
 * translates these into the typed CardDemo domain-exception hierarchy
 * &mdash; {@code RecordNotFoundException}
 * ({@code COBOL FILE STATUS 23} &rarr; HTTP 404),
 * {@code DuplicateRecordException}
 * ({@code COBOL FILE STATUS 22} &rarr; HTTP 409),
 * {@code ConcurrentModificationException} (JPA optimistic-lock
 * conflict &rarr; HTTP 409) &mdash; preserving the COBOL
 * condition-code semantics surfaced to downstream consumers
 * (AAP &sect;0.7.1).</p>
 *
 * <h2>No-AWS-SDK isolation (AAP &sect;0.7.1)</h2>
 *
 * <p>This repository contains no AWS SDK client wiring. All AWS service
 * integrations (Secrets Manager for the JDBC password, KMS for
 * encryption-at-rest, CloudWatch for metrics, OpenSearch for audit
 * indexing) are isolated in the
 * {@code com.awsm2.carddemo.adapter} package and wired into the
 * {@code DataSource}/{@code EntityManagerFactory} beans declared by
 * {@code JpaConfig} and {@code SecretsManagerConfig}. The repository
 * itself is pure Spring Data JPA and depends only on the
 * {@link UserSecurity} domain entity and standard Spring framework
 * types.</p>
 *
 * @see com.awsm2.carddemo.domain.UserSecurity
 *      the JPA entity mapped to the {@code user_security} table
 */
@Repository
public interface UserSecurityRepository extends JpaRepository<UserSecurity, String> {

    /**
     * Paged, key-ordered scan starting at or after the given user ID
     * &mdash; the JPA replacement for the CICS {@code STARTBR ... GTEQ
     * ... READNEXT} keyed browse loop in {@code app/cbl/COUSR00C.cbl}.
     *
     * <p>Spring Data JPA translates this derived method name into the
     * JPQL query:</p>
     * <pre>
     *     SELECT u FROM UserSecurity u
     *      WHERE u.secUsrId &gt;= :startId
     *      ORDER BY u.secUsrId ASC
     * </pre>
     * <p>which, executed against PostgreSQL, traverses the
     * {@code pk_user_security} primary-key index in ascending order
     * starting at the first key {@code &gt;= startId}, then returns up
     * to {@code pageable.getPageSize()} rows. The result envelope
     * ({@link Page}) carries the rows on the current page plus total
     * page count and total element count, supporting the
     * {@code COUSR00.bms} list-pagination footer ("Page n of m").</p>
     *
     * <p><strong>Ordering invariant:</strong> the method name ends in
     * {@code OrderBySecUsrIdAsc}, which forces Spring Data to emit
     * {@code ORDER BY u.secUsrId ASC} regardless of any {@code Sort}
     * embedded in the {@link Pageable}. This matches the deterministic
     * ascending-key traversal semantics of the CICS browse loop and
     * the VSAM KSDS physical ordering &mdash; the JPA layer never
     * presents the rows out of order even under concurrent inserts.</p>
     *
     * <p><strong>Page size:</strong> the {@code COUSR00.bms} screen
     * displays exactly 10 user rows
     * (the {@code USER-REC OCCURS 10 TIMES} working-storage array in
     * {@code app/cbl/COUSR00C.cbl}:L56&ndash;L64), so the
     * {@code UserListService} typically passes
     * {@code PageRequest.of(pageNumber, 10)}. Callers MAY request a
     * different page size for administrative reports or for the
     * Backstage catalog UI &mdash; the repository imposes no
     * upper bound itself.</p>
     *
     * <p><strong>Starting key convention:</strong> pass an empty
     * string {@code ""} or the all-zeros sentinel {@code "00000000"}
     * to start at the beginning of the table; pass the last-seen
     * user ID from the previous page to resume browsing (matching
     * the COBOL {@code CDEMO-CU00-USRID-LAST} COMMAREA carry-forward
     * pattern in {@code COUSR00C.cbl} L67&ndash;L75).</p>
     *
     * <p><strong>Empty result:</strong> when no row satisfies
     * {@code sec_usr_id &gt;= startId}, returns an empty
     * {@link Page} (never {@code null}) with
     * {@link Page#getTotalElements()} {@code = 0} and
     * {@link Page#getTotalPages()} {@code = 0} &mdash; the JPA
     * equivalent of the COBOL {@code WS-USER-SEC-EOF = 'Y'} flag
     * raised after the {@code READNEXT} returns {@code FILE STATUS 23}
     * NOTFND on the first iteration.</p>
     *
     * @param startId  the starting user ID (inclusive); pass an empty
     *                 string {@code ""} or {@code "00000000"} to start
     *                 at the beginning of the table. Must be
     *                 non-{@code null}; an empty string is the
     *                 canonical "begin of table" sentinel.
     * @param pageable pagination request carrying page number and
     *                 page size (typically
     *                 {@code PageRequest.of(pageNumber, 10)} per
     *                 {@code app/bms/COUSR00.bms}). Must be
     *                 non-{@code null}; use
     *                 {@code Pageable.unpaged()} only for
     *                 administrative full-table exports.
     * @return paged result containing matching rows in ascending
     *         {@code secUsrId} order; an empty {@link Page} (never
     *         {@code null}) when no rows match.
     */
    Page<UserSecurity> findBySecUsrIdGreaterThanEqualOrderBySecUsrIdAsc(String startId, Pageable pageable);
}
