package com.carddemo.model.dto;

import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;

/**
 * Immutable request payload for the transaction-add endpoint
 * {@code POST /api/transactions}.
 *
 * <p>Mirrors the input/editable fields of the {@code COTRN02} BMS symbolic map
 * and is consumed by {@code TransactionAddService} (originating program
 * {@code COTRN02C}). The new transaction identifier is <em>not</em> supplied by
 * the client: it is auto-generated by the service using a browse-to-end and
 * increment strategy (Factory pattern), reproducing the COBOL ID-assignment
 * behavior, so no transaction-id component appears on this contract.</p>
 *
 * <p>The monetary {@code amount} field (COBOL {@code TRAN-AMT PIC S9(9)V99}) is
 * modeled with {@link java.math.BigDecimal} and constrained to nine integer and
 * two fractional digits to preserve the exact COBOL fixed-point precision; no
 * binary floating-point type is used. Every remaining field is a {@link String}
 * whose maximum length matches the corresponding symbolic-map field, and the
 * bean-validation constraints express the {@code COTRN02}/{@code CSSETATY}
 * field-edit semantics (mandatory, numeric, and length rules) as declarative
 * Jakarta Bean Validation annotations.</p>
 *
 * <p>Response-only and presentation elements of the map — the error message
 * line ({@code ERRMSG}), screen titles, date/time, program name, and PF-key
 * legend — are intentionally excluded from this request contract. Source commit
 * 27d6c6f.</p>
 *
 * @param accountId    account identifier (COBOL {@code ACTIDIN}); numeric, up to 11 digits
 * @param cardNumber   card number (COBOL {@code CARDNIN}); numeric, up to 16 digits
 * @param typeCode     transaction type code (COBOL {@code TTYPCD}); up to 2 characters
 * @param categoryCode transaction category code (COBOL {@code TCATCD}); up to 4 characters
 * @param source       transaction source (COBOL {@code TRNSRC}); up to 10 characters
 * @param description  transaction description (COBOL {@code TDESC}); up to 60 characters
 * @param amount       transaction amount (COBOL {@code TRNAMT} / {@code TRAN-AMT PIC S9(9)V99})
 * @param originDate   origination date (COBOL {@code TORIGDT}); up to 10 characters
 * @param processDate  processing date (COBOL {@code TPROCDT}); up to 10 characters
 * @param merchantId   merchant identifier (COBOL {@code MID}); up to 9 characters
 * @param merchantName merchant name (COBOL {@code MNAME}); up to 30 characters
 * @param merchantCity merchant city (COBOL {@code MCITY}); up to 25 characters
 * @param merchantZip  merchant ZIP code (COBOL {@code MZIP}); up to 10 characters
 * @param confirm      confirmation flag (COBOL {@code CONFIRM}); single character
 */
public record TransactionAddRequest(
        @NotBlank @Pattern(regexp = "\\d{1,11}") @Size(max = 11) String accountId,
        @NotBlank @Pattern(regexp = "\\d{1,16}") @Size(max = 16) String cardNumber,
        @Size(max = 2) String typeCode,
        @Size(max = 4) String categoryCode,
        @Size(max = 10) String source,
        @Size(max = 60) String description,
        @NotNull @Digits(integer = 9, fraction = 2) BigDecimal amount,
        @Size(max = 10) String originDate,
        @Size(max = 10) String processDate,
        @Size(max = 9) String merchantId,
        @Size(max = 30) String merchantName,
        @Size(max = 25) String merchantCity,
        @Size(max = 10) String merchantZip,
        @Size(max = 1) String confirm) {
}
